.github/workflows/release.yml

Adds a docker deploy. Keeps it "safe" to push upstream - Netlify would just need to input their Docker Hub details into the repository Settings > Secrets.
This always tags the image as "dev", although I could potentially add version numbers if that seems more useful

chore: adds a "dev" docker deployment on any push to master

---

api/external.go

chore: revert query param to fragment in external login callback url

chore: revert query param to fragment in external login callback url

---

api/auth.go
api/helpers.go
conf/configuration.go

Added new variable GOTRUE_JWT_ADMIN_ROLES which contains information about supported admin roles. Feature implemented according issue #45

Feat: added support for admin_roles variable

---

api/verify.go
mailer/template.go

Changed type of magic link from type=recover to type=magiclink according to issue #35  
I implemented that logic without changing db schema, but this change can potentually introduce buggy situation. 
When recovery called, db generate token and save it to recovery_token field and user get email with recovery link. After that someone call magiclink and new recovery_token rewrite old one and it delivered to user. After that user click to first recover link and got error. This situation can be reverted too.
@awalias Can we ignore that? or better add new fields to saving magiclink_token and sent time and fix it?

Feat: added type magiclink to verify links

---

api/verify.go
models/errors.go
models/user.go

Bug fix for [Signup Confirmation Email link](https://github.com/supabase/supabase/issues/504) on second and subsequent clicks.
Subsequent clicks on confirmation link sent when user signs up results in error `User not found`.
Descriptive error informing user that Confirmation Token was not found. 
User will also be redirected back to the application with the error context in the return url.

Fix for Signup Confirmation Email Link Issue

---

models/errors.go
models/user.go

Bug fix for Issue 504 where the Signup Confirmation Token is not found.
When a Signup email confirmation has already been confirmed, the subsequent click on that link returns a 404 error stating user not found.
Golang is not my primary language (and I am still learning a lot) so I would appreciate if feedback could be provided in case this fix I introduced is incorrect or can be improved further.

Fix for Issue 504 Signup Confirmation Email Link

---

README.md
api/api.go
api/external.go
api/external_oauth.go
api/provider/apple.go
api/settings.go
conf/configuration.go
go.mod
go.sum

Adds Apple as an OAuth provider. Addresses #37 
1. Apple makes use of OAuth2.0
2. `GOTRUE_EXTERNAL_APPLE_SECRET` refers to the `CLIENT_SECRET` that Apple requires you to generate. See the steps [here](http://p.agnihotry.com/post/validating_sign_in_with_apple_authorization_code/) and [here](https://medium.com/identity-beyond-borders/how-to-configure-sign-in-with-apple-77c61e336003) for information I personally found useful.

Feature: Add Apple Provider 🍎

---

Dockerfile

Updates the go image from 1.13 to 1.16 in the Dockerfile. Fixes #100 
Current version fails to build

chore: bump go version to 1.16

---

README.md
api/helpers.go

redirectTo needs to find an exact match with one of the URLs in the `URI_ALLOW_LIST` 
Addresses #107

Fix: redirectTo allows url which should not be permitted 

---

README.md
conf/configuration.go
mailer/mailer.go

Fixes #120 
AdminUser cannot add a custom sender name which results in the emails being blocked by some providers.
Exposes an env var `SMTP_SENDER_NAME` which allows the user to set a custom sender name. Defaults to the `SMTP_ADMIN_EMAIL` if empty.
*Not ideal, I'm gonna make a PR to the netlify repo that we use and change it [here](https://github.com/netlify/mailme/blob/9b1d3a9cef8bb81cebaebff53ac464c3d15f1a45/mailme.go#L69) but in the meantime, this will work on our end.

Fix: Add sender name to SMTP config

---

api/verify.go

As mentioned by hieu, on verify error, the redirect_to should be used as the redirect url instead of the default site URL

fix: verify failure should redirect to valid redirect_url

---

models/user.go

Bug fix, stores user emails in lowercase and performs case-insensitive query of existing email from users table.
Current behavior stores emails as they are provided by the user (unmodified). This this treats emails with different cases (e.g upper vs lowercase) as different emails / users.
#89
The new behavior saves all emails in lowercase and calls LOWER SQL function on email field when querying existing users.
Replaces [PR 108](https://github.com/supabase/gotrue/pull/108) correcting db dependant collation feature (Thanks @icecream78 for the catch) and follows [conventional commits guides](https://www.conventionalcommits.org)

fix: case-insensitive user emails - issue #89

---

api/provider/github.go
api/provider/provider.go
api/provider/twitter.go

During the OAuth login the usernames from Twitter and GitHub are retrieved and saved as meta_data of the user.
Additionally I've changed the authorization URL of Twitter from `https://api.twitter.com/oauth/authorize` to `https://api.twitter.com/oauth/authenticate` so that the user only has to authorize the application on the first login, instead of at every login.
Usernames from Twitter and GitHub are not retrieved.
The user has to authorize the Twitter App on every login again.
Usernames from Twitter and GitHub are retrieved and saved as meta_data.
The user only has to authorize the Twitter App on the first login.
Description for the /authenticate URL from Twitter:
https://developer.twitter.com/en/docs/authentication/api-reference/authenticate

Fix: Retrieve Twitter and GitHub usernames via OAuth

---

api/provider/discord.go
api/provider/provider.go

Addresses #130 
Returns `discord_id` in user_metadata as `provider_id`

fix: add discord id to user_metadata

---

README.md
api/admin.go
api/api.go
api/errors.go
api/invite.go
api/mail.go
api/signup.go
api/user.go
mailer/mailer.go
mailer/noop.go
mailer/template.go

Allows an admin user to generate email action links (`signup`, `magiclink`, `recovery`, `invite`).
Admin user cannot make use of their own custom email service (e.g. Sendgrid) or email templates to serve their customers. 
#109 
Adds a new admin endpoint: `POST /admin/generate_link?type=TYPE&redirect_to=REDIRECT_URL` 
Allows an admin user to generate the corresponding email action link to send in their custom email templates.
Requires admin credentials because the email action links contain the verification token used to sign a user in.
Sign up a new user via magiclink
Request: 
```
POST /admin/generate_link?type=magiclink&redirect_to=REDIRECT_URL
```
Response:
```
{
"action_link": "http://localhost:9999/verify?token=TOKEN&type=signup&redirect_to=REDIRECT_URL",
"app_metadata": { …
```

Feat: Generate email action links

---

api/errors.go

Missing " in struct tag causing lint to throw an error during github deploy action.

chore: fix incorrect struct tag

---

.github/workflows/release.yml

Adds `/migrations` to zip file for both arm64 and x86

Chore: Add /migrations to deploy workflow

---

README.md
api/token.go

* Update `/token` endpoint to allow login with phone
* If phone number is unconfirmed, return error.
* If user cannot be found by phone number, return error.
* Only allow user to login via email **or** phone but **not** email & phone
Sample curl request
```
curl -X POST 'http://localhost:9999/token?grant_type=password' \                                                                                                                                                              
-H "Content-Type: application/json" \
-d '{
"phone": "123456789",
"password": "super-secret-password"
}'
```

Fix: allow phone-password login

---

api/phone.go
api/sms_provider/sms_provider.go
api/sms_provider/twilio.go

Current sms otp message just sends the otp. This PR adds a default message in the format:
`Your OTP for {{ SITE_URL }} is {{ OTP }}`

fix: add default message for sending sms otp

---

api/signup.go
models/audit_log_entry.go

Adds audit log action when user requests for confirmation email / sms otp on signup.
```json
{
"action":"user_confirmation_requested",
"actor_id":"d01a130f-5498-4d60-971a-4236bf77b0b4",
"actor_username":"00000000",
"log_type":"user",
"timestamp":"2021-07-29T07:35:11Z"
}
```

Fix: Add user_confirmation_requested audit log action

---

api/phone.go
conf/configuration.go

The default message sent will always be "Your code is `{{ .Code }}`".

fix: add env var to set custom message for sms

---

api/provider/twitter.go

Updates the Twitter provider to use the HTTPS profile image URL instead of the default HTTP image URL.
The `AvatarURL` metadata for Twitter logins has a HTTP image URL.
The `AvatarURL` metadata for Twitter logins now uses the HTTPS image URL.

Twitter: use HTTPS profile image URL for `AvatarURL`

---

api/mail.go
api/verify.go
models/user.go

* Email change endpoint should redirect properly if only 1 email is confirmed. See #200 
* Email change confirmation status should reset when user requests to change email again (regardless of the current status)

fix: redirects on email change

---

api/signup.go

I fixed https://github.com/supabase/gotrue/issues/119 issue. Just changed the response message.
Returns a response message that may cause to attack by hackers. 
Hides the information of person that who is signed up for the service.
Reference: https://security.stackexchange.com/questions/234740/on-my-websites-account-creation-form-how-to-avoid-leaking-the-information-that/234757#234757

Fixed return message to avoid information leaking

---

api/middleware_test.go
security/hcaptcha.go

The hcaptcha token included in API requests gets pushed down a level
under the '__gotrue_meta_security' field to allow for greater
extensibility, while also communicating that the included data is for
Gotrue's consumption (vs a third-party provider, or user db).
Although this constitutes a breaking change in the API, the HCaptcha functionality is as-of-yet unsupported by our client libs, and was initially merged under an 'alpha' moniker, marking it liable to such changes.
https://github.com/supabase/gotrue-js/pull/128#issuecomment-917523658

fix: nest hcaptcha token under a more generic field

---

README.md
api/api.go
api/middleware.go
conf/configuration.go

* Add rate-limit on all endpoints that send out emails via `GOTRUE_RATE_LIMIT_EMAIL_SENT` env var. Default is set to 30. 
* Want to enforce rate-limit on only `PUT` or `POST` requests with `email` field in request body. 
* Can't seem to find a way to enforce a rate-limit over multiple endpoints collectively using tollbooth.

Fix: Add rate limiting on email endpoints

---

api/mail.go
api/user.go
api/verify.go
conf/configuration.go
mailer/template.go

- Allow custom email change templates. Send email change template to old email and confirmation email template to new email
- Change API responses to have a better response. It shouldn’t say email has changed when only one link has been clicked. Better message for confirming 1 email (it shouldn't be an error message)
- Option to disable double confirmation.

Fix: email change dx

---

api/token.go

Ensure that we return the same error message for a user not existing,
and their password being incorrect.
Credit to <chipilov@hotmail.com> for reporting this issue.

chore: avoid leaking user existence via Token endpoint

---

api/signup.go
models/audit_log_entry.go

* If autoconfirm is enabled:
```
{
"code":400,
"msg":"User already registered"
}
```
* Insert `user_repeated_signup` action into audit log trail  (if there is a repeated signup)

Fix: update repeated user signups

---

api/admin.go
api/admin_test.go

* Allow admin to create users regardless of whether `DISABLE_SIGNUP=true`, `GOTRUE_EXTERNAL_EMAIL_ENABLED=false` or `GOTRUE_EXTERNAL_PHONE_ENABLED=false`

Fix: allow signups always

---

hack/init_postgres.sql
migrations/20211124214934_update_auth_functions.up.sql

* Updates the auth.uid, auth.role, auth.email functions 
* Run ./hack/postgresd.sh
* `make build && ./gotrue` 
* `docker exec -it gotrue_postgresql psql -U postgres` 
* `select proname, proowner::regrole from pg_proc where pronamespace::regnamespace::text = 'auth';` 
```
proname |      proowner
---------+---------------------
role    | supabase_auth_admin
uid     | supabase_auth_admin
email   | supabase_auth_admin
```

fix: update auth functions

---

api/api.go
api/invite_test.go
api/signup.go
api/token.go

* Fixes #276 
* If the `providers` field returned contains "email", we still don't allow a user to use the refresh token. This is because it is impossible to tell if the user is refreshing a token for an email login or oauth provider login.

Fix: Allow refresh token grant if no email in providers field

---

api/admin.go
api/admin_test.go
api/errors.go
api/user.go
api/user_test.go

* `PUT /admin/users/<user_id>` with a password of length 0 should return an explicit error 
* `PUT /user` with a password of length 0 should return an explicit error 
* Standardise invalid password update error response for both `PUT /user` & `PUT /admin/users/<user_id>` to return a 422 unprocessable entity
* Resolves #294

fix: empty password update should return explicit error

---

api/verify.go
api/verify_test.go

* Developer reported that an expired invite link does not redirect the user to the redirect_url specified 
* User would not get redirect to the client page set up to handle invalid / expired tokens or otps

fix: redirect user on expired or invalid confirmaton token and otp 

---

api/external.go
api/external_github_test.go

* Return an error to tell the user that the oauth email being used is unverified
* User needs to verify the email associated with the oauth provider in order for the oauth flow to work
* Transaction will be rolled back an the user will not be created if they are using an unverified email

fix: return err if oauth provider email is unverified

---

api/admin.go
api/admin_test.go

* Fixes issue #301 in admin create user method which led to a nil pointer assignment
* Caused by [this PR](https://github.com/supabase/gotrue/pull/297) when updating the password field to be a string pointer

fix: admin create user

---

Makefile

Bug fix.
Version number is not displayed when running `gotrue version`.
This adds the version number at compile time.
This also switches to `git describe --tags` to get the version, which
displays either the Git tag for the current commit if it has been
tagged, or the last Git tag along with the number of commits on top of
the tag and the commit hash.
Fixes #272.

fix: Set version number at compile time

---

api/auth.go
api/logout.go
api/signup.go
api/token.go
api/verify.go

* to start the ball rolling for #279 
* sets access_token and refresh_token as individual cookies
1. Add this to `.env` file
```
GOTRUE_COOKIE_KEY="sb"
GOTRUE_COOKIE_DURATION="100"
```
2. Update `GOTRUE_MAILER_AUTOCONFIRM=true` in the `.env` file
3. Signup a new user
```
curl -X POST "http://localhost:9999/signup" -H "Content-Type: application/json" -d '{"email": "user@example.com", "password": "secret"}'
```
4. Take note of the refresh token returned above.
5. Try to get a new access token & refresh token
```
curl -X POST 'http://localhost:9999/token?grant_type=refresh_token' \
-d '{"refresh_token": "refresh_token_in_4"}' -H "Content-type: application/json" -H "x-use-cookie: some-value" -v
```
```
...
* Connected to localhost (127.0.0.1) port 9999 (#0)
> POST …
```

fix: set access_token & refresh_token in cookies 

---

api/provider/linkedin.go

* Linkedin always returns the primary email (which is guaranteed to be verified) when the `r_emailaddress` scope is requested

fix: linkedin email should be verified

---

api/external.go
api/external_github_test.go
mailer/mailer.go

* Fixes the following issue
- User initially signs up with external provider on gotrue
- User's email with external provider is unverified 
- User verifies email with external provider OR user changes email with external provider & verifies it
- User tries to sign-in with external provider on gotrue again 
* User should be confirmed since the email associated with the external provider has been verified already
>    - User verifies email with external provider OR user changes email with external provider & verifies it
* In the context of the latter, `auth.user.email` shouldn't be updated to reflect the new email associated with the identity
- we don't update the email in `auth.user.email` because that column has a unique constraint on it
- there is a possibility that a person has 2 user …

fix: verify identity email

---

api/signup.go
api/token.go

* always set the cookies on `/token` and `/signup` endpoints

fix: remove x-use-cookie header

---

README.md
api/admin.go
api/admin_test.go
api/external.go
api/external_github_test.go
api/token.go
api/token_test.go
api/verify.go
api/verify_test.go
migrations/20220114185221_update_user_idx.up.sql
migrations/20220114185340_add_ban_until.up.sql
migrations/20220114185340_add_banned_until.up.sql
models/user.go

* Adds a `ban_until` column in `auth.users` to restrict specific user access until a certain time.
* `GET /admin/users` should allow filtering by users
* `PUT /admin/users/<user_id>` should allow banning an existing user
- Update `adminUserParams` struct to include a `BanDuration` field
- Decided to use a duration rather than a timestamp or boolean since it seems like the best DX (users don't have to worry about following go's time format) and provides greater flexibility over a bool
* fixes #41
* Decided not to go with a middleware approach in view of having to make an extra query to the database to check if a user is banned or not. 
* The current implementation makes use of the existing query used to fetch the user and checks the `ban_until` column.
* Even though the current …

feat: add basic user banning functionality

---

README.md
api/errors.go
api/otp.go
api/otp_test.go

* Allows developer to decide whether to allow automatic signup for magiclinks / otps. 
* Fixes #311 
```bash
{
"phone": "12456789",
"create_user" true
}
or 
{
"email": "newUser@email.com",
"create_user" true
}
```
Both will result in a bad request with a message of "Signups not allowed for otp"

fix: add create_user field to otp endpoint

---

api/token.go

resolve this issue
#94 Self hosted Gitlab login provider support by exposing GOTRUE_EXTERNAL_GITLAB_URL as setting in UI
#159 Support arbitrary OpenID Connect providers for external authentication
#292 Allow org-specific endpoint to be specified for Azure OAuth provider
#299 Generic OpenID Connect auth provider
#94 Self hosted Gitlab login provider support by exposing GOTRUE_EXTERNAL_GITLAB_URL as setting in UI
#159 Support arbitrary OpenID Connect providers for external authentication
#292 Allow org-specific endpoint to be specified for Azure OAuth provider
#299 Generic OpenID Connect auth provider
https://github.com/supabase/supabase/pull/5181

resolve #94, #159, #292 and #299

---

api/provider/slack.go

This change adds Slack's `https://slack.com/team_id` as a custom claim.
Right now, it is difficult to use Supabase for apps that use Slack workspace membership as an authorization mechanism.
With this change, a user's Slack team ID is included in the `identity_data` column.
Slack API response [documentation](https://api.slack.com/authentication/sign-in-with-slack#response)

fix: add Slack Team ID custom claim

---

README.md
api/verify.go
api/verify_test.go
conf/configuration.go
mailer/template.go

* Fixes #139, #264, #368 
* Sends the OTP (which can either be a confirmation / invite / recovery / email change token) in the email together with the url link
* Developers can choose to omit `{{ .ConfirmationURL }}` from their email templates to prevent cases where email clients preview the URL thus resulting in the token being consumed. (addresses #368)
1. `POST /verify` now accepts an `email` field which would be used together with the token to verify the user. 
```json
{
"type": "signup",
"email": "foo@example.com",
"token": "random token",
"redirect_to": "my_redirect_to_url"
}
```
2. If `type=email_change` and `MAILER_SECURE_EMAIL_CHANGE_ENABLED=true`, the old email will be used for verifying both OTPs sent to the old and new email address.
1. I refactored the common parts in …

fix: send otp in email link

---

api/external_azure_test.go
api/provider/azure.go
api/token.go
conf/configuration.go

Another possible solution for Azure tenant configuration.
Unsupported via #179 
Similar to #270 but attempts to preserve the supported External Authentication Providers configuration by using the EXTERNAL_X_URL value for the auth host prefix.
`EXTERNAL_AZURE_URL=https://login.microsoftonline.com/{tenant_id}`
Removes the use of configuration value from the api path as it is the same in both use cases.

Adds support for Azure tenant configuration

---

api/verify.go

* Currently, the verification for a magiclink / recover sends a sign up action to the audit_log_entries table.
* We should be sending a login action instead.

fix: magiclink & recover verification should send login instead of signup action

---

api/verify.go

* recover verify should log a login action if the user is confirmed

fix: add login event to recover / magiclink verify

---

Dockerfile

Feature.
Old versions of Go and Alpine are used in the Dockerfile.
Upgrade to Go 1.17 and Alpine 3.15

Dockerfile: bump to Go 1.17 and Alpine 3.15

---

README.md
conf/configuration.go

* Default `password_min_length` to 6 if it's less than 0
* Add `split_words:"true"` to password_min_length to support camel case struct to env var name mapping (see https://github.com/kelseyhightower/envconfig#struct-tag-support)

fix: update password min length config

---

api/signup.go
api/token.go

* Fixes #141 
* Decided that for DX purposes, returning the user object after verification is fine.
* Unblocks https://github.com/supabase/gotrue-js/pull/228

fix: return user for POST verify endpoints

---

api/provider/zoom.go

* "Sign-in with zoom" via an email-password based zoom account requires gotrue to check if the email associated with zoom is verified or not. 
* "Sign-in with zoom" via oauth doesn't require gotrue to check if the email is verified because we assume that the oauth provider has already verified the email. 
* `verified` field returned from zoom only means something for email-password based signups. A user is `verified` (type 1) only if they received an email when their profile was created and confirmed the link. See [link](https://devforum.zoom.us/t/how-to-determine-if-a-zoom-user-actually-owns-their-email-address/44430) for more details.

fix: verify email for email-based zoom signup

---

conf/configuration.go

* Allows for setting the api url config of a provider like `GOTRUE_EXTERNAL_AZURE_API_URL` instead of `GOTRUE_EXTERNAL_AZURE_APIURL`

fix: api_url config

---

README.md
conf/configuration.go
storage/dial.go

* Currently, pop always defaults to an unlimited number of connections for the db pool, this PR allows one to set the desired pool size via `GOTRUE_DB_MAX_POOL_SIZE`

fix: allow max db pool size to be configurable

---

api/mail.go
api/user.go
api/user_test.go
api/verify.go
mailer/mailer.go
mailer/noop.go
mailer/template.go

* Fixes issue where updating a user's email fails if the existing email is empty (when `SECURE_EMAIL_CHANGE_ENABLED=true`)
* This issue happens because `SECURE_EMAIL_CHANGE_ENABLED` attempts to send an email confirmation link to both the current and new email, since the current email doesn't exist, the mail client fails to send the link.
* Refactored the `TemplateMailer` to use an interface for the `Mailer`. This makes mocking the `mailme.Mailer.Mail` method easier rather than just mocking the `EmailChangeMail` method.
* Added tests for updating a user

fix: update user email should not fail when current email doesn't exist

---

migrations/20220320143831_set_idle_transaction_timeout.up.sql

* Sets the `idle_in_transaction_session_timeout ` to 5mins instead of 0 (unlimited).
* Fixes issue where many long-running transactions are left in a state of `idle_in_transaction` which results in holding up too many connections

fix: set idle_in_transaction_session_timeout to 5min

---

migrations/20220320143831_set_idle_transaction_timeout.up.sql

The username is configurable via the connstring, and as such we can't
rely on it being supabase_auth_admin

fix: no longer hardcode username for migration

---

api/errors.go
api/otp.go
api/phone.go
api/phone_test.go
api/signup.go
api/user.go
api/user_test.go
api/verify.go
api/verify_test.go
go.sum

* Fixes #390 
* If `GOTRUE_SMS_AUTOCONFIRM` is enabled, an otp will not be sent to the new phone number, else, an otp will be sent to the new phone number and the user has to verify it first.
* Added a new verification type called `phone_change` which when set, will verify if the token sent is valid when compared to the `phone_change_token` and `phone_change_sent_at` fields
* Update gotrue-js to include the `phone_change` verification type (https://github.com/supabase/gotrue-js/blob/master/src/lib/types.ts#L202)

fix: allow user to update phone number

---

api/verify.go

Bug fix.
Adds a `LoginAction` to the audit log when the user is unconfirmed.
Adds a `UserSignedUpAction` to the audit log when the user is unconfirmed.
This fixes a leftover bug following PRs #395 and #396.

fix: add `UserSignedUpAction` to the audit log when the user is unconfirmed

---

api/verify.go

Bug fix.
The `emailChangeVerify` function created new transactions when performing updates, although an existing connection already exists.
The existing connection passed into `emailChangeVerify` is re-used. This aligns the connection handling behaviour with the rest of the functions in `api/verify.go`.
This looks like it might have been a leftover bug during refactoring in PR #379.

fix: re-use existing connection's transaction in `emailChangeVerify`

---

api/phone_test.go
api/reauthenticate.go
api/recover.go
api/user_test.go

* Add tests for phone auth failures
* remove phone recovery logic from recover endpoint (can just use `/otp` for phone recovery)
* return consistent error messages for `/signup`, `/otp`, `/reauthenticate`, `PUT /user` (phone_change)

fix: reauthenticate bugs

---

api/phone.go
api/reauthenticate.go
api/user.go
api/user_test.go
api/verify.go
api/verify_test.go
models/user.go

* Modifies DX for verifying a phone update
```
// Previous (POST /verify)
{
"phone": "11111111", // old phone number
"token": "123456",  // token sent to new phone number
"type": "phone_change"
}
// New (POST /verify)
{
"phone": "222222222", // new phone number
"token": "123456",  // token sent to new phone number
"type": "phone_change"
}
```
* Return clearer response for email change verification (when `SECURE_EMAIL_CHANGE_ENABLED = true`)
```
// Previous (POST /verify) - First confirmation
{
"email": "foo@example.com", 
"token": "123456",  
"type": "email_change"
}
// Response
null
// New (POST /verify) - First confirmation
{
"email": "foo@example.com",
"token": "123456",  
"type": "email_change"
}
// Response
{
"code": "200",
"msg": "Confirmation link accepted. Please proceed to …
```

fix: user email & phone update

---

mailer/template.go

* When a user updates their email, an email change template will always be sent to the new email instead of a confirm email template

fix: use email change template for current and new

---

api/token.go

Receiving a nonce is optional in the open id spec. Google has 2 apis, the older one does not return a nonce while the newer one does.
There's a risk of replay attack if there's no nonce, but that's why my PR makes passing the nonce optional ONLY if it's missing from the returned jwt
Fix(?) When using native auth on some platforms like Flutter's sign in with google, the idtoken that is returned does not contain a nonce.
The current behavior requires a nonce inside the id_token as well as a nonce passed.
If there is a nonce in the id_token, then a nonce is required in the body and vice versa.
Fixes and adds support for
https://github.com/supabase/gotrue/issues/412
https://github.com/supabase-community/gotrue-dart/issues/27
https://github.com/supabase-community/supabase-flutter/issues/5

BUG FIX: Only require nonce in id_token when also passed in body

---

CONTRIBUTING.md
Dockerfile.dev
Makefile
docker-compose-dev.yml

I setup my local development to use containers with hot reload. I made the changes pretty quick so there is room for improvement but I figured others could benefit from the changes. Everything was done without effecting the current development work flow. Improving the development setup will make it easier for others to get involved in the project. If these changes look good then I will do a followup PR to update documentation.
Anyone wishing to work on GoTrue must install manually dependencies locally and rebuild the binary every time they make a change.
Dependencies are installed within a container which will automatically rebuild GoTrue when a change is made to the source code. Everthing is captured in a handful of Makefile commands

Add dev containers with hot reload

---

api/mail.go
api/token.go
api/verify.go
crypto/crypto.go
mailer/template.go
migrations/20220412150300_add_unique_idx.up.sql
models/user.go

* Shortens email otp sent when the user requests for a confirmation, recovery, invite, email change, reauthentication and magic links
* Email otps will now be sent with a fixed length of 10 and will only contain alphanumeric characters
* Adds a partial unique index on the following db fields: `confirmation_token`, `recovery_token`, `email_change_token_new`, `email_change_token_current`, `reauthentication_token`

fix: shorten email otp 

---

api/provider/discord.go

Signed-off-by: Bariq <bariqhibat@gmail.com>
Fix #442
(Referenced from the issue)
> If you have a Discord discriminator that is #0999 or lower, the metadata stored doesn't respect the 4 int/string length and will show up as #999. In my case it just shows up as #1.

Change Discord's discriminator type to string

---

migrations/20220412150300_add_unique_idx.up.sql
migrations/20220429010200_add_unique_idx.up.sql

* Fixes bug in migration where unique partial index created fails consider the case where it is acceptable for phone OTPs to not be unique

fix: unique index should not apply to phone otps

---

api/api.go
api/token_test.go
conf/configuration.go

* Rename `GOTRUE_RATE_LIMIT_TOKEN` to `GOTRUE_RATE_LIMIT_TOKEN_REFRESH` for clarity
* This env var controls the rate limit on the `/token` endpoint and defaults to 30 requests over 5 mins with a burst of 30

chore: rename rate limit token endpoint env var

---

api/provider/apple.go
api/provider/notion.go
api/provider/provider.go
api/provider/twitch.go
api/sms_provider/messagebird.go
api/sms_provider/sms_provider.go
api/sms_provider/textlocal.go
api/sms_provider/twilio.go
api/sms_provider/vonage.go

* Adds a default 10 sec http timeout to all external oauth / sms provider requests

fix: add http timeout to add external provider requests

---

migrations/20220531120530_add_auth_jwt_function.up.sql

* Add `auth.jwt()` function to return the user's jwt claims
* Add comments to signal deprecating `auth.email`, `auth.uid`, `auth.role` and to use `auth.jwt` instead

fix: add auth.jwt() function

---

docker-compose-dev.yml

Running the make dev command fails without double quotes at the '-pattern' parameter
Bug fix (see #485)
`-pattern` Parameter is without double quotes " " and this causes issues running docker-compose command.
I added the double quotes and with these it works flawlessly (at least on my Debian WSL).

fix$docker-compose: add double quotes to command

---

api/admin.go
api/admin_test.go
api/audit_test.go
api/external_test.go
api/hook_test.go
api/invite_test.go
api/phone_test.go
api/provider/saml.go
api/recover_test.go
api/signup.go
api/signup_test.go
api/token_test.go
api/user_test.go
api/verify_test.go
cmd/admin_cmd.go
cmd/serve_cmd.go
models/identity_test.go
models/refresh_token_test.go
models/user.go
models/user_test.go

Refactors our NewUser to take in a phone param.
No phone param
I've left the admin command as is as I think it's not often used and probably might cause more confusion for existing users if we refactor it to take in phone since they might be accustomed to the old syntax.
I have also left the `createUser` refactor as a TODO for another PR and would take substantial refactor. We can also opt not to update it as it is used in `external_test.go` and the behaviour doesn't seem to be affected by whether or not we have a phone number.

Refactor New User to take in phone

---

cmd/migrate_cmd.go

This allows [automated] migrations activity to be differentiated from
user-initiated activity.

chore: specify an application_name when running migrations

---

.github/workflows/test.yml
Makefile
api/admin.go
api/audit.go
api/hook_test.go
models/audit_log_entry.go
models/instance.go
models/user_test.go

Add formatting checks
No checks

Add Formatting Checks to CI

---

api/api.go
api/middleware_test.go
security/hcaptcha.go

* Add captcha protection to `/verify` and `/token` endpoints
* Captcha protection is excluded from any `GET /verify` requests and `POST /token?grant_type=refresh_token`
* Renamed the captcha token field to make it more generic for future implementations of other captcha providers (e.g. reCaptcha) - this should only affect anyone self-hosting gotrue and using the captcha feature already 
* Decided not to enable captcha on the following endpoints
* `/admin` routes since those endpoint should only be called on the server-side
* `/user` since the user has to be logged in first in order to make calls to this endpoint
* `/settings`, `/authorize`, `/logout` - seems irrelevant

feat: add captcha to verify and token endpoints

---

migrations/20220607041349_add_mfa_schema.up.sql

Initial DB schema for MFA. Will add the indexes later in the implementation once I have a clearer idea of what to index
Note that I've changed the base branch to `mfa`  and will be using `j0_add_mfa` as a draft branch
- We've introduced the concept of a `factor_status` to differentiate between `disabled` factors and `unverified` factors. Factors can only be disabled once they are verified.
-  Challenges also have a `verification` status. Challenges are marked as verified once there is a successful verification
-  remove `factor_` prefix on the factor table and changed `simple_name` to `friendly_name`

Add DB changes

---

api/admin.go
api/api.go
api/audit.go
api/errors.go
api/hook_test.go
api/mfa.go
api/mfa_test.go
crypto/crypto.go
migrations/20220607041349_add_mfa_schema.up.sql
models/audit_log_entry.go
models/instance.go
models/recovery_code.go
models/recovery_code_test.go
models/user_test.go

This PR  should add the ability for a user signed in with a single factor(or more factors) to call `/mfa/%s/generate_recovery_codes` to produce recovery codes which will eventually be used to `SignIn`, recover a factor. 
Given the all encompassing nature of this endpoint it should eventually move out of the `/mfa` route.
There should also be a rate limiter on this but haven't decided on value.
None

Generate Recovery Codes 

---

README.md

OpenID Endpoint Configuration as mentioned in realm admin panel is not included '/auth/' in URL. keycloak [documents](https://www.keycloak.org/docs/latest/authorization_services/index.html#_service_authorization_api) describe endpoint URLs.
EXTERNAL_KEYCLOAK_URL = https://keycloak.example.com/auth/realms/myrealm IS NOT Correct.
EXTERNAL_KEYCLOAK_URL = https://keycloak.example.com/realms/myrealm IS Correct.
Readme show a bad URL example.
This PR can help users to have a better deploy without confusion.

Edit Keycloak OpenID endpoint url

---

api/external.go
api/token.go
models/user.go
models/user_test.go

An unconfirmed user account using email + password login, that is then connected to an OAuth account presents a security risk since the user logging in with OAuth does not expect for there to be a (potentially malicious) email + password combination (or unconfirmed phone number). Therefore, the password / phone is removed, the email and/or phone providers removed from the user.
Email + password combination can be used to log-in after linking with an OAuth account occurs.

fix(oauth): Remove password, phone on subsequent OAuth login

---

api/mail.go
mailer/template.go

* Adds support to generate email links for changing a user's email
* `/admin/generate_link` endpoint does not support generating email links for changing emails 
* https://github.com/supabase/supabase/discussions/5125#discussioncomment-3172735
* Addresses #365 
* Introduces 2 new types for generating email links: `email_change_current`, `email_change_new` 
```bash
curl -X POST 'http://localhost:9999/admin/generate_link' 
-H 'Authorization: Bearer token' 
-d '{
"type": "email_change_current", 
"new_email": "bar@example.com", 
"email": "foo@example.com"
}'
{
"action_link": "http://localhost:9999/verify?token=813...2f8&type=email_change&redirect_to=http://localhost:3000",
"email": "foo@example.com",
"email_change_sent_at": "2022-07-22T12:49:45.906546+08:00",
"email_confirmed_at": …
```

fix: add email_change support to generateLink

---

api/api.go
api/mfa.go
api/mfa_test.go

- Change `/recovery_codes` from GET to POST
- Allow only `factor_id` to be passed in on the `/challenge` endpoint
- update responses for  `/challenge`(remove `factor_id` and `friendly_name`) and `/verify` (remove `/challenge_id` from response)
- Remove  type from `/verify` endpoint
- Update associated tests

MFA fixes 

---

api/helpers.go
api/verify_test.go
conf/configuration.go

If a user specifies a redirect URL glob of the form:
```
https://example.com
```
But they send a `redirect_to` parameter to `/authorize` of the form:
```
https://example.com/
```
(Note the trailing slash!)
GoTrue will not match the two URLs, even though in the modern web they are equivalent. This PR normalizes HTTP(S) URLs to remove the trailing slash in the `redirect_to` parameter; as well as ignoring any trailing slashes in the URL allow list.

feat: Normalize redirection URLs and globs

---

api/admin_test.go

Remove non-determinism from 2 tests & speed up those tests.
Tests relied on sleeping to allow underlying library to set `created_at` at `time.Now()`.
Explicitly set the `CreatedAt` value.
Looks like the library won't set CreatedAt if it's already set:
```
if !IsZeroOfUnderlyingType(v) {
// Do not override already set CreatedAt
return
}
```
https://github.com/gobuffalo/pop/blob/2d0cf817d62006ebf9bec1b51ab0a066602e3e5b/model.go#L194
Which is why this works.
Being explicit like this allows for more  advanced cases too. Like, if there was a "Recently added" feature that you wanted tested, you wouldn't be able to rely on sleep.

Remove sleep from admin test

---

api/admin.go
api/api.go
api/context.go
api/mfa.go
api/mfa_test.go
api/token_test.go

Refactors MFA Routes to conform to a more REST-ful format
now, routes are of the form `/user/<user_id>/factor/<factor_id>/<action>` . Concretely, this means
And more
This is done by storing and loading factors from the context and making use of them to perform relevant operations. 

Refactor MFA Routes

---

README.md

The response from ```/admin/generate_link``` now includes additional fields (see https://github.com/supabase/gotrue/pull/537). These are added to the docs.
Docs update
https://github.com/supabase/gotrue/issues/538
https://github.com/supabase/gotrue/pull/537

Update description of /admin/generate_link response

---

models/identity.go

* Emails saved in the identities.identity_data->>'email' field should be saved as lowercase emails

fix: convert emails to lowercase before saving

---

api/helpers.go
api/verify_test.go
conf/configuration.go

Previously in #591 and #535 we introduced a change to normalize redirect URLs and match patterns, but that does not apply for the scenario:
`https://example.com/*` won't match `https://example.com/` since the slash is stripped.
If we fix this later, it will be in a new PR.

fix: Revert URL normalization (#535, #591)

---

api/api.go
api/context.go
api/saml.go
models/errors.go
models/sso.go
models/sso_test.go

Adds basic CRUD operations for managing SAML Identity Provider connections.
Tests incoming.

feat(saml): Add `/admin/saml` routes and basic implementation

---

api/mfa.go

Removing the `created_at` field as I'm guessing use mainly cares about when the challenge expires which is given by the `expires_at` field. Can reinstate if user asks, adding via PR so we can track all changes

Remove created_at field

---

api/admin.go
api/admin_test.go
api/mfa.go
api/mfa_test.go
models/factor.go

`MFAEnabled` is no longer a variable on the `User` model  that can be toggled. Rather, a user can only call special MFA methods(like delete factor, unenroll factor) when they have at least one verified factor. It is more a safeguard than anything (and partially for security) because users calling the endpoints without a verified factor would still get an actor but perhaps with a more obscure message.

Reintroduce notion of MFAEnabled

---

api/api.go
cmd/multi_cmd.go
storage/dial.go

These features inherited from [Netlify's GoTrue](https://github.com/netlify/gotrue) are not supported by Supabase and are due for removal in the next few minor releases:
- Multi-instance mode
- JWT groups
- SAML external provider

chore: Add deprecation notices for unsupported features

---

README.md

Adds information to the README on guarantees for backward compatibility especially with regards to self-hosting.

chore: Update README with backward compat. information

---

.github/workflows/release.yml
.github/workflows/test.yml
Dockerfile
Dockerfile.dev
go.mod
go.sum

We are currently requiring a minimum version of Go 1.13 for Go Modules and 1.17 in Dockerfiles. This PR bumps the go version to the next major release (1.18) 

chore: bump go version to 1.18

---

.github/workflows/publish.yml
.github/workflows/release.yml

ci/cd workflow
patch release to trigger new workflow
some duplication in release job
- publish docker image in separate workflow
- runs deploy and publish in parallel
- mirrors to public ecr

fix: mirror gotrue image to public ECR

---

api/admin_test.go
api/helpers.go
models/user.go

Supabase does not use the "system user" concept, thus it is not supported and removed from the codebase.

feat: Remove system user (deprecated)

---

README.md

We had an internal discussion and decided to only use GitHub releases and security advisories as means of notifying self-hosters.

chore: Remove Google Group from README

---

api/middleware.go

The function is not used -- probably added to populate the `GetBody` function on requests, but it's not used.

chore: Remove unused `addGetBody` middleware

---

api/helpers.go
cmd/admin_cmd.go
models/user.go

Removes the `IsSuperAdmin` field from the `User` model, as this is not used nor supported by Supabase.

feat: Remove `IsSuperAdmin`

---

api/admin.go

* Fixes the bug described in https://github.com/supabase/gotrue/issues/629 where `app_metadata` field was not being respected when a user is created via the admin endpoint

fix: admin user create should respect `app_metadata`

---

api/api.go
api/auth.go
api/context.go
api/helpers.go
api/logout.go
api/reauthenticate.go
api/user.go
models/refresh_token.go

* `requireAuthentication` middleware should handle storing the user and session in the request context since the user is always needed downstream
* `/logout` should maintain backward compatibility for access_tokens that do not have a `session_id` claim in them and delete all the refresh tokens associated to a user
* `/logout` should delete all sessions associated to a user if the `session_id` claim exists in the access_token. Since the delete is cascaded, the refresh_tokens associated to each session will also be deleted
* replace `getUserFromClaims` and `getSessionFromClaims` with `maybeLoadUserOrSession`

refactor: requireAuthentication should store user and session in context

---

api/admin_test.go
api/auth.go
api/middleware.go
api/middleware_test.go

* Allows a user to skip captcha validation if an admin JWT is present in the header
* Allows one to bypass captcha validation on a trusted client (e.g. supabase's user management dashboard)
* Add test for bypassing captcha with admin jwt

fix: skip capcha if admin jwt in header 

---

SECURITY.md

Adds Supabase's [security.txt](https://supabase.com/.well-known/security.txt) policy so that it shows up in the [GitHub Security Policy](https://github.com/supabase/gotrue/security) page.

chore: Add `SECURITY.md` with Supabase's security.txt policy

---

api/admin.go
api/helpers.go
api/invite.go
api/mail.go
api/otp.go
api/recover.go
api/signup.go
api/token.go
api/user.go
api/verify.go

Fixes access to a request's `Body` via a common helper function `getBodyBytes(req)` which handles proper closing and re-setting of `req.Body`.

fix: Access to `req.Body` via `getBodyBytes`

---

api/api.go

Removes the deprecation notice since it was mistakenly added. Self-hosters can use the property to specify which roles serve the "admin" function.

fix: Remove deprecation notice for admin roles

---

.github/workflows/test.yml
Makefile
api/api.go
api/hooks.go
api/middleware.go
api/provider/notion.go
api/provider/twitch.go
security/hcaptcha.go

Fixes some remaining `G104: Audit errors not checked` errors in the main codebase. The tests codebase has a ton of these, which should be OK when used in tests, so keeping G104 excluded there.

fix: Add full `gosec` support (w/o tests)

---

.github/workflows/test.yml
Makefile
api/context.go
api/helpers.go
api/helpers_test.go
api/hook_test.go
mailer/mailer.go
mailer/mailer_test.go

Moves code used only in `_test.go` files, into such files, so they don't pollute the main binary.
Depends on: #637.

style: move test-only code under _test files

---

api/mfa.go
conf/configuration.go
migrations/20220811173540_add_sessions_table.up.sql
models/challenge.go
models/sessions.go

Adds `factor_id` and `amr_claims` to session. Also adds fixes suggested  by @kangmingtay.
Briefly, the changes are:
1. Remove MFA Enabled. Looks like I  actually didn't remove `MFA_Enabled`  -- this can be reintroduced in V2 since there's no need to explicitly enable.
2.  Move TOTP validation logic to be before the check for challenge expiry
3. Catches errors when saving factors
Error in saving factors/Challenges should show up
Random: Looks like someone filed a PR for [Global `split_words`](https://github.com/kelseyhightower/envconfig/pull/191) on envconfig. Don't think it's getting merged anytime soon though

Add MFA Sessions Fields

---

.github/CODEOWNERS

Inherited from Netlify, also the reason why code owners are not showing up in new PRs.

style: remove old `.github/CODEOWNERS`

---

logger/log.go
security/hcaptcha.go
utilities/request.go
utilities/request_test.go

Uses the [`X-Forwarded-For`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) header to determine the proper origin of the HTTP request. Comes out of #582.

feat: use proper ip address

---

api/token.go
api/token_test.go
models/refresh_token.go
models/refresh_token_test.go
models/user_test.go

Useful for parametrizing the issuing of refresh tokens. Both MFA and SAML branches need a concept like this.

refactor: add `GrantParams` for issuing refresh tokens

---

api/external.go
api/external_oauth.go

* Retrieves the `ProviderRefreshToken` from the provider's OAuth response
* Pass the `ProviderRefreshToken` as `provider_refresh_token` in the query fragments when redirecting to SITE_URL
Currently the provider's refresh token is completely ignored and never passed to the client.
The provider's refresh token is now passed, **when it exists**, to the client as `provider_refresh_token` along the `provider_token`.
This feature should be backwards compatible, for a more coherent approach it could be possible to rename the current `provider_token` to `provider_access_token` but it would probably break current integrations.
Some of the OAuth providers have an expiry date on the access token they provide (e.g: Twitch). By passing the provider refresh token it allows developers to renew the …

feat: Add provider_refresh_token query fragment

---

models/connection.go

`DELETE` is faster than `TRUNCATE` when running the tests.

fix: use `delete` instead of `truncate` for fast tests

---

api/magic_link.go
api/otp.go
api/otp_test.go

Renames the OTP param from Metadata to Data to be consistent with the `/signup` route.
TODOs:

refactor: params.Metadata -> params.Data

---

.github/workflows/release.yml

For some reason the existing workflows are not running one after the other. This will allow us to manually dispatch a release on the `zerosessionidfix` branch.

ci: add temp. manual run for release workflow

---

api/audit_test.go
api/invite_test.go
api/phone_test.go
api/token.go
api/user_test.go
api/verify_test.go
models/refresh_token.go

* This changes the `SessionID` struct field to use a `*uuid.UUID` instead of `nulls.UUID`

refactor: use uuid ptr instead of nulls.UUID

---

api/audit_test.go
api/auth.go
api/auth_test.go
api/context.go
api/invite_test.go
api/middleware.go
api/phone_test.go
api/token.go
api/user_test.go
api/verify_test.go
models/refresh_token.go

* omit `session_id` from access token jwt if `session_id` is `uuid.Nil` 
* `createRefreshToken` should create a new session if one doesn't exist (`uuid.Nil`)
* `maybeLoadUserOrSession` should skip reading `session_id` from claim if it's a `uuid.Nil`
* Add tests for auth middleware functions

fix: handle null session id

---

models/errors.go

In the codebase today none of these errors are passed as pointers, but I can see how easily a mistake can be made where a pointer is passed.

refactor: add pointer type checks in `IsNotFoundError`

---

api/external.go
api/signup.go
api/token.go
api/verify.go

Passes an empty `models.GrantParams` object to `issueRefreshToken` as this is going to be used by SAML / MFA.

refactor: pass `GrantParams` object to `issueRefreshToken`

---

.github/workflows/release.yml
.github/workflows/test.yml
.releaserc

We will be using the `mfa_v1` branch instead of the `mfa` branch. The `mfa_v1` only contains the vanilla enroll and verify flow and does not include recovery codes

ci: add release for mfa_v1

---

api/hook_test.go
api/magic_link.go
api/middleware_test.go
api/provider/notion.go
api/provider/provider.go
api/provider/twitch.go
api/provider/twitter.go
api/signup_test.go
api/token.go
api/verify.go
api/verify_test.go
security/hcaptcha.go

Patched some static check errors which came up while editing another branch.
We are now on Go 1.18  which is past Go 1.16 in which [`io/ioutil` has been deprecated](https://go.dev/doc/go1.16#ioutil)  -- the recommendation is that users use `io` instead. As such, this PR aims to patch this as per static check errors that were showing up.
Also took the recommendation to user `errFoo` instead of `redirectWithQueryError` and adjusted the error name accordingly.

refactor: deprecate io/ioutil in favour of io

---

CONTRIBUTING.md
Dockerfile.postgres.dev
README.md
cmd/migrate_cmd.go
conf/configuration.go
docker-compose-dev.yml
init_postgres.sh
migrations/00_init_auth_schema.up.sql
migrations/20210710035447_alter_users.up.sql
migrations/20210722035447_adds_confirmed_at.up.sql
migrations/20210730183235_add_email_change_confirmed.up.sql
migrations/20210909172000_create_identities_table.up.sql
migrations/20210927181326_add_refresh_token_parent.up.sql
migrations/20211124214934_update_auth_functions.up.sql
migrations/20211202183645_update_auth_uid.up.sql
migrations/20220114185340_add_banned_until.up.sql
migrations/20220224000811_update_auth_functions.up.sql
migrations/20220323170000_add_user_reauthentication.up.sql
migrations/20220429102000_add_unique_idx.up.sql
migrations/20220531120530_add_auth_jwt_function.up.sql
migrations/20220614074223_add_ip_address_to_audit_log.postgres.up.sql
migrations/20220811173540_add_sessions_table.up.sql

* Supersedes #553 without relying on postgres search path, fixes #185
* This change allows us to move away from hardcoding the auth schema prefix in the migrations and instead defer to use the `NAMESPACE` env var
* Since pop allows for go template strings in `.sql` files when running migrations, we can use `{{ index .Options "Namespace" }}` to specify the schema name in the migration file

refactor: remove auth schema prefix

---

api/errors.go
api/mfa.go
models/refresh_token.go
models/sessions.go

* Return token in mfa verify
* Update session `aal` from `aal1` to `aal2` on successful verify

fix: return token in mfa verify & update session aal

---

mailer/mailer.go
mailer/template.go

`mailer` had unnecessary calls to `conf.LoadGlobal('')` which were re-parsing the environment config on every request. This PR removes those calls, as the global config is already present.
Part of #679.

refactor: remove LoadGlobal calls from mailer

---

cmd/migrate_cmd.go
cmd/root_cmd.go
conf/configuration.go
conf/logging.go
conf/tracing.go
observability/logging.go
observability/tracing.go

Splits the configuration and enablement of observability settings such as tracing and logging. A tracer, metrics collector or logger should only be configured once per process. This also allows for future additions of OpenTelemetry metrics and tracing.
Part of #679.

refactor: split observability config and enablement

---

api/sms_provider/sms_provider.go
api/sms_provider/sms_provider_test.go
api/sms_provider/textlocal.go
api/sms_provider/twilio.go
go.mod
go.sum

* ~Introduce a custom `HttpClient` interface which can be overridden in tests.~ 
* ~For tests in `sms_provider`, we can overwrite the native `http.Client` with a `MockHttpClient` and define the expected API behaviour from the 3rd-party sms providers with `handleApiRequest`.~
* Used [gock](https://github.com/h2non/gock) for mocking external API requests instead

fix: add test for all sms providers

---

api/admin.go
api/audit.go
api/auth.go
api/external.go
api/invite.go
api/logout.go
api/magic_link.go
api/mail.go
api/otp.go
api/reauthenticate.go
api/recover.go
api/signup.go
api/token.go
api/user.go
api/verify.go
storage/dial.go

Passes the request's context down to the database queries so that tracing and correlation can work.
Part of #679.

refactor: pass request context to database queries

---

api/admin.go
api/api.go
api/errors.go
api/external.go
api/external_oauth.go
api/user.go
api/verify.go
models/audit_log_entry.go
observability/request-logger.go

Today the structured logger for the API lives under the `api` package, but it's place is better suited under the `observability` package as logs can be correlated to traces and metrics easily.
Part of #679.

refactor: move request structured logger to o11y

---

Makefile

Newer Go versions are getting confused by the `github.com/netlify/gotrue` package (since git says this repo has an origin at `github.com/supabase/gotrue`) and fails with the following error:
```
gotrue           | go build -ldflags "-X github.com/netlify/gotrue/utilities.Version=`git describe --tags`"
gotrue           | fatal: detected dubious ownership in repository at '/go/src/github.com/netlify/gotrue'
gotrue           | To add an exception for this directory, call:
gotrue           |
gotrue           | 	git config --global --add safe.directory /go/src/github.com/netlify/gotrue
gotrue           | error obtaining VCS status: exit status 128
gotrue           | 	Use -buildvcs=false to disable VCS stamping.```
Until we change the package, this should stop the error from appearing.

tools: add `-buildvcs=false` to makefile

---

api/mfa.go
models/factor.go

* fix static check errors
* a serialised factor should not contain the associated user and user_id, the friendly name should also be omitted if it is empty

fix: minor mfa changes

---

api/api.go
api/cleanup.go
api/listener.go
cmd/root_cmd.go
cmd/serve_cmd.go
conf/configuration.go
main.go
observability/cleanup.go

Refactors signal handling (i.e. `Ctrl-C` behavior) using a top level context using `signal.NotifyContext`. This context is propagated down to the API server, which will shut down cleanly when it gets cancelled.
Furthermore, adds clean up functions for any additional servers that were started but not waited upon -- specifically in `api` and `observability`.
Part of #679.

refactor: signal handling with cleanup

---

.github/workflows/docs.yml
api/admin.go
api/api.go
api/mail.go
docs/admin.go
docs/doc.go
docs/errors.go
docs/health.go
docs/invite.go
docs/logout.go
docs/oauth.go
docs/otp.go
docs/recover.go
docs/settings.go
docs/signup.go
docs/token.go
docs/user.go
docs/verify.go
main.go
swagger.json

* Supersedes #230  
* Adds swagger spec for gotrue's API
* Had to change the response data structure from a `map[string]interface{}` to a proper struct for some endpoint so they can be reused in `/docs` 
```
$ git clone https://github.com/go-swagger/go-swagger && cd go-swagger
$ git checkout v0.30.0
$ go install -ldflags "-X github.com/go-swagger/go-swagger/cmd/swagger/commands.Version=$(git describe --tags) -X github.com/go-swagger/go-swagger/cmd/swagger/commands.Commit=$(git rev-parse HEAD)" ./cmd/swagger
$ swagger generate spec -o ./swagger.json
$ swagger serve -F=swagger swagger.json
```

fix: add swagger docs

---

api/api.go
api/mfa.go
conf/configuration.go

Introduces tollbooth rate limiters as in PR
Exact values  are up for discussion. Decided not to slap hcaptcha on as captcha is already deployed on the 1FA routes
No rate limiters

Add Rate limiters for MFA

---

api/helpers.go
api/verify_test.go

GoTrue limited wildcard redirect patterns only on `http` or `https` URLs. This presents a problem in mobile apps that have dynamic redirects back to their application.
See: #710.

fix: allow all URL forms in redirects

---

Makefile
api/middleware.go

Rate limiting was applied to all users if the rate limit header value was not present in the request.

fix: skip rate limit if header not present

---

api/signup.go

Some developers attach triggers to the `users` table where they add custom columns or other data upon the creation of a new user. This data was not visible in the response from the sign up API call.
This PR loads the user again after the initial sign-up to pull the latest data from the database.
See: #288

fix: load user after sign-up to pull data from triggers

---

api/admin.go
api/invite.go
api/magic_link.go
api/mail.go
api/otp.go
api/recover.go
api/signup.go
api/user.go
api/verify.go

* Fixes https://github.com/supabase/gotrue-js/issues/435 because the `POST /verify` takes in the email in the request and hashes it without making it case-insensitive first
* Lowercase all emails passed through the `validateEmail` function

fix: lowercase emails for verify otp

---

Makefile

I think I accidentally committed this in a previous PR, which breaks `./gotrue` running on Mac.

ci: remove forgotten `GOOS=linux` in `make build`

---

api/mfa_test.go

Add reused variables to `ts`  in `mfa_test`  so they can be reused across tests.

refactor: add mfa test refactor

---

api/admin.go
api/admin_test.go
api/api.go
api/mfa.go
api/mfa_test.go
models/connection.go
models/factor.go
models/factor_test.go

- EnrollFactorResponse TOTP to have json:"TOTP,omitempty"
- DefaultQRSize to be moved to top of file
- Use url.ParseRequestURI instead of url.Parse
- Add the new tables in TruncateAll.
- Rate limiters for challenge and verify scoped to minute
- adminUserUpdateFactor now behind PUT instead of Post

refactor: MFA Refactors

---

api/admin.go
api/admin_test.go
api/mfa.go
models/factor.go

- Across all files, use getBodyBytes instead of r.Body and json.Unmarshal instead of a decoder.
- Documentation comments should start with the function name. Example: // IsMFAEnabled returns whethe
- Admin users can no longer update factor status

refactor: update factors.go and getBodyBytes 

---

api/mfa.go
api/mfa_test.go
api/token.go
models/sessions.go
models/sessions_test.go

We now trigger a refreshToken swap on successful verification of a TOTP token.
We now trigger a refreshToken swap on successful verification of a TOTP token.
As @kangmingtay pointed out, the following series of events could lead to a race condition resulting into a state refresh token being sent back:
1. Sign-in
2. Enroll MFA
3. Verify Enrollment
4. Automatic refresh of access token
When Steps 4 happens during / after the transaction in step 3 completes GoTrue returns an old refresh Token
Nil

fix: trigger token swap on MFA verify to ensure token is latest one

---

api/admin_test.go
api/api.go
api/audit_test.go
api/auth_test.go
api/external.go
api/invite_test.go
api/logout_test.go
api/mfa_test.go
api/phone_test.go
api/signup.go
api/signup_test.go
api/token.go
api/user_test.go
api/verify.go
api/verify_test.go
conf/configuration.go
models/factor_test.go
models/refresh_token.go
models/sessions.go
models/sessions_test.go
models/user.go

Add  a feature flag `MFA_ENABLED` which gates all MFA related tests, routes, and breaking changes.
We prefix the `MFA_` prefix for all breaking MFA changes and make use of the version without the prefix when the flag is toggled to off
`sessions_test.go` and `mfa_test.go` have not been flagged as they contain only MFA related functions and default to the `MFA_` functions. They are not run when the flag is set to false

chore: add feature flag

---

migrations/20221004041400_add_index_on_refresh_token.up.sql
migrations/20221011041400_add_mfa_indexes.up.sql
models/amr.go

Introduces indexes for mfa to target the following queries:
```
func FindFactorsByUser(tx *storage.Connection, user *User) ([]*Factor, error) {
factors := []*Factor{}
if err := tx.Q().Where("user_id = ?", user.ID).Order("created_at asc").All(&factors); err != nil {
if errors.Cause(err) == sql.ErrNoRows {
return factors, nil
}
return nil, errors.Wrap(err, "Database error when finding MFA factors associated to user")
}
return factors, nil
}
```
Find Token by Session
```
func FindTokenBySessionID(tx *storage.Connection, sessionId *uuid.UUID) (*RefreshToken, error) {
refreshToken := &RefreshToken{}
err := tx.Q().Where("session_id = ?", sessionId).Order("created_at asc").First(refreshToken)
if err != nil {
if errors.Cause(err) == sql.ErrNoRows {
return nil, RefreshTokenNotFoundError{}
}
return …
```

feat: add mfa indexes

---

api/admin.go

Updating a user on the admin endpoint did not perform email address or phone number validation.

fix: add validation to admin update user

---

api/auth.go
api/auth_test.go

* Previously, the middleware would return 500s for JWTs with invalid subject / invalid claims. We should be returning 401s instead.

fix: return unauthorized error for invalid jwt

---

api/settings.go
api/settings_test.go

* Return the `MFA_ENABLED` config in `/settings`

fix: return mfa enabled in settings

---

api/api.go
api/mfa.go
api/mfa_test.go

Use a plural version of `/factors`, lowercase `totp` response on enrollment.

refactor: pluralize factors endpoint, use lowercase `totp`

---

api/admin_test.go
api/mfa.go
api/mfa_test.go
models/factor_test.go

Add a few sanity checks on `mfa_test.go` and  `admin_test.go` to ensure secret is not leaked
Also change the status codes for unenroll from `unauthorised` to `bad request` if user doesn't have AAL2 JWT

test: add sanity checks to ensure secret does not leak

---

api/token.go

Every other supported provider used provided client ID that could be modified and set via the Supabase studio/dashboard but the Apple login was the only one that used a separate `config.External.IosBundleId` that comes from a config file and can't be set in the dashboard.
To fix this, we first try and read the value provided by the config and then try to fallback onto using client IDs, just like it's done for the remaining providers.
cc @kangmingtay who implemented the initial `id_token` grant flow
This should address the error seen by @k0shk0sh in https://github.com/supabase/gotrue/issues/412#issuecomment-1114193213 (happened to me, this PR is an attempt to fix that).
Fixes a bug/omission introduced in https://github.com/supabase/gotrue/pull/189
The user can use the `id_token` grant …

Fix mobile/native Apple login in the `id_token` grant flow for hosted instances

---

api/external.go
api/external_oauth.go
api/provider/workos.go

* Fixes [issue](https://github.com/supabase/gotrue-js/issues/131#issuecomment-1277378031) where some providers require passing an explicit query param (e.g. `access_type=offline`) before returning the provider refresh token 
* Refactored workos provider since this solution is generic enough to be used across all other oauth providers

fix: allow any oauth providers to pass query params

---

migrations/20221020193600_add_sessions_user_id_index.up.sql

Indexes, they get you every time.
It was forgotten and in cases where there are many users x sessions the database can spend many cycles trying to delete sessions on logout.

fix: add missing index on `user_id` under `sessions`

---

migrations/20221021073300_add_refresh_tokens_session_id_revoked_index.up.sql
models/refresh_token.go

Certain long-lived user sessions will have a large number of refresh tokens. Each new subsequent refresh token action scans this large set of rows and updates all to be revoked. This change adds an index for the operation, and also limits the number of affected rows by forcing the query to update only non-revoked tokens.

fix: add index on `(session_id, revoked)` in `refresh_tokens`

---

api/magic_link.go

* Fixes https://github.com/supabase/gotrue/issues/699#issuecomment-1286382275
* The `data` param will only be passed on the first magiclink sent (which is a signup action). Subsequent magiclink requests for the same user will not trigger any updates to the user metadata

fix: rename metadata to data

---

migrations/20221021082433_add_saml.up.sql

Adds migrations that add all of the necessary entities. Changes from the POC implementation:
- `sso_providers` includes a `resource_id` optional column that will allow providers have user-generated unique IDs that can be used in cases like a Terraform provider.
- `sso_domains` has a lowercase unique index on `domain`.
- `saml_relay_states` uses the `inet` type for the IP address.
- `sso_sessions` references back to `sessions` instead of being its own thing.

feat(saml): add SSO/SAML migrations

---

api/api.go
observability/metrics.go
observability/request-tracing.go

Metrics were not collected if only the metrics exporter was enabled. This is now rectified.
It also counts HTTP status codes per route, so that misbehaving routes can be easily identified. Example:
```prometheus
http_status_codes{code="400",gotrue_version="",http_route="/authorize"} 1
http_status_codes{code="405",gotrue_version="",http_route="/*"} 1
```
Finally, it adds a gauge metric to count all running versions:
```prometheus
gotrue_running{gotrue_version=""} 1
```

fix: add improved HTTP metrics

---

api/mail.go

* when using `generateLink` with type `signup` / `invite`, the `generateLink` method should handle creating an identity for the `email` provider

fix: generateLink should create identity for invite & signup

---

migrations/20221021082433_add_saml.up.sql

Uses the `{{ index .Options "Namespace" }}` template string instead of `auth` as a schema in the SAML migration.

refactor: use template schema in SAML migration

---

api/external.go
api/token.go
api/verify.go

Extracts the redirect URL encoding logic as a method on `AccessTokenResponse` so it can be reused easily.

refactor: extract `AccessTokenResponse` encoding as URL to method

---

api/external.go

`createNewIdentity` started a new transaction instead of using the one that is passed to it. Starting a transaction within a transaction can cause deadlocks.

fix: `createNewIdentity` uses provided transaction

---

migrations/20221027105023_add_identities_user_id_idx.up.sql

[Foreign keys don't create indexes by default.](https://stackoverflow.com/questions/970562/postgres-and-indexes-on-foreign-keys-and-primary-keys)

fix: add index on `identities.user_id`

---

api/mfa.go
api/mfa_test.go
models/amr.go
models/sessions.go
models/sessions_test.go

There was a brief incident last week where users with pre-MFA sessions would run into errors when attempting to sign in. This was because past sessions would have an empty `AAL` claims  field(thus null) while the Sessions model was expecting a string. This resulted in an error as a null was being coerced into a string.
Both models use `string`
We modify both the AAL and AMR fields to accept `*string` in case there are future instances which have null values for some reason
How this was tested:
1. Revert to `85cff37bac7fdd22a87235890caca7d6ace6c244` (pre-MFA)
2. Create a few sessions by making a few signups, check DB to ensure they have null field
3. Pull to come back to the current version and apply existing migrations.
4. Attempt to sign up, sign in, get user, and then make a full …

fix: convert `string` -> `*string` for AAL and AMR

---

api/api.go
api/context.go
api/sso.go
api/sso_test.go
models/connection.go
models/errors.go
models/sso.go
models/sso_test.go

Adds SSO/SAML admin endpoints, which are disabled by default.
Differences from the SAML POC:
- Routes are RESTful under `/admin/sso/providers`.
- Extensive test suite that covers a minimum of 70% of all new code.
A few more test cases need to be added in follow up PRs, and the OpenAPI specs to be updated.

feat(saml): add SSO/SAML admin endpoints (disabled by default)

---

api/api.go
api/samlacs.go
api/samlassertion.go
api/samlassertion_test.go
conf/saml.go
models/factor.go
models/sso.go

Adds the SAML Assertion Consumer Service handler. Only IdP initiated flows can be tested on this PR.
Tests are missing for the ACS endpoint as this requires a bit more time to be invested and will be added in a follow up PR. At this time you can test using samltest.id.
Things that will be done as part of follow up PRs:
- Creating uniqueness domains, i.e. treating SSO accounts as separate from other social login accounts.
- Obeying SAML session duration.

feat(saml): add SAML ACS handler (disabled by default)

---

api/api.go
api/middleware.go

Rate limiting was not getting applied because the shared email+phone limiter for OTP only rate limited when the request body contained an `email` attribute; which is not the case with SMS OTP.

fix: rate limiting not applied on phone OTP

---

api/helpers.go
api/middleware.go
api/middleware_test.go
conf/configuration.go
security/hcaptcha.go
utilities/request.go

Previously the code was quite messy and was not easy to determine why hCaptcha protection was failing. This PR attempts to simplify the logic and provide clear error messages.

fix: use clear hCaptcha error messages

---

api/api_test.go
crypto/password.go
models/user.go
models/user_test.go

Refactors the password hashing code to live in a central place under `crypto` and adds metrics that count the number of submitted and completed password hashing attempts. These metrics can be useful to determine whether GoTrue is under a password stuffing attack (where submitted will rise drastically over completed or not-matched will rise drastically over matched). Example:
```prometheus
gotrue_compare_hash_and_password_completed{alg="bcrypt",bcrypt_cost="10",gotrue_version="",match="false"} 4
gotrue_compare_hash_and_password_completed{alg="bcrypt",bcrypt_cost="10",gotrue_version="",match="true"} 3
gotrue_compare_hash_and_password_submitted{alg="bcrypt",bcrypt_cost="10",gotrue_version=""} 7
gotrue_generate_from_password_completed{alg="bcrypt",bcrypt_cost="10",gotrue_version=""} 1 …
```

feat: add password hashing metrics

---

mailer/template.go

Magic links often need to be customized. This PR allows folks to customize the link by providing access to the `HashedToken`.

refactor: add access to token used for magic-link generation

---

api/recover.go
api/recover_test.go
api/verify_test.go
models/audit_log_entry.go

* No longer allow password resets for user's without an email identity.
* Previously, it was possible to request for a password reset if you have an oauth identity. This is because the oauth identity is always guaranteed to have an email and the password reset would be allowed. This means that the user will now be able to login with email + password if the reset was successful even though no email identity is created for them. The password reset acts as a backdoor access to the user's account in the event the user loses access to their oauth account. However, the user should attempt to regain their access to the account by liaising with the oauth provider rather than initiate a password recovery to gain access to the account.

feat: no email password resets for users with no email identity

---

api/api.go

Having CAPTCHA on `POST /verify` means that developers need to ask users to solve a captcha twice: one when the email / SMS is sent, and once again when the code is being verified.
Given that `GET` request already does not require CAPTCHA, and that there is a rate limiter including OTP expiration logic, it is not possible to brute-force verifications.
PR in gotrue-js: https://github.com/supabase/gotrue-js/pull/532

fix: skip captcha on `POST /verify`

---

api/sso_test.go
api/ssoadmin.go
models/sso.go

Attribute mapping persistence was forgotten. This adds it on provider creation and update.

fix(saml): persist attribute mappings on provider create and update

---

CONTRIBUTING.md
Dockerfile.postgres.dev
hack/postgresd.sh

Bump Postgres version to 14
postgres 13
postgres 14
strings replaced via `rg "postgres:13" --files-with-matches | xargs sed -i "" "s/postgres:13/postgres:14/g" `

chore: bump postgres version from 13 to 14

---

api/user.go
api/user_test.go
models/audit_log_entry.go
models/sessions.go

* Previously, updating a password would allow other sessions to remain logged in. However, this change fixes that by ensuring that all other sessions are forcefully logged out upon a password update

fix: update password should logout all other sessions

---

migrations/20221114143410_remove_parent_foreign_key_refresh_tokens.up.sql

Removing the foreign key constraint as it's causing some issues when deletes cascade. PotgreSQL is having trouble deleting refresh tokens with parents since it has to recursively keep track.

fix: remove foreign key constraint on `refresh_tokens`.`parent`

---

migrations/20221114143122_add_session_not_after_column.up.sql
models/sessions.go

Prepares the database for the introduction of expiring sessions (as first used by SAML).

feat(saml): add `not_after` column to `sessions` table (not used)

---

models/refresh_token.go

* Fixes problem where attempting to dereference a `nil` will lead to a panic causing a deadlock in postgres because gotrue panics and the transaction is left idle

fix: resolve nil pointer dereference issue

---

api/auth.go
api/auth_test.go
api/mfa_test.go
api/middleware.go

* This PR fixes the issue where the cookies are not being cleared if an invalid user's JWT is supplied on logout.

fix: logout cookies not cleared

---

api/hook_test.go
api/signup.go

Subsequent unconfirmed user signups allow modifying the originally passed user metadata without confirming that the password is correct. Given that this endpoint is meant to be used only once, no subsequent editing of the user metadata should be allowed.
This can be achieved by calling the user update endpoint while authenticated.

fix: don't update user metadata on subsequent signups

---

api/auth.go
api/auth_test.go
api/mfa_test.go
api/samlacs.go
api/token.go
api/token_test.go
models/refresh_token.go
models/refresh_token_test.go
models/sessions.go
models/sessions_test.go
models/user.go
models/user_test.go

The SAML ACS endpoint will create sessions with a "not after" timestamp. Refresh tokens won't be refreshable past this timestamp.

feat(saml): add session expiration (not after timestamp) support (disabled by default)

---

migrations/20221003041349_add_mfa_schema.up.sql
migrations/20221011041400_add_mfa_indexes.up.sql

Noticed while doing support that `amr_id_pk` does not need currently check if the index already exists. As such, if the migration is re-run it will lead to an error.
See Internal support ticket

fix: make add_mfa_indexes re-runnable

---

migrations/20221125140132_backfill_email_identity.up.sql

* This migration is responsible for backfilling all email-password or email-passwordless based users that don't have a corresponding email identity.
* The `created_at` and `updated_at` timestamps are deliberately hard-coded so we can roll back the migration by deleting those identities easily

fix: add migration to backfill email identities

---

api/admin.go
api/mail.go
api/signup.go
api/user.go
cmd/admin_cmd.go
migrations/20221125141029_add_identities_email_column.up.sql
models/identity.go
models/user.go
models/user_test.go

Modifies the `IsDuplicateEmail` method to use email addresses within the `identities` table and not the primary user email address in `users`. 
It now also returns the duplicate user it found, so that it can be reused in signup and update user.

feat: modify email duplicate lookup to use `identities`

---

api/admin.go
api/external.go
api/external_test.go
api/mail.go
api/samlacs.go
api/signup.go
api/user.go
cmd/admin_cmd.go
migrations/20221120114718_add_identities_email_column.up.sql
migrations/20221124140122_add_identities_email_column.up.sql
models/identity.go
models/linking.go
models/linking_test.go
models/user.go
models/user_test.go

Uses the account linking algorithm described in #792 for linking accounts via external identities. This change produces equivalent results as the previous algorithm, while also supporting the SSO case.
(Depends on #826.)

feat: use account linking algorithm

---

api/external.go
api/invite.go
api/mail.go
api/mfa.go
api/samlacs.go
api/signup.go
api/token.go
api/user.go
migrations/20221121110412_modify_users_email_unique_index.up.sql
models/user.go

Adds a new `duplicated_emails` boolean column on `auth.users`. This column in combination with a partial unique index will allow rows in the table to contain duplicate emails.
This is a somewhat temporary measure that ensures database consistency until full programmatic support is available for account merging / linking / delinking through APIs and hooks. 
Cases such as SAML, which do not obey the email-similarity account linking rule, may create distinct user accounts that may have the same email address. In fact, this is the only time the `duplicated_emails` column is set to `true`.

feat: add `is_sso_user` column to `users` which allows duplicate emails to exist on those rows

---

api/token.go
models/identity.go
models/identity_test.go
models/sessions.go
models/sessions_test.go

When the authentication method reference ends with (i.e. the initial authentication method is) `sso/saml`, an additional sub-claim `provider` is added that contains the UUID of the SSO provider that originated the authentication. This is extracted from the single row under the `identities` table.

feat: add `provider` claim to `amr` when the method is `sso/saml`

---

api/saml.go

GSuite obeys the authentication request NameID instead of the configured one. Example request from GoTrue:
```xml
<samlp:AuthnRequest
xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
ID="id-cf0bf40db81ac47473667730e20ae70bc87fccc1"
Version="2.0" IssueInstant="2022-11-30T19:27:37.755Z"
Destination="https://accounts.google.com/o/saml2/idp?idpid=CXXXXXXXXXX"
AssertionConsumerServiceURL="https://alt.supabase.green/auth/v1/sso/saml/acs"
ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST">
<saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">
https://alt.supabase.green/auth/v1/sso/saml/metadata
</saml:Issuer>
<samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" AllowCreate="true"/> …
```

fix(saml): always request persistent NameID in authn requests

---

api/samlassertion.go

The wrong `NotOnOrAfter` was being used. The correct one is found in one of the AuthnStatements, instead of the Conditions.

fix(saml): use `SessionNotOnOrAfter` from the authn. statement instead of conditions

---

api/external.go
api/invite.go
api/mail.go
api/signup.go
api/token.go

Due to a merge conflict in the previous PRs, SAML accounts were not assigned `is_sso_user` correctly.

fix(saml): saml user accounts not being set as `is_sso_user`

---

.github/workflows/mirror.yml

followup #844 
nodejs 12 outdated warning https://github.com/supabase/gotrue/actions/runs/3599385295

chore: bump mirror action version

---

api/external_linkedin_test.go
api/provider/linkedin.go
models/linking.go

* This PR fixes the issue with a linkedin user not being able to sign-in if they don't have an avatar url.
* Fixes: https://github.com/supabase/gotrue-js/issues/488

fix: linkedin provider issue with missing avatar url

---

.github/workflows/release.yml
.releaserc
migrations/20221208132122_backfill_email_last_sign_in_at.up.sql

With the email identities backfill migration, new `email` identities were created where `last_sign_in_at` was set to null. Even though the database allows this, the types in gotrue-js do not, which crashes strongly-typed derivations of the library like Flutter projects.

fix: fill `last_sign_in_at` with a non-null value on backfilled email identities

---

api/middleware.go
api/middleware_test.go
conf/configuration.go

* Separate the email and sms rate limits by introducing a new env var `GOTRUE_RATE_LIMIT_SMS_SENT`
* This env var controls the global limit on the total number of sms-es that can be sent per hour. It is a global rate limit that defaults to 30 sms-es per hour

fix: add separate config for sms rate limits

---

api/verify.go
models/user.go

* Only update `auth.identities.identity_data` if `auth.identities.identity_data["email"]` exists

fix: verify email change

---

migrations/20221215195500_modify_users_email_unique_index.up.sql

Migration was adding a comment on the wrong index. Because we reordered the migrations this code runs again, but at this time there's no such index so the comment can't be applied.

fix: use proper index name in `20221215195500_modify_users_email_unique_index`

---

Dockerfile

see title. Latest version of alpine is [3:17](https://hub.docker.com/_/alpine)

chore: bump alpine in Dockerfile to 3.17

---

api/external.go
api/verify.go

* For endpoints which redirect the request on an error, if the error is an internal server error, the internal message isn't getting logged properly. This change helps to fix that.

fix: handle error properly for redirects

---

api/verify.go
api/verify_test.go

* Adds a new verification type for email OTPs called `email`. Currently, it's impossible to tell whether the verification type should be set to "signup" or "magiclink" when a user enters an OTP. As such, developers have to resort to trying `magiclink` first, then catching the error and trying with `signup` next. 
* Deprecate `signup`, `magiclink` types for `POST /verify` 
* Also remove references to the v1 OTP format since it's no longer used and any existing v1 OTPs should have expired by now.
Example request:
```bash
curl -X POST 'http://localhost:9999/verify' -H 'Content-Type: application/json' -d '{"email": "foo@example.com", "token": "123456", "type": "email"}'
```

fix: add `email` as verification type for email OTPs

---

api/admin.go
api/admin_test.go
models/identity_test.go
models/user.go

* Clear token fields on soft-deletion as well
* Update `obfuscateFieldsForSoftDelete` to only obfuscate fields that originally contained values 
* Refactor admin soft delete endpoint
* Add tests

fix: update soft deletion

---

api/external.go
api/invite.go

* Previously, inviting a user won't lead to an identity being created. This creates a bug when the following steps are executed:
1. Invite a new user
2. Accept the invite via email
3. Try to sign-in with an oauth provider (i.e google) with the same email used in (1)
This leads to an error saving the user in (3) because `DetermineAccountLinking` will not be able to find any similar identities  as shown in: https://github.com/supabase/gotrue/blob/65817282f2ed05bae19b57f85d4c09cf20b7780c/models/linking.go#L73-L79 Thus, this returns the decision to create a new account. However, attempting to create a new user will result in a unique constraint violation since a user with that email already exists.

fix: create identity for invited user

---

api/api.go

feat: remove unused API `NewAPIFromConfigFile`

---

api/settings_test.go
api/token.go

- Removes `MFA_Enabled` flag references since MFA is enabled by default on all projects and we no longer use it

chore: remove MFA_ENABLED references

---

api/mail.go

* Fixes #897 
* Previously, the `u.EmailChange` field would be empty and we'd be hashing an empty string together with the OTP. This results in `verifyOtp` failing since it expects the token hash value to be `hash(emailChange+OTP)` instead of `hash(""+OTP)`

fix: set emailChange to email

---

migrations/20230125174531_backfill_invite_identities.up.sql
migrations/20230131181311_backfill_invite_identities.up.sql

* With #895, invited users will now have an email identity created upon invite. However, previously invited users will need to be reinvited again for this change to persist. This migration to backfill the `auth.identities` table helps to ensure that previously invited users won't have to be reinvited again.

fix: backfill email identities for invited users

---

.github/workflows/test.yml

see title
- need to check that we do indeed use 22.04 in prod

chore: bump postgres to 15  and ubuntu version to 22.04 in test

---

migrations/20221011041400_add_mfa_indexes.up.sql

* the `information_schema.check_constraints` view doesn't show information about the primary key on the `mfa_amr_claims` table so we should use the `information_schema.table_constraints` view instead

fix: make migration idempotent

---

api/admin.go
api/invite.go
api/magic_link.go
api/mail.go
api/otp.go
api/phone.go
api/phone_test.go
api/recover.go
api/signup.go
api/token.go
api/user.go
api/verify.go

* make `validateEmail` and `validatePhone` private methods in the `api` package instead of a struct method of the API struct 
* `validateEmail` used to rely on the `ValidateEmail` method in the `Mailer` interface. However, this is not necessary since we can just use the underlying lib directly

refactor: update validateEmail & validatePhone

---

api/token.go
openapi.yaml

The `POST /token?grant_type=id_token` implementation allowed any OpenID Connect compliant issuer to be used for authentication, albeit in a very limited and broken way. Given we are not supporting this at this time, the implementation is being removed.
Existing OIDC providers, importantly `google` and `apple` continue to be supported.

feat: remove `id_token` flow with freeform provider

---

internal/api/token.go
openapi.yaml

Reverts supabase/gotrue#927 due to identifying that some users do actually use this API but only for Apple and Google. I'll come back with another PR that blocks non-Apple and Google issuers only.

feat: revert "remove `id_token` flow with freeform provider"

---

internal/api/token.go
internal/conf/configuration.go

Allows the explicit configuration of the ID token flow with freeform issuers. Given this is a deprecated functionality for security reasons, a warning log is emitted.

feat: deprecate and explicitly allow freeform ID token issuers

---

go.mod
go.sum
internal/api/sms_provider/sms_provider_test.go
internal/api/sms_provider/vonage.go

Bug fix
When the message contains Chinese / Japanese character, the message will be displayed in garbled text.
If the message contains unicode character, set 'type' to 'unicode' in the request payload before making the request to vonage api server

fix: garbled text in sms message when message contains unicode

---

Dockerfile
Dockerfile.dev
app.json
netlify.toml

Further renaming from netlify -> Supabase. Main change here is on the dev set up - if one cleans out existing image +  volumes + cache and runs `make dev` the build step will error with `"Failed to load configuration: open .env.docker: no such file or directory` as Docker will look in `/go/src/github.com/netlify/gotrue` instead of `/go/src/github.com/supabase/gotrue`

fix: Change Dockerfile.dev target from netlify to Supabase

---

migrations/20210927181326_add_refresh_token_parent.up.sql
migrations/20211122151130_create_user_id_idx.up.sql
migrations/20220114185221_update_user_idx.up.sql

This PR fixes some errors on inital database migrations.
On database initialization following errors occur:
- `add_refresh_token_parent`:
```
{"level":"fatal","msg":"running db migrations: error executing /usr/local/etc/gotrue/migrations/20210927181326_add_refresh_token_parent.up.sql, sql: -- adds parent column\n\nALTER TABLE auth.refresh_tokens\nADD COLUMN IF NOT EXISTS parent varchar(255) NULL;\n\nDO $$\nBEGIN\n  IF NOT EXISTS(SELECT *\n    FROM information_schema.constraint_column_usage\n    WHERE table_schema = 'auth' and table_name='refresh_tokens' and constraint_name='refresh_tokens_token_unique')\n  THEN\n      ALTER TABLE \"auth\".\"refresh_tokens\" ADD CONSTRAINT refresh_tokens_token_unique UNIQUE (\"token\");\n  END IF;\n\n  IF NOT EXISTS(SELECT *\n    FROM …
```

fix: add missing namespace prefix to index targets

---

internal/api/errors.go
internal/api/otp.go
internal/api/otp_test.go
internal/api/phone.go
internal/api/phone_test.go
internal/api/reauthenticate.go
internal/api/resend.go
internal/api/signup.go
internal/api/sms_provider/messagebird.go
internal/api/sms_provider/sms_provider.go
internal/api/sms_provider/textlocal.go
internal/api/sms_provider/twilio.go
internal/api/sms_provider/vonage.go
internal/api/user.go
openapi.yaml

We wish to support WhatsApp as a channel for sending OTPs due to the added security provided and more. For this first pass, we will only support Twilio. 
Companion PR:
- Frontend:  https://github.com/supabase/gotrue-js/pull/616
For now, we only support Twilio API. We can slowly ungate more providers as needed. There should be no change to the API guarantees otherwise - if the user does not specify `whatsapp` the API will default to SMS.
I've excluded `reauthenticate` and `resend` methods from whatsapp support as we don't currently use them in the client library. I'm not sure whether we plan on supporting them long term so have  left them with SMS as default in order to reduce complexity. Let me know if anyone feels otherwise and we can consider amending.
For now, we also expose the …

feat: support for whatsapp as a channel for sending OTPs 

---

README.md

Change the requirement for admin role to service role so as to align with what is offered via platform (Service key role seems to be required)
Related issue: https://github.com/supabase/gotrue/issues/794

Update README.md /admin/users/<user_id> route docs

---

internal/api/api.go

* #980 
* expose the "x-total-count" and "link" headers which are useful for the `GET /admin/users` method

fix: expose x-total-count and link

---

internal/models/factor.go

- Change deletion to a raw query.
- Removes another unused function
When verifying a factor, unverified factors are deleted. Currently this is done by passing in a `[]*Factor` which isn't handled by soda's `Destroy()` method well as it doesn't play well with pointers to a Model
There will be a FLUP with an updated end to end test  + removal of other potential deletion/update functions which involve a `[]*model`

Fix MFA deletion of unverified factors

---

README.md

Fixes link to point to Netlify's repo rather than the forked version.
Links to existing repo.
Links to the original Netlify gotrue repo.

Fix link on README

---

internal/models/user.go
migrations/20230116124310_alter_phone_type.up.sql

Given that with #489 we added a migration that alters the data type of `users.phone` and `users.phone_change` from `varchar(15)` to `text`, which turns out not to be a backward compatible change due to the inability for the alter to occur if there are views or triggers on the table, this PR does the following:
- Tries to change the data type if possible.
- The soft-delete code is modified to obfuscate phone numbers using Base64-URL and only the first 15 chars so they fit in `varchar(15)`.
- The obfuscation code uses a hash of the user UUID to decrease the likelihood of collisions on shorter values.

feat: make phone data type alter backward compatible

---

internal/conf/configuration.go

Removes the warning that SAML is an incomplete feature, as it has been in dogfooding and early-beta for months now.

feat: remove saml beta warning

---

internal/api/otp.go
internal/api/verify.go

Move validation to a `.Validate()` method for `OtpParams` and `VerifyParams`  similar to how validation is done on the `/resend` endpoint
Refactor for magic link and SMSOTP coming in a FLUP

refactor: move param validation to function

---

internal/api/token.go
internal/models/flow_state.go

see title, allows expiry check to be re-used. 
Should probably do the same with MFA and convert the config var to a `time.Duration` - probably after LW

refactor: move flow state expiry check to function

---

internal/models/audit_log_entry.go
openapi.yaml

Adds the `actor_via_sso` boolean value to the audit log, which can be used to track audit events for actors using a SSO protocol to authenticate.

feat: add `actor_via_sso` to audit log

---

internal/api/api.go
internal/api/middleware.go
internal/api/middleware_test.go
internal/api/settings.go
openapi.yaml

* Moves the `SAML_ENABLED` check to a middleware function 
* Display information about whether SAML is enabled in the `/settings` endpoint

fix: update settings & route for SAML

---

internal/api/external_github_test.go
internal/api/token.go
internal/api/token_test.go
openapi.yaml

After further thought, the `/token?grant_type=oauth_pkce` need not be constrained for use to only `oauth` flows. All PKCE implementations perform the same checks can re-use the same  generic `grant_type=pkce` route as the route is generally agnostic to the flow taken to get there (e.g. via magic link, recovery)
It's worth noting that we need to track the flow type in order to store the corresponding AAL claim 
[through the refresh token](https://github.com/supabase/gotrue/blob/master/internal/api/token.go#L630) (e.g. OAuth, OTP, etc)
This can be done via the introduction of a database column `authentication_method_reference` which will store the login flow used to get an auth code. 
As the addition of a column is potentially permanent, I've left it out and am instead including it in the …

fix: update from oauth_pkce to pkce

---

internal/api/pkce.go
internal/api/verify_test.go

Currently, code challenge validity is only enforced on the OAuth endpoint. We move this check to the validate params method. There will be a FLUP which refactors the oauth endpoint to use the validate params method.

fix: enforce code challenge validity across endpoints

---

internal/api/external.go
internal/api/external_test.go
internal/api/pkce.go
internal/api/token_test.go
internal/api/verify_test.go
internal/models/flow_state.go
openapi.yaml

The flow_type parameter is not needed as we can deduce the flow from the presence of  a code_challenge (pkce if present, implicit if not)

Refactor: remove flow_type param from oauth

---

example.env

The `DB_` prefix was added and it's needed for the migrations to run to completion

chore: update example .env file to use DB_NAMESPACE instead of NAMESPACE

---

internal/api/external.go
internal/api/pkce.go
internal/api/recover.go
internal/api/signup.go
internal/api/verify.go
internal/api/verify_test.go
internal/models/factor.go
internal/models/flow_state.go

* Fix issue where signup was always creating a flow state regardless of whether the flow type was pkce or implicit
* Fix issue where `/recover` was not parsing the `code_challenge_method`
* Ensure that we check the flow state based on the authentication method as well

fix: pkce issues

---

internal/api/verify.go

* Since `POST /verify` doesn't implement PKCE, it should check for cases where the initial request could have been a PKCE request 
* Fixes https://github.com/supabase/gotrue-js/issues/662

fix: POST /verify should check pkce case

---

migrations/20230322519590_add_flow_state_table.up.sql
migrations/20230402418590_add_authentication_method_to_flow_state_table.up.sql

With the introduction of an Authentication Method check on `FindFlowStateByUserID` we may wish to add an index. Also introduces an idempotency condition on flow state related migrations.  Finally, updates the old Postgres comment by [issuing a new comment to overrwrite previous comment](https://www.postgresql.org/docs/current/sql-comment.html)
Left as draft till this is tested together with other remaining PKCE changes.

fix: make flow_state migrations idempotent, add index

---

internal/api/mail.go
internal/api/user.go

* Email change requests on `PUT /user` should adhere to the max frequency rule.

fix: check freq on email change

---

internal/api/mail.go
internal/api/signup.go

Missed this, follows from #1078 which allows us to substitute the following two errors

refactor: replace unprocessableEntityError  with invalidPasswordLengthError

---

internal/api/mfa.go
internal/api/mfa_test.go
internal/models/challenge.go
internal/models/factor.go
internal/models/sessions.go

The current MFA checks are quite unreadable. Have refactored parts of it and I think there's more to refactor.

refactor: simplify MFA checks

---

internal/api/mail.go
internal/api/resend.go
internal/api/user.go
internal/api/verify_test.go
internal/models/factor.go

Add PKCE to email Change routes
No PKCE on email change routes
PKCE on email change routes 
There's an additional AMR claim known as `email_change` I'm not sure whether we want to have a special claim for this given that `email_change` is not typically classed as a login method. The other option would be to use the Magic Link AMR claim instead. Let me know if anyone has a preference here.
Should be tested  with: https://github.com/supabase/gotrue-js/pull/661/files
TODOs:

feat: add pkce to email_change routes

---

README.md
internal/api/middleware.go
internal/api/middleware_test.go
internal/conf/configuration.go
internal/security/captcha.go
internal/security/hcaptcha.go

Captcha providers are treated as generic in this PR. Users can swap out the provider which in turn swaps out only the `siteverify` URL.  This approach generally works fine when considering `turnstile` and `hcaptcha` since both have similar feature sets.
However, for  other providers like `recaptcha` users might want to use specialized features such as Android recaptcha and  recaptcha V3 score. Since the [responses slightly differ between an android response and a generic response](https://developers.google.com/recaptcha/docs/verify), we may need to introduce separate structs.
Another alternative considered was to initialize a new provider type for each methods (similar to `SMSProvider`) and have corresponding `verifyCaptcha` methods for each provider. This way there is clear separation of …

feat: add turnstile support

---

internal/api/external.go
internal/api/verify.go

Currently, it seems like PKCE flow implementation incorrectly adds a `?` instead of a `&` to the url when there is a redirect with multiple parameters (e.g. on `/resend` like in the url below:) . This PR aims to fix this.

fix: correct pkce redirect generation

---

internal/api/ssoadmin.go

Fix the `PUT` `/admin/providers/<id>` endpoint not committing the SAMLProvider changes to the database when updating the metadata XML (resulting in a no-op).
Updates to the metadata XML via the `/admin/providers/<id>` should be reflected on the `saml_provider` database object.
The provider metadata XML can now be correctly updated.

feat: allow updating saml providers `metadata_xml`

---

internal/models/linking.go

The issue is that the modified account linking algorithm _always_ linked SSO to non-SSO accounts if a similar email account was present.

feat: fix account linking

---

internal/api/samlacs.go
internal/api/sso_test.go

If the SAML Metadata defined via a URL does not publish validity or cache duration information, forcefully try to update it every 24 hours.

feat: add saml metadata force update every 24 hours

---

internal/models/cleanup.go
migrations/20230508135423_add_cleanup_indexes.up.sql
migrations/20230523124323_add_mfa_challenge_cleanup_index.up.sql

This PR extends #875 to clean up MFA challenges as well so that they don't clog the database.
set `GOTRUE_DB_CLEANUP_ENABLED = true`
1. Sign up locally
2. Enroll a factor
3. `ab -p testfileforab -T application/json -H 'Authorization: Bearer <token>' -c 10 -n 100 http://localhost:9999/factors/0bca5d9c-157a-4a15-890c-2ad33415b4f3/challenge` 
4. `update auth.mfa_challenges set created_at = created_at - interval  '48 hours';`
5. Make about 7 requests to ensure there's a cleanup performed

feat: add mfa cleanup

---

internal/api/external.go

With #999 custom domains were introduced, however for OAuth, the redirect URLs should in fact be the ones specified in the config and not ones interpreted from the `X-Forwarded-Host` header.

fix: use configured redirect URL for external providers

---

internal/api/external.go
internal/models/linking.go
internal/models/linking_test.go

* The account linking algorithm in [`DetermineAccountLinking()`](https://github.com/supabase/gotrue/blob/577a97e7aad241fcb8562ded195f8c2e55250272/internal/models/linking.go#L52) checks if the slice of emails returned by the oauth provider matches an existing email in the database. However, the emails returned by the oauth provider might not be lowercase. This may result in cases where the account linking algorithm thinks that a new user should be created instead. For example:
```
Existing user's email: "foo@example.com"
New oauth identity emails: [ "FOO@example.com", "bar@example.com" ] 
```
This would result in [this line](https://github.com/supabase/gotrue/blob/577a97e7aad241fcb8562ded195f8c2e55250272/internal/models/linking.go#L77) failing to return the existing user's email because …

fix: lowercase oauth emails for account linking

---

internal/api/provider/oidc.go
internal/api/provider/oidc_test.go

Google seem to rotate their OIDC JWKS keys regularly, which made the tests fail. This time the verifier is overridden and uses a static key at the time of generating of the ID token.

tests: fix flaky Google ID token test

---

internal/api/admin.go
internal/api/admin_test.go
internal/api/samlassertion.go

PingIdentity usually sends the email address in `Mail` with capital M. We also are allowing deleting the user record when the user is SSO with the admin API.

feat: infer `Mail` in SAML assertion and allow deleting SSO user

---

internal/api/samlacs.go

When GoTrue needs to update the SAML metadata XML by fetching from the URL, there were a few issues:
- `Update` was being called with a non-pointer argument which generally fails with a panic in Pop 😞 
- Only the `metadata_xml` and `updated_at` columns should be updated
This PR fixes it.

feat: fix SAML metadata XML update on fetched metadata

---

internal/api/user.go
internal/models/identity.go

* When updating a user's email or phone number, if the user previously did not have an email or phone number associated to their account, gotrue will create an new identity for it. However, subsequent attempts to update the user's email or phone number will result in gotrue attempting to create the same identity again. This results in postgres returning a unique constraint violation. 
For example, assuming that the user signed up with email + password initially:
```bash
curl -X PUT "http://localhost:9999/user" -H "Authorization: Bearer <access_token>" -H "Content-Type: application/json" -d '{"phone": "123456789"}'
curl -X PUT "http://localhost:9999/user" -H "Authorization: Bearer <access_token>" -H "Content-Type: application/json" -d '{"phone": "123456789"}'
```
* ~This PR attempts to fix …

fix: duplicate identity error on update user

---

internal/api/helpers.go
internal/api/user.go
internal/models/identity.go

* Create a `Validate()` method to handle the validation of the request body separately
* Moves some of the input validation out of the transaction into the `Validate()` method

refactor: validate update user params separately

---

internal/api/otp.go
internal/api/phone.go
internal/api/phone_test.go
internal/api/reauthenticate.go
internal/api/resend.go
internal/api/signup.go
internal/api/sms_provider/messagebird.go
internal/api/sms_provider/sms_provider.go
internal/api/sms_provider/sms_provider_test.go
internal/api/sms_provider/textlocal.go
internal/api/sms_provider/twilio.go
internal/api/sms_provider/vonage.go
internal/api/user.go
openapi.yaml

Returns the SMS message ID as received from the SMS sending provider in `/otp` and `/resend` to aid in debugging deliverability issues. Logs also include the message ID when available.

feat: return SMS ID when possible

---

internal/api/signup.go

* Set `IsSSOUser` field on user only after err has been checked, else this might result in a panic the the rare case where  `models.NewUser` returns an error

fix: check err before using user

---

.gitattributes

This addresses differences in eol handling between OSes by normalizing the line endings using a `.gitattributes` file.
On Windows, cloning the repo and building the containers causes the Postgres container to fail to initialize and shutdown early due to `init_postgres.sh` being copied into the container with Windows line endings. 
Fixes #1155
New clones of the repo shouldn't have issues with this after this PR is merged. Existing clones which don't already contain `LF` line endings may have to reset using
```
git rm --cached -r .
git reset --hard
```
to update their files' line endings.

chore: normalize line endings

---

go.mod
go.sum
internal/mailer/mailer.go

Switches to github.com/supabase/mailme instead of Netlify's mailme package.
Fixes:
- #870

feat: switch to github.com/supabase/mailme package

---

cmd/root_cmd.go
cmd/serve_cmd.go
internal/conf/configuration.go
internal/conf/profiler.go
internal/observability/profiler.go
main.go

* Adds a profiler server (pprof) to gotrue

fix: add profiler server

---

internal/api/logout.go
internal/api/logout_test.go
openapi.yaml

Right now, probably due to a bug, `POST /logout` would log the user out from _all_ sessions they have. This is not always desired behavior.
This change adds a new `scope` query param on `/logout` with these values:
- `global` (default when not provided) Logs a user out from all sessions they have.
- `local` Logs a user out from the current session only.
- `others` Logs a user out from all other sessions except the current one.
See:
- https://github.com/supabase/gotrue-js/pull/713

feat: add different logout scopes

---

internal/mailer/mailer.go
internal/mailer/mailer_test.go
internal/mailer/template.go

* Maintains the order of the query params passed into the email link

fix: maintain query params order

---

internal/api/user.go

When the user updates their password, the new and old passwords must be different. When an admin does it, this is not checked.

feat: require different passwords on update

---

internal/api/verify.go
internal/api/verify_test.go

* To enable server-side redirection via an email link, we need some way to return the session in the response body rather than in the query fragments (`GET /verify`) because the fragments can't be parsed on the server-side.
* By allowing `POST /verify` to accept just a token hash, a developer would be able to set the verification URL in their email template to point to their own endpoint (`https://myapp.com/confirm-signup?token_hash=XXX&type=signup`) and  parse the `token_hash` param before calling `POST /verify` with the following:
```bash
curl -X POST 'http://localhost:9999/verify' -H 'Content-Type: application/json' \ 
-d '{"token_hash": "my_token_hash", "type": "signup" }'
```
If the token hash is valid and the request is successful, this would return the verified user's session in …

feat: allow `POST /verify` to accept a token hash

---

internal/models/refresh_token.go

`updated_at` was not being updated when the token family was being revoked, which makes it impossible to figure out when the revocation actually happened.

feat: set `updated_at` on `refresh_tokens` when revoking family

---

internal/api/provider/discord.go

* Fixes https://github.com/supabase/gotrue/issues/1133
* Note: The `global_name` attribute will just default to an empty string if it's not returned by discord / not present

fix: add discord `global_name` to custom_claims

---

internal/api/middleware.go

* Remove captcha protection on `id_token` grant since the protection is provided by the OIDC issuer
* Fixes #1172

fix: remove captcha on id_token grant

---

internal/api/verify.go
internal/api/verify_test.go
internal/models/errors.go
internal/models/user.go

* Allow `POST /verify` to accept the email verification type when used together with the `token_hash`
* For example:
```
curl -X POST "http://localhost:9999/verify" -H "Content-Type: application/json" -d '{"token_hash": "d00bae897e954fd46a72d72ee9e00eb3e061541413395f08f7f754c1", "type": "email"}'
```

fix: support email verification type on token hash verification

---

internal/api/signup.go

Allow autoconfirm signup to be used with PKCE. When used with PKCE,  autoconfirm signups retain their behaviour of returning an access token directly
Calling signup with autoconfirm enabled will throw an error
Calling signup with autoconfirm enabled will return a session similar to implicit flow
Linked to: https://github.com/supabase/gotrue/pulls?q=is%3Apr+is%3Aclosed++accept+

feat: drop restriction that PKCE cannot be used with autoconfirm

---

internal/api/pkce.go
internal/mailer/template.go

Removes the expiry on flow state which might overshadow the `OTP expiry` since default OTP expiry (1 day) is typically longer than default flow state expiry (5 mins). Flow state expiry is still enforced on token exchange.
Flow state expiry is checked on verification/issuance of Auth code
No flow state expiry check on verification of magic link. Flow state expiry continues to be enforced on token exchange.

feat: remove flow state expiry on Magic Links (PKCE)

---

internal/api/api.go
internal/api/external.go
internal/api/helpers.go
internal/api/invite.go
internal/api/magic_link.go
internal/api/mail.go
internal/api/mail_test.go
internal/api/recover.go
internal/api/resend.go
internal/api/samlacs.go
internal/api/signup.go
internal/api/user.go
internal/api/verify.go
internal/observability/request-logger.go
internal/utilities/request.go
internal/utilities/request_test.go

* Currently, we always log [`r.Referer()`](https://cs.opensource.google/go/go/+/refs/tags/go1.20.5:src/net/http/request.go;l=454) in the gotrue logs. However, this assumes that the referrer is always sent in the header which is false.
* Move the functions to get the referrer and validate the referrer to  the `utilities` package so it can be used across the `api` and `observability` packages
* Removed `getRedirectURLOrReferrer` because it's basically a repeat of `getReferrer`. You would still need to parse the `redirect_to` before calling `getRedirectURLOrReferrer` and `getReferrer` handles the parsing + validation for us already.

fix: log correct referer value

---

internal/api/middleware.go
internal/api/middleware_test.go

* Rate limit for total emails / sms-es sent should only be applied when autoconfirm is disabled

fix: only apply rate limit if autoconfirm is false

---

internal/api/token.go
internal/api/token_refresh.go

To make the `token.go` file less busy.

refactor: move refresh token grant to new file

---

internal/api/auth.go
internal/api/mfa_test.go
internal/api/token.go
internal/api/token_refresh.go
internal/api/user_test.go
internal/models/refresh_token_test.go
internal/models/sessions.go
internal/models/sessions_test.go
internal/models/user.go
internal/models/user_test.go

Improves the `refresh_token` grant flow by serializing access over the session ID, so that a session cannot concurrently be refreshed.
It achieves this by adding a boolean `forUpdate` parameter to `models.FindSessionByID()` and `models.FindUserWithRefreshToken()`. This in turn uses a [`SELECT ... FOR UPDATE`](https://www.postgresql.org/docs/current/sql-select.html#SQL-FOR-UPDATE-SHARE) query that locks the row from use with other flows that select it with a `FOR UPDATE` clause.

feat: serialized access to session in `refresh_token` grant

---

internal/mailer/template.go

withDefault returns a string, so cast isn't strictly needed

refactor: drop string cast on withDefault

---

internal/api/invite_test.go
internal/api/mail.go
internal/api/mail_test.go
internal/api/phone.go
internal/api/reauthenticate.go
internal/api/user_test.go
internal/api/verify.go
internal/api/verify_test.go
internal/crypto/crypto.go

see title -  relevant command:
```
#!/bin/bash
replace_in_files() {
sed -E -i '' 's/fmt\.Sprintf\("%x", sha256\.Sum224\(\[\]byte\(([^+]+)\+([^)]+)\)\)\)/crypto.GenerateTokenHash(\1, \2)/g' "$1"
}
if [ -z "$1" ]; then
echo "Please provide the directory path as an argument."
exit 1
fi
if [ ! -d "$1" ]; then
echo "Directory not found: $1"
exit 1
fi
for file in "$1"/*; do
if [ -f "$file" ]; then
replace_in_files "$file"
fi
done
```

refactor: replace fmt.Sprintf with generateTokenHash

---

internal/api/token_refresh.go

Should be using `tx` in refresh token grant instead of `db`. Thanks @bnjmnt4n for [spotting this](https://github.com/supabase/gotrue/pull/1190#discussion_r1270861390).

fix: use started transaction, not a new one

---

internal/api/api.go
internal/conf/configuration.go

Adds a new `GOTRUE_CORS_ALLOWED_HEADERS` config option to add additional allowed headers when performing CORS with GoTrue.

feat: add CORS allowed headers config

---

internal/api/audit_test.go
internal/api/invite_test.go
internal/api/logout_test.go
internal/api/mfa_test.go
internal/api/phone_test.go
internal/api/token.go
internal/api/token_refresh.go
internal/api/user_test.go
internal/api/verify_test.go
openapi.yaml

There are cases where the response for an access and refresh token takes more than 1 second. In such cases, `gotrue-js` will record the *expiry time* as the time it received the response + `expires_in`. However, this is not correct because the access token is likely to have already expired by the recorded time.
With this change, `gotrue-js` can just use an `expires_at` value instead. `expires_in` is still sent for backward compatibility.

feat: return `expires_at` in addition to `expires_in`

---

internal/models/user.go

* Currently, if an identity exists without a user (e.g. the dev accidentally inserts a user identity without creating a user), `IsDuplicatedEmail` function will panic because we omit the check for `IsNotFound(err)`. This leads to a `nil` user being accessed when you check for `user.Aud` which leads to a panic.

fix: return error if user not found but identity exists

---

internal/api/token.go
internal/models/amr.go
internal/models/sessions_test.go

* We're querying for the session redundantly when we already have the sessionId. Every time we query for a session, it fetches all the amr claims tied to the session too.
* There's no need to query for the entire session when we already have the session id, since the `auth.mfa_amr_claims` table already has a foreign-key constraint on the `auth.sessions.id` column, the insert will fail if the given `sessionId` doesn't exist

fix: remove redundant queries to get session

---

internal/api/phone.go
internal/api/phone_test.go
internal/conf/configuration.go

When developers build mobile apps that use phone login, they need to provide pre-determined phone numbers and OTPs that will work so that automated and manual app reviewers (that work at Apple's AppStore or Google's Play Store) can test and confirm compliance with the phone system.
Those reviewers / systems cannot be expected to provide their own phone number.
Developers can thus set up the following environment variable:
```
GOTRUE_EXTERNAL_SMS_TEST_OTP="<phone-1>=<otp-1>, <phone-2>=<otp-2>..."
GOTRUE_EXTERNAL_SMS_TEST_OTP_VALID_UNTIL="<ISO date time>"
```
SMS messages are not sent to those test phone numbers. Furthermore after the validity period has expired, they will automatically not be used. This enhances the security so that people don't forget test OTPs accidentally.
Incidentally …

feat: add test OTP support for mobile app reviews

---

internal/api/sms_provider/sms_provider.go

WhatsApp is supported by Twilio Verify but we've missed the validation here.

feat: allow `whatsapp` channels with Twilio Verify

---

README.md
example.docker.env
internal/conf/configuration.go
internal/conf/configuration_test.go

Bug fix, setting sane defaults
https://github.com/supabase/gotrue/issues/1194
- If the configuration API_EXTERNAL_URL is not set requests to gotrue return 500 errors. This configuration was undocumented and only part of some examplary configurations.
- If the URLPaths for the Mailer are not set they defaulted to / which by default is not the correct endpoint to handle verification requests. 
- API_EXTERNAL_URL needs to be set for gotrue to start.
- URLPaths for Invite,Confirmation,Recovery and EmailChange are set to "/verify" by default instead of "/"

Issue #1194 - Gotrue is returning http 500 if API_EXTERNAL_URL is not set

---

internal/api/external.go
internal/api/middleware.go
internal/crypto/password.go
internal/observability/metrics.go

- Move metric counter to observability package so that we can reuse it to track other metrics
- Rename `NetlifyMicroserviceClaims` to `AuthMicroserviceClaims`
Supports the email rate limit task

refactor: centralize metric counter to observability package

---

internal/api/external.go
internal/api/middleware.go
internal/crypto/password.go
internal/observability/metrics.go

This PR aims to expose a set of email rate limit metrics as a Prometheus metric that can then be consumed by an alerting system like Prometheus. When a rate limit is triggered we increment a counter. This can then be passed to a monitoring system such as Prometheus alert manager which can fire off a notification (or similar) when a threshold (say 5 occurrences in an hour) has been breached.
Extends: #1213 
The presence of the metric was tested via using the default `prometheus.yml` file that comes on download.  To test that the rate limit is firing, we decreased `GOTRUE_RATE_LIMIT_EMAIL_SENT="5"` to 5 and ran `ab` against the endpoint like
`ab -p mass_signup.txt -T application/json  -c 10 -n 50 http://localhost:9999/otp`

feat: add email rate limit breach metric

---

internal/api/phone.go
internal/api/verify_test.go

* OTP should be test if not using the test OTP

fix: set the otp if it's not a test otp

---

internal/api/api.go
internal/api/resend.go
internal/api/resend_test.go

Move the check for whether email logins are enabled into the resend function. Also checks if Phone Logins are enabled before proceeding to resend
Currently, the check  is done in middleware. This would mean that resend requests with phone based logins will not go through if email logins are disabled.

chore: amend email and phone enabled checks on resend 

---

internal/mailer/template.go

- Exposes the email address that we're sending to so that devs can customize the email conditionally
Build and update a staging project to use the GoTrue binary from this branch.
On staging, add `{{.SendingTo}}` as a parameter and execute email change. Confirm that the parameter is parsed on both emails when using secure email change.

feat: expose email address being sent to for email change flow

---

internal/api/verify.go
internal/api/verify_test.go

There are two issues the PR aims to resolve:
1. Currently, a Token Hash can be re-used twice in place of using the token hash send to the new email and a token has in the current mail. A solve attempt was originally made in #1240 but a test was added in this branch.
2. Currently, the single confirmation response is slightly misformed and has an additional null param
This stems from the return in the transaction. sendJSON doesn't return an error. Consequently, he error returned by the transaction will be nil. This leads to 
`sendJSON(w, http.StatusOK, token)`  being run after `sendJSON` is callled which will write the `token` (`nil` in this case) to the existing singleConfirmationResponse. This in turn affects returned response for the  first confirmation as the client library is unable to …

fix: patch secure email change (double confirm) response format.

---

internal/api/external.go
internal/api/external_test.go

Aims to address #1150  so that we can pass redirect query parameters alongside errors. Note that if any of the existing query parameters are named `error` or `error_description` they will be overwritten. In such cases, the error added by Supabase Auth will take precedence
When an error occurs the redirect query params only return error and error_description without other query parameters.
- Case with Error was induced by artifically returning an error in `internalExternalProviderCallback`
- Happy path was tested as per normal

fix: pass through redirect query parameters

---

internal/api/external.go
internal/api/provider/linkedin_oidc.go
internal/api/settings.go
internal/conf/configuration.go

This PR introduces a new linkedin provider to address issues related to the current LinkedIn provider no longer being available for new applications.
LinkedIn applications created after 1st of August experience difficulties while attempting to log in with GoTrue due to incorrect scope requests.
Relevant issue: https://github.com/supabase/gotrue/issues/1216#issuecomment-1688943690
Relevant initial fix however would lead to breaking existing apps - https://github.com/supabase/gotrue/pull/1232
This PR aims to rectify the issue by adding a new provider with the updated OAuth scopes. Specifically, the scopes openid, email, and profile will be utilized. Additionally, the method of collecting profile information is updated, employing the /v2/userinfo API endpoint.
Visual changes: No visual …

fix: add new Linkedin OIDC due to deprecated scopes for new linkedin applications

---

internal/api/provider/linkedin_oidc.go
internal/api/provider/oidc.go

* Add OIDC support for the linkedin provider as highlighted [here](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2#validating-id-tokens) 
* Addresses #1216

fix: use linkedin oidc endpoint

---

internal/api/phone.go
internal/api/phone_test.go
internal/api/sms_provider/messagebird.go
internal/api/sms_provider/sms_provider.go
internal/api/sms_provider/sms_provider_test.go
internal/api/sms_provider/textlocal.go
internal/api/sms_provider/twilio.go
internal/api/sms_provider/twilio_verify.go
internal/api/sms_provider/vonage.go
internal/conf/configuration.go

As of October, Meta will be having a separate category [for billing authentication related templates (such as OTP)](https://support.twilio.com/hc/en-us/articles/13550552351771-Notice-Changes-to-WhatsApp-Template-Approval-Workflows-April-2023-). Consequently, it looks like WhatsApp Authentication templates need to be [submitted for approval via the content API](https://www.twilio.com/docs/content/whatsappauthentication?code-sample=code-sending-wa-authentication-templates&code-language=Go&code-sdk-version=1.x).
Consequently, there are two new parameters `ContentSID` and `ContentVariables` that need to be passed in.  `ContentVariables` contains the OTP and can be passed down from the calling functions. These parameters are needed in order to allow for WhatsApp use  on Twilio Programmable …

feat: upgrade whatsapp support on Twilio Programmable Messaging

---

internal/api/invite_test.go
internal/api/signup.go
internal/models/user.go

Currently, sending an `invite` request followed by a `signup` request  w/o  confirmation between invite and signup will expose metadata on UserMetadata and Identities which may be perceived as a leak of sensitive information.
This PR aims to clear out such metadata for cases where the dev has been invited before a signup
How to test locally:
Use this admin bearer `jwt` 
1. Call  http://localhost:9999/invite to `myemail@gmail.com`
2. Wait 60s 
3. Call http://localhost:9999/signup with `myemail@gmail.com` and check that `identities` field is blanked out

feat: initial fix for invite followed by signup.

---

internal/api/phone.go
internal/api/phone_test.go
internal/api/sms_provider/messagebird.go
internal/api/sms_provider/sms_provider.go
internal/api/sms_provider/sms_provider_test.go
internal/api/sms_provider/textlocal.go
internal/api/sms_provider/twilio.go
internal/api/sms_provider/twilio_verify.go
internal/api/sms_provider/vonage.go
internal/conf/configuration.go

Resinstates WhatsApp support for the content API by reinstating: https://github.com/supabase/gotrue/pull/1249
After further discussion, it looks like we do have users who are using custom SMS templates (e.g. "Your <company> code is {{.code}} ")
We were notified that this is required as alphanumeric senders require the company name in the  message. This means we will need to support the Content API as custom messages aren't allowed under Programmable Messaging API + WhatsApp Template
There will be 2 more PRs after this:
1. PR to allow for backward compatibility with Basic Authentication Template
2. PR to add ContentSid env var
3. Dashboard PR to expose variable

feat: reinstate upgrade whatsapp support on Twilio Programmable Messaging to support Content API

---

internal/api/sms_provider/twilio.go

Twilio has come back with clarification that Legacy WhatsApp Template can contain compliant authentication template
> The compliant authentication template format is supported in Content API, Content Editor and Legacy WhatsApp Templates. 
> Legacy Templates: Support for basic authentication message only.
This means that we'd have to preserve support for messages which don't include ContentSid/ContentVariables. Namely this would be messages which are using the Legacy WhatsApp template with the message: `*{{1}}* is your verification code. For your security, do not share this code.` . It seems like anything else will be rejected.
Full article: https://support.twilio.com/hc/en-us/articles/15596541039771-New-WhatsApp-Authentication-Template-Requirements-May-2023

fix: preserve backward compatibility with Twilio Existing API

---

internal/api/external_azure_test.go
internal/api/external_test.go
internal/api/provider/azure.go
internal/api/provider/azure_test.go
internal/api/provider/oidc.go
internal/api/provider/oidc_test.go

Use the OIDC ID token instead of the UserInfo endpoint, as there are serious discrepancies between what is returned.

feat: use OIDC ID token for Azure

---

internal/api/token_oidc.go
internal/conf/configuration.go

It appears that in certain client libraries that deal with the OIDC authentication flow, such as [this one for React Native on iOS](https://github.com/google/GoogleSignIn-iOS/pull/244), the clients are unable to extract the nonce that is generated randomly by the library. 
This option allows to temporarily drop the enforcement at the GoTrue level when performing the OIDC flow. This does remove an important security barrier, which could potentially allow "stolen" ID tokens to be used on third-party services (that have opted in to this configuration) however in the interest of flexibility and broad platform support the option is being added.

feat: add `GOTRUE_<PROVIDER>_SKIP_NONCE_CHECK` to skip nonce checks in ODIC flow

---

internal/api/provider/azure.go

If the developer has configured `GOTRUE_AZURE_URL` to be `https://login.microsoftonline.com/common` then the expected issuer setting is set to `https://login.microsoftonline.com/common/v2.0`. However this is not an issuer so no ID tokens will be issued by it, but rather from all other multi-tenant apps and tenants, so it needs to be ignored from the expected issuer setting.

feat: ignore common Azure issuer for ID tokens

---

internal/api/provider/azure.go
internal/api/token_oidc.go

* The issuer can also be https://login.microsoftonline.com/organizations for applications processing accounts in any organizational directory (any Microsoft Entra directory) (see [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-convert-app-to-be-multi-tenant))
* Fixes #1274

fix: include `/organizations` in expected issuer exemption

---

internal/mailer/template.go

* Expose the `{{ .RedirectTo }}` param in the email templates
* Fixes https://github.com/supabase/gotrue/issues/1271

fix: add redirectTo to email templates

---

migrations/00_init_auth_schema.up.sql
migrations/20221003041349_add_mfa_schema.up.sql
migrations/20221125140132_backfill_email_identity.up.sql

Bug fix; Adapting existing migrations to allow other 'Namespaces' than Auth
If a 'Namespace' (DB-Schema) other than 'auth' should be used the migrations fail
#1218 
Other db-schemas might be used for gotrue. 

fix: #1218 fixes existing migrations to allow namespaces!="auth"

---

internal/api/token_refresh.go
internal/api/token_test.go
internal/models/sessions.go
internal/storage/helper.go

Modifies the refresh token algorithm to support a limited form of idempotency. The lack of this behavior is documented to cause loss of session.
**Problem**
GoTrue, so far, assumes that clients calling the `POST /token?grant_type=refresh_token` endpoint are guaranteed to at least save the result of the response. Like all networked software, there are no guarantees that the sender of a request will receive the response, or act on it. This problem is exacerbated by network appliances like CDNs and reverse proxies which mask the TCP stream semantics from GoTrue. A properly closed TCP stream does not mean that the receiver of the response received the stream, but rather that a proxy in the chain buffered the response.
Furthermore, even if the receiver is able to receive _and parse_ the …

feat: add idempotent refresh token algorithm

---

internal/api/api.go
internal/api/token_refresh.go
internal/api/token_test.go
internal/conf/configuration.go
internal/models/sessions.go

Adds time-boxed sessions. These sessions time-out after a fixed amount of time configured via the `GOTRUE_SESSIONS_TIMEBOX` property (if set).

feat: add time-boxed sessions

---

internal/api/verify.go
internal/models/user.go

* Fixes #798 
* When a user requests for an email change via the `updateUser` method, it can use either the implicit or PKCE flow. However, when we verify the email change token, we should be checking for the `pkce_` prefix too.

fix: check for pkce prefix

---

.github/workflows/release.yml
.github/workflows/test.yml
Dockerfile
Dockerfile.dev

Bumps CI and Dockerfiles to use version 1.21 of Go.

ci: bump go version to 1.21

---

internal/api/external.go
internal/api/samlacs.go
internal/api/signup.go
internal/api/token.go
internal/api/token_oidc.go
internal/api/token_refresh.go
internal/api/token_test.go
internal/api/verify.go
internal/conf/configuration.go
internal/models/refresh_token.go
internal/models/sessions.go
internal/utilities/request.go
migrations/20231027141322_add_session_refresh_columns.up.sql

Adds the ability for sessions to time-out after a period of inactivity. "Activity" is defined as refreshing the session.
This can be configured by setting the `GOTRUE_SESSIONS_INACTIVITY_TIMEOUT` to a duration.
Since this PR modifies the database by adding a new `refreshed_at` nullable column to `sessions`, it also adds some useful columns to the `sessions` table to track the `User-Agent` and IP address that performed the refresh / session creation.

feat: add inactivity-timeout to sessions

---

internal/api/token_refresh.go
internal/models/sessions.go

My previous force-push didn't succeed but I accidentally merged thinking it did.

refactor: rename `Session.UpdateRefresh` to `UpdateRefreshInfo`

---

internal/api/api.go
internal/api/middleware.go
internal/models/cleanup.go
internal/models/cleanup_test.go

Builds on top of #1288.
Adds cleanup for timeboxed sessions and sessions that have expired due to inactivity timeout. 
It achieves backward compatibility with sessions that have `null` in `refreshed_at` by looking at the `updated_at` column of the refresh tokens table. This approach is the one that puts the least strain on the database, having considered backfilling (very expensive at least `O(nlogn)` over the whole refresh tokens table).

feat: add cleanup for session timebox and inactivity timeout

---

internal/conf/configuration.go

Change the defaults for`RATE_LIMIT_TOKEN_REFRESH` from 30 to 150 to allow for more token refreshes and also to match what is offered on the hosted platform.

Update defaults for RATE_LIMIT_TOKEN_REFRESH

---

internal/api/token_refresh.go
internal/api/token_test.go
internal/conf/configuration.go
internal/models/refresh_token.go
internal/models/sessions.go
migrations/20231114161723_add_sessions_tag.up.sql

Enforces a single session per user with optional tags. If a session has a tag, only the most recently refreshed session with the same tag can be refreshed. If no tags are configured, then only the most recently refreshed session of all of the user's sessions will be refreshed. 
Sessions that are invalid due to inactivity or timeboxing won't be considered.

feat: add single session per user with tags support

---

internal/api/external.go
internal/api/external_github_test.go
internal/api/external_kakao_test.go
internal/api/token_oidc.go
internal/storage/dial.go
internal/storage/dial_test.go

* This PR introduces a new error type `CommitWithError` that allows one to commit a transaction but also return an error. 
* This is useful in situations where `GOTRUE_MAILER_ALLOW_UNVERIFIED_EMAIL_SIGN_INS="false"` since oauth users with an unverified email will require email confirmation before being allowed to sign-in. If the transaction doesn't get committed, the new user doesn't get created and the email confirmation sent out will not be mapped to a user in the database.

fix: allow transactions to be committed while returning a custom error

---

internal/api/token_refresh.go
internal/api/token_test.go
internal/models/refresh_token.go
internal/models/sessions.go

Refresh token reuse revocation was broken, as an error was returned from the transaction where the revocation took place, which rolled back any changes. This went unnoticed as the reuse error was sent. Ouch.

feat: fix refresh token reuse revocation

---

internal/conf/configuration.go

* default `GOTRUE_MAILER_ALLOW_UNVERIFIED_EMAIL_SIGN_INS` to false

fix: disable allow unverified email sign ins if autoconfirm enabled

---

internal/api/admin_test.go
internal/models/identity.go
internal/models/user.go
migrations/20231117164230_add_id_pkey_identities.up.sql

* We need to be able to have a consistent identifier to fetch an identity from the database. The current approach for using a composite primary key isn't sufficient and not ideal for exposing through the API.
* Remove the composite primary key on (`auth.identities.id`, `auth.identities.provider`)
* Rename `auth.identities.id` to `auth.identities.provider_id`
* Add a new primary key called `auth.identities.id` 
* Add a unique constraint on (`auth.identities.provider_id`, `auth.identities.provider`)

feat: update primary key for identities table

---

internal/api/api.go
internal/api/mail.go

Follows the pattern where all admin handlers are named `adminXYZ`.

refactor: rename `GenerateLink` to `adminGenerateLink`

---

internal/api/admin.go
internal/api/admin_test.go
internal/api/mail.go
internal/api/password.go
internal/api/signup.go
internal/api/token.go
internal/api/user.go
internal/api/user_test.go
internal/api/verify.go
internal/models/linking_test.go
internal/models/user.go

Refactors all places where the password strength check (right now just length check) is enforced to a single method on the API `checkPasswordStrength`.
To do this, both `SignupParams` and `UserUpdateParams` had to be reworked. Furthermore user update now splits basic validation logic from user update validation logic and the main updating transaction which should drastically speed up the method itself.

feat: refactor for central password strength check

---

internal/api/mfa_test.go

The mfa tests are hard to read. There's also a lot of redundant code which makes testing for hooks quite a bit harder. This PR aims to remove some of the redundancy so that it's easier to write the tests for #1314
Main changes include
- Splitting out `enrollAndVerify` into `enroll` and `verify` 
-  Using suite specific constants
-  Packaging duplicated setup code

refactor: refactor mfa tests

---

README.md
internal/api/admin_test.go
internal/api/errors.go
internal/api/password.go
internal/api/password_test.go
internal/conf/configuration.go
internal/conf/configuration_test.go

Adds the `GOTRUE_PASSWORD_REQUIRED_CHARACTERS` config option, which if set, will reject passwords that do not contain at least one character of each set of characters.
It is defined like so: `abc...xyz:0123...89`. This means that at least one lowercase and one digit has to be present in the password to be accepted. All other characters are also allowed. To include the `:` character, escape it with `\:`.
When a weak password is detected, the HTTP 429 error is sent with an additional JSON field `weak_password` that includes a `reasons` property -- an array of the strings:
- `length` if the password is not long enough
- `characters` if the password does not use all required character sets

feat: add required characters password strength check

---

go.mod
go.sum
internal/api/api.go
internal/api/password.go
internal/conf/configuration.go
internal/utilities/hibpcache.go

Uses Supabase's HIBP Go library to perform password strength checks using the HaveIBeenPwned.org Pwned Passwords API.
You can configure this behavior by:
- `GOTRUE_PASSWORD_HIBP_ENABLED` to turn it on
- `GOTRUE_PASSWORD_HIBP_USER_AGENT` to specify your project's identifier
- `GOTRUE_PASSWORD_HIBP_FAIL_CLOSED` if the API is unavailable (or unresponsive for 5 seconds) the response is ignored and any password is accepted, set this to true to fail with a 500 error in such cases
- `GOTRUE_PASSWORD_HIBP_BLOOM_ENABLED` to enable a bloom filter cache
- `GOTRUE_PASSWORD_HIBP_BLOOM_ITEMS` to specify the maximum number of pwned password hashes to be stored in the bloom filter
- `GOTRUE_PASSWORD_HIBP_BLOOM_FALSE_POSITIVES` to specify the maximum number of false positives returned by the bloom filter, …

feat: add haveibeenpwned.org password strength check

---

internal/api/identity.go
internal/models/errors.go
internal/models/identity.go
internal/models/user.go
internal/models/user_test.go

* A primary identity is implicitly defined by the first identity created when the user signs up
* Addresses the issue where unlinking a primary identity results in the `auth.users.email` becoming stale. If the other identities do not have the same email, the `auth.users.email` column should be updated to use one of the existing identities emails
* Update the `FindProvidersByUser` method to remove duplicates if there is more than 1 identity that share the same provider

feat: unlinking primary identity should update email

---

internal/api/mfa.go
internal/hooks/auth_hooks.go

Refactors the error handling of hooks so the proper errors bubble up.

feat: refactor hook error handling

---

CONTRIBUTING.md

Update suggested Go version for contributors from `1.16` to `1.21`.

fix: update suggested Go version for contributors to 1.21

---

internal/api/mfa_test.go
internal/api/user_test.go

Primary goal of this refactor is to reduce number of calls to `generateAccessToken` to ease refactoring of `generateAccessToken`. This PR centralizes a few commonly used functions/objects:
- `generateAccessToken`
- `models.User`
- It also directly accesses `models.Factors` on `ts.TestUser` instead of fetching it from the DB via `models.FindFactorsByUserID`
Tests with multiple cases were left untouched as they have interleaving interactions in some cases

refactor: reduce amount of test setup code in mfa tests

---

internal/api/user_test.go

Similar to #1333 we centralize the setup around `generateAccessToken`

refactor: centralize generateAccessToken for user tests

---

go.mod
go.sum
internal/api/audit_test.go
internal/api/invite_test.go
internal/api/logout_test.go
internal/api/mfa.go
internal/api/mfa_test.go
internal/api/phone_test.go
internal/api/token.go
internal/api/token_refresh.go
internal/api/token_test.go
internal/api/user_test.go
internal/api/verify_test.go
internal/conf/configuration.go
internal/hooks/auth_hooks.go
internal/models/factor.go

Allow developers to customize access token by adding claims or altering metadata
Other affected changes:
- `generateAccessToken` is moved to a method on `API` and now takes in a `context`. In tests we use a default `context.Background()`

feat: add custom access token hook

---

internal/api/external.go
internal/models/linking_test.go

* Should be checking the prefix of the linking domain instead of matching against the whole string

fix: check linking domain prefix

---

internal/api/mfa_test.go
internal/api/settings.go
internal/api/settings_test.go
internal/api/token_test.go
internal/conf/configuration.go
internal/conf/configuration_test.go

Currently, the HookName is not properly populated which leads to improper invocation of the function. The `HookName` was not set on the global config but was set locally on hook config.
To fix this we split out `Validation` and `Population` into 2 separate steps and populate the `HookName` in `LoadGlobal`

feat: split validation and population of hook name

---

internal/api/sms_provider/textlocal.go

- Improvement to error message when there is error when sending OTP using textlocal sms provider
- Log message if error is caused by template
shows generate internal server error message
shows error from the api
This will make debugging easier, currently there is no way to find out why the api is failing

fix: show proper error message on textlocal

---

internal/api/token.go
internal/api/token_test.go

Properly bubble up the error from the HTTP hook during hte custom access token hook

fix: add error handling for hook

---

.github/workflows/release.yml
Dockerfile

Realized that too many things depend on the executable being called `gotrue` so it will be a symlink to `auth` instead.

ci: include `gotrue` symlink to `auth` in release archives, docker images

---

internal/api/password.go
internal/api/token.go
openapi.yaml

Adds the weak password check on sign in, after successfully verifying the password. Returns it as `weak_password` on the access token response.

feat: add weak password check on sign in

---

internal/api/external.go
internal/api/external_google_test.go
internal/api/external_kakao_test.go
internal/api/external_notion_test.go
internal/api/external_oauth.go
internal/api/provider/bitbucket.go
internal/api/provider/discord.go
internal/api/provider/facebook.go
internal/api/provider/figma.go
internal/api/provider/fly.go
internal/api/provider/github.go
internal/api/provider/gitlab.go
internal/api/provider/google.go
internal/api/provider/kakao.go
internal/api/provider/keycloak.go
internal/api/provider/linkedin.go
internal/api/provider/notion.go
internal/api/provider/oidc.go
internal/api/provider/slack.go
internal/api/provider/spotify.go
internal/api/provider/twitch.go
internal/api/provider/twitter.go
internal/api/provider/workos.go
internal/api/provider/zoom.go
internal/api/token_oidc.go

* Instead of returning an error in every provider if the email doesn't exist, we check if the email exists in `internalExternalProviderCallback` instead
* Setting the `Email` and `EmailVerified` claims in the `Claims` struct is redundant since we are tracking it separately in `Emails`. 
```go
type UserProvidedData struct {
Emails   []Email
Metadata *Claims
}
```
* Fix buggy oauth tests that appear to pass but they were actually returning the wrong value / wrong expected error
* This PR lays the foundation for removing the dependency on the email returned by the oauth provider

fix: handle oauth email check separately

---

internal/api/provider/azure.go
internal/api/token_oidc.go
openapi.yaml

Allows the use of Azure ID tokens with various Azure issuers, and defaults to the common issuer.

feat: azure oidc fix

---

internal/api/signup.go

Fixes #1365 
An existing user's role in `sanitizeUser` does not get sanitized and is revealed when a new user tries to signup with the same email.
The existing user's role is sanitized to an empty string to avoid revealing the information. 
Previous Behavior:
Fixed Behavior:

[#1365] Fix signUp leaking user role

---

internal/api/magic_link.go
internal/api/mail.go
internal/api/otp.go

* If `GOTRUE_PASSWORD_REQUIRED_CHARACTERS` includes symbols, it prevents users signing up via passwordless methods (magiclink / sms OTP) because those routes make an internal call to the `/signup` endpoint with a generated password.
* The generated password doesn't include symbols which will cause it to fail the character requirement check

fix: include symbols in generated password

---

.github/workflows/publish.yml

Until the repo is renamed to `auth` we can't push to ghcr.io/auth.

ci: remove push to ghcr.io/auth until repo rename

---

internal/api/mfa.go
internal/api/mfa_test.go

Swap `internalServerError` for `badRequestError` so as to allow user to make use of the status code and make adjustments

feat: return bad request error when factor with duplicate friendly name is registered

---

migrations/20221125140132_backfill_email_identity.up.sql
migrations/20221208132122_backfill_email_last_sign_in_at.up.sql
migrations/20221215195800_add_identities_email_column.up.sql
migrations/20230131181311_backfill_invite_identities.up.sql

Migrations that contain `SELECT`, `INSERT`, `UPDATE`, `DELETE` that are not already wrapped in a `DO` block, are wrapped. This is because anything that executes in a `DO` block _does not get counted as activity_ on the database.

feat: use `DO` blocks around SQL statements in migrations

---

internal/api/samlacs.go
internal/api/sso.go
internal/models/sso.go
migrations/20240115144230_remove_ip_address_from_saml_relay_state.sql

The SAML Relay State IP address check was originally introduced to increase security by guarding against man in the middle like attacks.
Unfortunately, mismatches can be quite common, especially when using a corporate network or a VPN when attempting to `signInWithSSO`.  After customer feedback and discussion, it seems like the SAMLRelayState might not add that much additional security value. Hence, we are removing the check.
We keep the IP Address field for now and can consider deprecating it in the future

feat: drop SAML RelayState IP address check

---

internal/api/mfa.go

Removes the restriction for enabling MFA on SSO accounts. It is unnecessary and an artificial limitation.

feat: remove non-SSO restriction for MFA

---

internal/models/cleanup.go

Unverified Factors are unlikely to be relevant after a 24 hour window. This PR cleans up unverified factors so they don't clog the database.
We cleanup `unverified` factors after 24 hours but this doesn't catch users who abandon the setup process midway (e.g. enroll and then leave)

feat: add cleanup of unverified factors in 24 hour window

---

internal/api/provider/provider.go
internal/api/sms_provider/twilio.go
internal/api/sms_provider/twilio_verify.go

* In the [`net/http` Do method](https://pkg.go.dev/net/http#Client.Do), if an error is returned, the http response should be ignored. Currently, we defer closing the response body which leads to a nil pointer error

fix: potential panics on error

---

.github/workflows/conventional-commits-lint.js
.github/workflows/conventional-commits.yml

Adds a linter for commits and PRs to ensure that correct structure is observed. Certain directives are not compatible with this project:
- Breaking changes are not allowed. Therefore PR titles or commit messages must not use the `!` nor the `BREAKING CHANGE` directive in descriptions or commit messages.
- The `Release-As` directive is not supported as it can break the release process.
- For cleanliness, only a few conventional commit prefixes are allowed.
These are linted using a simple JavaScript script that runs on PRs and pushes.

ci: add conventional commits linter

---

.github/workflows/release.yml
Makefile

Adds a new release process based on [release-please](https://github.com/googleapis/release-please).
As soon as this gets merged, releases will work as follows:
1. PR merges will be collected by release-please into a release PR. The team at Supabase decides when a release is ready to go out, usually weekly or bi-weekly.
2. Every PR merge (that uses `feat:` or `fix:` titles) will result in a release candidate release with tag `rc<version>`. Example: if the new release will be `2.140.0` then the RC release will be `rc2.140-rc.1`, and so on.
3. Once the release PR is merged, an official release will be published with the tag `v<version>`, or per the example `v2.140.0`.
4. Releases with a patch version of `0` get a special branch `release/v2.140.0` which can be used to patch that and only that …

ci: add new release process using release-please

---

internal/api/token_oidc.go

Message was:
```
Custom OIDC provider "" not allowed
```
And now is:
```
Custom OIDC provider "kakao" not allowed
```

fix: OIDC provider validation log message

---

.github/workflows/release.yml

Whoops. The test repo references remained in the workflow.

ci: use real repo in release workflow

---

internal/models/linking.go

* Currently, we use an `ilike` which doesn't use the index on `auth.identities.email`. Since the emails in the `verifiedEmails` slice only contains lowercased emails, and the `auth.identities.email` are also guaranteed to be lowercase, there is no need for a case-insensitive search
* The partial unique index (`users_email_partial_key`) in auth.users is defined on the condition that `is_sso_user = false`. However, the query uses `is_sso_user is false` which causes it to not use the index ever (along with `ilike`). It would be much faster to do `lower(email) = any (?)` rather than `email ilike any (?)`
* Fixes #1390

fix: improve perf in account linking

---

internal/api/provider/apple.go
internal/api/provider/oidc.go

* Apple returns either a boolean or string value in `is_private_email` which is why we need to implement our own custom unmarshaler to deal with it (https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple)

fix: unmarshal is_private_email correctly

---

.github/workflows/release.yml

The outputs of the job were not registered.

ci: fix publish step from release workflow

---

internal/api/user.go
internal/api/verify.go

* We only want to create / update the email / phone identity after it's been verified during the email change / phone change flow
* Previously, the email / phone identity was created / updated immediately after the user update endpoint is called. This results in the identity being created before it's been confirmed.

fix: only create or update the email / phone identity after it's been verified

---

.github/workflows/release.yml

Maybe it doesn't want `rc`-prefixed versions?

ci: use `RELEASE_VERSION` instead of `RELEASE_NAME` in publish step

---

.github/workflows/release.yml

If release please doesn't detect a version commit, the release name calculation should not run. IDK why that line was left like that.

ci: only calculate release versions if release please detects a version commit

---

internal/api/user.go
internal/api/verify.go

* We only want to create / update the email / phone identity after it's been verified during the email change / phone change flow
* Previously, the email / phone identity was created / updated immediately after the user update endpoint is called. This results in the identity being created before it's been confirmed.
Like #1403, but adding again.

fix: only create or update the email / phone identity after it's been verified (again)

---

.github/workflows/publish.yml

Apparently pattern is mandatory.

fix: use `pattern` for semver docker image tags

---

.github/workflows/publish.yml
Dockerfile

Publishing builds the image, but the Makefile uses `git describe --tags` for the version if the `RELEASE_VERSION` env var is not defined. And this is an issue because the `.git` directory is not included in the image (and it shouldn't be). Furthermore, the describe tags does not reflect the proper version name.

ci: add explicit release version in docker build

---

README.md
internal/api/api.go

We deprecate the existing HTTP webhook implementation to make way for Auth HTTP Hooks. We put up a deprecation notice as a warning and fully deprecate the configuration in the next release
We have webhooks but it is unused on the Supabase Auth platform
We remove webhooks in this PR and add [Standard Webhooks compliant](https://www.standardwebhooks.com/) HTTP Hooks.
We should also add a deprecation notice on the release

feat: deprecate existing webhook implementation

---

.github/workflows/publish.yml

Currently, the `Dockerfile` can't be read as the [repository might not be cloned](https://github.com/supabase/gotrue/actions/runs/7869435581/job/21468831486#step:4:42)
This PR downloads the repository to allow access to the `Dockerfile`

feat: update publish.yml checkout repository so there is access to Dockerfile

---

.github/workflows/publish.yml

We currently publish a version with  [`sha-<version`](https://hub.docker.com/r/supabase/gotrue/tags) 
This might not be intended: https://supabase.slack.com/archives/C022071RB2L/p1707820895946899?thread_ts=1707807464.786769&cid=C022071RB2L so we drop it for now

feat: drop sha hash tag

---

.github/workflows/publish.yml

Currently, our release tag is the version 2.139.0 while AIO expects a v prefix (e.g. v2.139.0). We add an additional v to adjust for that

feat: prefix release with v

---

README.md

It seems like in v2.141.0 `release-please` succeeded but there was a [likely transient](https://github.com/supabase/gotrue/actions/runs/7889273761/job/21528885508#step:7:30) failure in the build.
It seems like release-please needs to run before an image can be published. However, since release please has completed for v2.141.0 it's not possible to publish an image again since `release-please` re-runs of v2.141.0 will lead to early termination since v2.141.0 has already been published.
We publish a new version to get around this. These are some README changes to trigger the publication of a new version

feat: update README.md to trigger release

---

.github/workflows/publish.yml

Mirror Supabase Storage and use the [raw tag](https://github.com/supabase/storage/blob/master/.github/workflows/release.yml#L59C13-L59C29)
Currently, v tag [still doesn't show up](https://hub.docker.com/r/supabase/gotrue/tags)

feat: alter tag to use raw

---

internal/api/verify.go

* Fixes a bug in https://github.com/supabase/gotrue/pull/1409 where the new email is not being used in the email identity created

fix: use email change email in identity

---

internal/api/user.go
internal/api/user_test.go
internal/models/user.go

* In #1407, the update user endpoint was refactored to use `smsVerify` if `GOTRUE_SMS_AUTOCONFIRM`  is enabled. However, `smsVerify` doesn't update the user's phone number to the new one. This PR aims to fix that.

fix: update phone if autoconfirm is enabled

---

internal/models/errors.go

* `ConfirmationOrRecoveryTokenNotFoundError` should be an `IsNotFoundError`

fix: error should be an IsNotFoundError

---

.github/workflows/publish.yml
Makefile

- the healthcheck endpoint uses the `RELEASE_VERSION` value set during the CI process
- it should have a `v` prefix in the version name

ci: fix release version name

---

internal/api/token_test.go
internal/conf/configuration.go

We currently don't populate the hook name for the password verification hook.

fix: populate password verification attempt hook

---

internal/api/mfa.go

fix: restrict mfa enrollment to aal2 if verified factors are present

---

internal/api/auth_test.go
internal/api/mfa_test.go
internal/api/token.go
internal/models/refresh_token.go
internal/models/sessions.go
internal/models/sessions_test.go

First of a few refactoring PRs:
- Change `NewSession` to take in a `UserID` and `FactorID` 
- Load identities outside of AAL and AMR calculation so `CalculateAALAndAMR` doesn't touch the database.
This will help with ensuring that the transaction doesn't run for too long and aid with the Hooks Implementation.

feat: calculate aal without transaction

---

migrations/20240115144230_remove_ip_address_from_saml_relay_state.sql
migrations/20240115144230_remove_ip_address_from_saml_relay_state.up.sql

We need to have the `.up.sql` postfix for auth to detect the migration

fix: update file name so migration to Drop IP Address is applied

---

internal/api/mfa.go

Reduced version of #1438. This increases the [error correction level](https://pkg.go.dev/github.com/boombuler/barcode@v1.0.1/qr#ErrorCorrectionLevel) which should make the QR Code easier to scan
Other aspects such as visibility of QR code and potentially size adjustments will be handled for later. Want to get the minimal possible change out that might fix the issue
Works with 1Password locally, will test against Supabase setup once merged

fix: improve MFA QR Code resilience so as to support providers like 1Password

---

internal/models/sessions.go

fix: expose `provider` under `amr` in access token

---

internal/api/mfa_test.go
internal/models/sessions_test.go

Remove redundant test setup, particularly around `TestSecondarySession`. 
- Changes `generateToken` into `generateAAL1Token`
- Abstracts adding the claim and reloading a session into a single method. Was probably a mistake to add [AMREntry](https://github.com/supabase/gotrue/blob/e9f38e76d8a7b93c5c2bb0de918a9b156155f018/internal/models/sessions.go#L38). Should sync to use [AMRClaim](https://github.com/supabase/gotrue/blob/e9f38e76d8a7b93c5c2bb0de918a9b156155f018/internal/models/amr.go) at some point
- Add additional check that a provider fields must exist if there's an SSO Claim on the last entry

feat: clean up test setup in MFA tests

---

internal/api/hooks.go
internal/api/mfa.go
internal/api/token.go

When invoking a hook, if the invocation is done within an already open transaction, `invokeHook` should not try to open a new transaction. This can easily cause connection pool exhaustion and deadlock.

feat: pass transaction to `invokeHook`, fixing pool exhaustion

---

internal/api/admin.go
internal/api/anonymous.go
internal/api/api.go
internal/api/helpers.go
internal/api/invite.go
internal/api/mail.go
internal/api/mfa.go
internal/api/middleware.go
internal/api/otp.go
internal/api/recover.go
internal/api/resend.go
internal/api/signup.go
internal/api/sso.go
internal/api/ssoadmin.go
internal/api/token.go
internal/api/token_oidc.go
internal/api/token_refresh.go
internal/api/user.go
internal/api/verify.go

* Introduce a new method `retrieveRequestParams` which makes use of generics to parse a request 
* This will help to simplify parsing a request from:
```go
params := RequestParams{}
body, err := getBodyBytes(r)
if err != nil {
return nil, badRequestError("Could not read body").WithInternalError(err)
}
if err := json.Unmarshal(body, &params); err != nil {
return nil, badRequestError("Could not decode request params: %v", err)
}
```
to 
```go
params := &Request{}
err := retrieveRequestParams(req, params)
```

fix: refactor request params to use generics

---

internal/models/refresh_token.go

Use the nil instance ID so that we can leverage the compound index on instance_id and user_id when performing search and deletion
Aims to address #1449 and #1398. 
We note that `LogoutAllRefreshTokens` was marked as deprecated and may be possible  to remove if all access tokens now have a `sessionId`. Additionally, `FindTokenBySessionID` can likely be replaced  by using `FindCurrentlyActiveRefreshToken`. 
We will revisit these in a week or two but they are out of scope for this PR.

feat: use dummy instance id to improve performance on refresh token queries

---

internal/api/token.go

Reverts supabase/gotrue#1443 - on second thought I don't think it is such a good idea - benefits are also marginal

fix: revert refactor resource owner password grant

---

internal/api/external.go
internal/api/magic_link.go
internal/api/pkce.go
internal/api/recover.go
internal/api/signup.go
internal/api/sso.go
internal/api/token_test.go
internal/api/user.go
internal/api/verify_test.go
internal/models/flow_state.go

- Removes `NewFlowStateWithUserID` - it is sufficient to have one method to create a flow state
- Compresses some of the PKCE checks into a single function

feat: refactor PKCE FlowState to reduce duplicate code

---

internal/api/provider/kakao.go
internal/api/provider/oidc.go
internal/api/token_oidc.go

Adds support for OIDC login with Kakao via `signInWithIdToken()`.
Fixes:
- https://github.com/supabase/gotrue/issues/1358

feat: add kakao OIDC

---

internal/api/external.go
internal/api/magic_link.go
internal/api/pkce.go
internal/api/recover.go
internal/api/signup.go
internal/api/sso.go
internal/api/user.go

Follow up to #1446  Moves the creation of the flow state into `generateFlowState`

fix: move creation of flow state into function

---

internal/api/mfa.go
internal/api/mfa_test.go
internal/models/challenge.go

Does a few refactors:
- Create a dedicated function in tests for making authenticated request
- remove `findChallenge` as it is not used 
- rename `FindChallengeByChallengeID` to `FindChallengeByID`

fix: refactor mfa challenge and tests

---

internal/models/factor.go
internal/models/factor_test.go

Test refactor to centralise setup for `factor_test.go`. Current test suite for factor is convoluted and hard to read. Having a unified setup improves readability

fix: refactor factor_test to centralize setup

---

internal/models/cleanup.go

Code used `SessionTimebox` instead of `SessionInactivityTimeout`.

fix: cleanup panics due to bad inactivity timeout code

---

internal/api/verify.go

There is a side-channel leak whether an email exists in the system when using the `verify` endpoint. It returns `User not found` (when it doesn't) vs `Token has expired or is invalid` (when it exists).

fix: prevent user email side-channel leak on verify

---

internal/api/identity.go
internal/api/identity_test.go
internal/models/user.go

* handle removing the user's phone number when the phone identity is unlinked
* handle resetting the user's email if the email identity is unlinked
* add tests

fix: unlink identity bugs

---

internal/conf/configuration.go
internal/conf/configuration_test.go

We represent HTTP Hooks as a `|` separated list, similar to what we do with required password characters. Asymmetric keys are separated by `:` like: `v1a,whpk_mypublickey|whsk_mysecretkey:v1,whsec_mysymettrickey`
We opt for `:` and `|` as they are not part of the base64 alphabet which we use to store secrets.

feat: HTTP Hook - Add custom envconfig decoding for HTTP Hook Secrets

---

internal/api/mfa.go
internal/api/mfa_test.go
internal/conf/configuration.go
internal/models/factor.go

Currently, unverified MFA factors can build up in the database quickly. Supabase developers can toggle Maximum unverified factors ( `Maximum number of per-user MFA factors`) via the dashboard but developers will have to look for the toggle.  Developers can also call `unenroll` but it requires an additional step.
This PR proposes periodic cleanup of stale factors on each request.  A stale factor is:
- Unverified
- Has no associated Challenges 
- Older than five minutes
Why five minutes? 
- Most enrolment or verification flow should be completed within the five minute window
Factors which are unverified but have associated challenges will be cleaned up [after the developer makes successful verification](https://github.com/supabase/gotrue/blob/master/internal/api/mfa.go#L314)
Alternatives …

feat: clean up expired factors

---

internal/api/sso.go
internal/api/ssoadmin.go
internal/models/sso.go
migrations/20240314092811_add_saml_name_id_format.up.sql

Adds the ability to specify the [NameID format](https://pkg.go.dev/github.com/crewjam/saml#NameIDFormat) for a SAML SSO provider's authentication request, as some providers don't appear to support accepting the persistent format.

feat: configurable NameID format for SAML provider

---

internal/api/sso.go
internal/api/ssoadmin.go
internal/models/sso.go
migrations/20240314092811_add_saml_name_id_format.up.sql

#1481 but for 2.144.0.
Adds the ability to specify the [NameID format](https://pkg.go.dev/github.com/crewjam/saml#NameIDFormat) for a SAML SSO provider's authentication request, as some providers don't appear to support accepting the persistent format.

fix: configurable NameID format for SAML provider

---

internal/api/hooks.go
internal/conf/configuration.go
internal/conf/configuration_test.go

Splits out config changes from #1474 
- rename runHook to runPostgresHook
- Allow http with https hooks only on localhost

fix: add http support for https hooks on localhost

---

internal/api/external_figma_test.go
internal/api/external_fly_test.go
internal/api/external_github_test.go

- change "toekn" annotation for "token"
docs: fix annotation #1487 
Word "toekn"
to "token"

chore(docs): retify word toekn to token

---

internal/api/user_test.go
internal/models/user.go

Password change may mean that the user no longer trusts the actions performed by the previous "knower" of the password, so all password reset, email confirmation, phone confirmation OTPs should be reset.

fix: invalidate email, phone OTPs on password change

---

internal/api/signup.go

Resends the confirmation on duplicate Phone sign ups which haven't been confirmed.
Example scenario:
1. User Signs up with phone and password 
a. User does not verify otp
2. User signs up with phone 
a. Currently this returns an error instead of re-sending the SMS

fix: Resend SMS when duplicate SMS sign ups are made

---

CONTRIBUTING.md

A link pointing to a CODE_OF_CONDUCT.md file inside CONTRIBUTING is broken.
I removed the unnecessary brackets.

fix(docs): remove bracket on file name for broken link

---

internal/api/api.go
internal/api/external.go
internal/api/identity.go
internal/api/invite.go
internal/api/magic_link.go
internal/api/mail.go
internal/api/reauthenticate.go
internal/api/recover.go
internal/api/resend.go
internal/api/signup.go
internal/api/user.go
internal/mailer/mailer.go
internal/mailer/template.go

The overall goal of this to expose a unified interface for emails. So that we can potentially implement the Hook as a Custom Mailer. This is to ensure that the impact on the existing code flow is minimal and that we can turn off the Hook easily if needed.  
After this change, we can do something similar to:
```
mailer. := a.Mailer()
if a.config.Hook.Enabled {
mailer =   a.CustomMailer
} 
```
and have all Hook logic live  in the custom Mailer
Specific changes are:
- Removes context from mailer as it is currently unused
- pushes down mailer into respective email sending methods
- Adds remaining send methods as API methods
- Fetch OTP Length and MaxFrequency from config
- Add convenience function for checking if an email was sent within frequency limit
- push down `externalURL` and …

fix: refactor email sending functions

---

internal/api/api.go
internal/models/cleanup.go
internal/models/cleanup_test.go

* Adds a cleanup statement to delete anonymous users older than 30 days
* Runs only if anonymous sign-ins are enabled
* Move cleanup struct creation into Setup function

fix: add cleanup statement for anonymous users

---

internal/api/admin.go
internal/api/mfa_test.go
internal/api/token.go
internal/models/factor.go
internal/models/sessions.go
internal/models/sessions_test.go

Regular cleanup.
-  Merge the AAL and AMR update methods. Think this was suggested a while back but only getting to it now. 
-  Move `FindUserByFactors` to tests - a user should never need to find a user by factors. They can fetch it from the models. 
Ideally I'd remove it entirely but it's used in a few tests which will take significant time to refactor.

fix: refactor mfa and aal update methods

---

README.md
internal/api/audit_test.go
internal/api/identity_test.go
internal/api/invite_test.go
internal/api/logout_test.go
internal/api/phone_test.go
internal/api/token.go
internal/api/user_test.go
internal/api/verify_test.go

Enforces the precondition of a valid session before one can create an access token.  This supports refactors around `generateAccessToken` and  `updateMFASessionAndClaims`. Also allows for stronger guarantees within the function since one can always assume there is a valid session.
There were a few test changes:
- To mirror real world use, Access Tokens should now only exist where there is a valid session. We wrap  `generateAccessToken` into a helper `generateAccessTokenAndSession` to replace previous occurrences where session was set to nil.
- We split TestUpdatePassword into cases where reauthentication is required and reauthentication is not required. We also attach a session to two of the test cases as they were previously nil

feat: forbid generating an access token without a session

---

internal/api/mail.go
internal/api/resend.go
internal/api/resend_test.go
internal/api/signup_test.go
internal/api/verify.go
internal/api/verify_test.go
internal/mailer/mailer.go
internal/mailer/template.go

Moves the mail related refactors from #1496  into a new PR so the hook related PR is easier to review. This PR moves all EmailActionTypes to mailer package to establish an explicit link between mailer and the packages it is used in.
The changes are cosmetic and should not affect underlying functionality.

fix: move all EmailActionTypes to mailer package

---

internal/api/hooks.go
internal/api/hooks_test.go
internal/api/phone.go
internal/conf/configuration.go
internal/hooks/auth_hooks.go

We are renaming `CustomEmailProvider` to `SendEmail`. For consistency, I guess we should rename `CustomSMSProvider` to `SendSMS`. More context in #1496 
This should be fine since [the PR to add env configs for this hook](https://github.com/supabase/infrastructure/pull/17604) has not landed in prod

fix: rename from CustomSMSProvider to SendSMS

---

internal/api/hooks.go
internal/api/mail.go
internal/conf/configuration.go
internal/hooks/auth_hooks.go
internal/mailer/mailer.go

The send email hook serves as a substitute for the default email client (e.g. GoMail) across all endpoints. 
Supercedes #1496  as it was simpler to visualize the PR when starting from scratch

feat: add send email Hook

---

internal/conf/configuration.go
internal/conf/configuration_test.go

fix: add validation and proper decoding on send email hook

---

internal/api/admin.go
internal/api/logout.go
internal/models/refresh_token.go

As all access tokens should have an associated ID, we should now be able to delete the deprecated code.

fix: remove deprecated LogoutAllRefreshTokens

---

internal/api/samlassertion.go
internal/api/samlassertion_test.go
internal/models/sso.go

By adding the `"array": true` option in the JSON SAML attribute mapping document for a key, the SAML attribute(s) for that key will be represented as an array in the user identity claims.

feat: add array attribute mapping for SAML

---

internal/api/anonymous.go
internal/api/audit_test.go
internal/api/external.go
internal/api/identity_test.go
internal/api/invite_test.go
internal/api/logout_test.go
internal/api/mfa_test.go
internal/api/phone_test.go
internal/api/samlacs.go
internal/api/signup.go
internal/api/token.go
internal/api/token_oidc.go
internal/api/token_refresh.go
internal/api/user_test.go
internal/api/verify.go
internal/api/verify_test.go

In support of the use of HTTP Hook with Custom Access Token Extension Point.
We need to take in a request in order to support the Custom Access Token Hook. We use the request in the Custom access hook depends on the request to fetch the global logger.  We refactor `generateAccessToken` and a wrapping method, `issueRefreshToken`, to take in a request to support this. 
We also add a dummy request to the tests to support this change.  Supports #1528 - branched out as a separate PR so as not to bloat the main PR with peripheral changes.

feat: refactor generate accesss token to take in request

---

internal/api/provider/linkedin_oidc.go

Fixes https://github.com/supabase/auth/issues/1533
Attempting to signInWithOAuth with linkedin_iodc provider results in error 500
Attempting to signInWithOAuth with linkedin_iodc results in a successful login
Error from Supabase Auth Logs:
`oidc: id token issued by a different provider, expected \"https://www.linkedin.com\" got \"https://www.linkedin.com/oauth\"`

fix: linkedin_oidc provider error

---

internal/api/provider/linkedin_oidc.go

Reverts supabase/auth#1534
Doesn't seem to work as expected. Directly testing against the API  by calling `https://localhost:9999/?provider=linkedin_oidc will return a 404 error.

fix: revert patch for linkedin_oidc provider error

---

internal/api/provider/linkedin_oidc.go

* Linkedin introduced a breaking change by changing the issuer url in their 
discover document from `https://linkedin.com` to `https://linkedin.com/oauth` 
* Fixes #1533, #1534, [#22711](https://github.com/orgs/supabase/discussions/22711), [#22708](https://github.com/orgs/supabase/discussions/22708)

fix: update linkedin issuer url

---

internal/api/hooks.go
internal/api/hooks_test.go
internal/api/mail.go
internal/api/mfa.go
internal/api/phone.go
internal/api/phone_test.go
internal/api/token.go
internal/conf/configuration.go
internal/hooks/auth_hooks.go

After this change, users can opt to use either Postgres or HTTP functions on each extensibility/extension point. From an implementation standpoint, all  new extension points must support both HTTP and Postgres functions

feat: allow for postgres and http functions on each extensibility point

---

internal/api/hooks_test.go
internal/api/phone.go
internal/hooks/auth_hooks.go

We align convention with `SendEmail` and send over a user to avoid having the user make an additional `getUser` call.  Also allows access to `app_metadata` and `user_metadata` which would be useful for internationalization where you may want the locale of the user to determine which template to send.
We also introduce a `PhoneData` struct through which we can introduce any potential phone related fields. This struct currently lives under the `hooks` package as there is no `phone` package currently and introducing one might require a significant refactor. Importing it as as is under `api` package would cause a circular dependency between `hooks` and `api` packages.

feat: send over user in SendSMS Hook instead of UserID

---

internal/api/errorcodes.go
internal/api/provider/azure.go

Adds support for [Azure's CIAM](https://learn.microsoft.com/en-us/entra/external-id/customers/overview-customers-ciam) login. This is a special B2B Azure account separate from the typical tenant accounts and is meant to be used only when the expected issuer is set to the CIAM tenant.

feat: add support for Azure CIAM login

---

internal/api/external.go

It merges back the identity data into user metadata on link account. This is safe because the user can just sign-in again and have the identity data merged back (AccountExists case).

feat: merge provider metadata on link account

---

internal/storage/dial.go

Adds the `GOTRUE_DB_CONN_MAX_IDLE_TIME` setting that allows setting the max idle time for a connection.

fix: add db conn max idle time setting

---

.github/workflows/test.yml
Makefile
internal/api/logout.go
internal/observability/logging.go

Adds [a linter that checks for non-exhaustive `switch` statements](https://github.com/nishanths/exhaustive).

ci: add exhaustive switch statement linter

---

internal/api/errors.go

If writing to the ResponseWriter fails, then there's no point in trying to handle the error recursively and write again. Just log with a warning.
Should deal with some endless-recursion edge cases.

fix: log final writer error instead of handling

---

internal/conf/configuration.go

* Apply basic formatting on test OTPs when config is loaded
* Fixes #1566

fix: format test otps

---

internal/api/phone.go

Small quirk discovered while testing  - it currently looks like when SMS Autoconfirm is set 
```
GOTRUE_SMS_AUTOCONFIRM="true" 
```
and an OTP request is made:
```
curl -X POST http://localhost:9999/otp -H "Content-Type: application/json" -d '{"phone": "<phone>"}'
```
an OTP is still sent.  There's a substantial number projects (see internal for exact number) using this so probably will preserve  this behaviour. 
This  affects the edge case where `SMS_AUTOCONFIRM` is enabled but the Hook returns an error which may leave the developer puzzled since one might expect an SMS not to be sent with autoconfirm similar to `MAILER_AUTOCONFIRM`
Before:
- Enable Send SMS and autoconfirm, make a request with faulty URI - request should fail
After:
- Enable Send SMS and autoconfirm, make a request - …

fix: do call send sms hook when SMS autoconfirm is enabled

---

internal/api/mail.go
internal/api/phone.go
internal/api/verify.go
internal/api/verify_test.go
internal/models/errors.go
internal/models/one_time_token.go
internal/models/user.go
migrations/20240427152123_add_one_time_tokens_table.up.sql

Refactors all One-Time Tokens (OTP) used for sign-in with email, SMS, email confirmation, phone confirmation, change... to achieve:
- Performance (as current method does not use an index due to the use of [partial indexes](https://github.com/supabase/auth/blob/master/migrations/20220429102000_add_unique_idx.up.sql#L10-L14) which [cannot be used in practice](https://www.postgresql.org/docs/current/indexes-partial.html))
- Future enhancements (such as OTP verification counters, adaptive OTP lengths, etc.)
Summary of the change:
- A new `one_time_tokens` table is added which uses a double-write mechanism with `users`.
- Each new OTP is both written in the corresponding `users` column and as a new row in `one_time_tokens`.
- Lookup for an OTP hash is performed first in `one_time_tokens` and …

feat: refactor one-time tokens for performance

---

openapi.yaml

Adds the `Identity` and `is_anonymous` fields to OpenAPI spec. This is so we can use the `openapi.yml` as a sgeneral reference  from which to generate Hook Payloads, which contain `User` objects.
Identity Fields taken from the [identity model](https://github.com/supabase/auth/blob/master/internal/api/identity.go)
User objects are generated by:
1.  Converting the `openapi.yml` into JSONSchema. Currently this is done via OpenAI though a modified version of [a yml to jsonschema converter should work with modifications as well](https://www.npmjs.com/package/yaml-to-json-schema). We don't use the latter as there's an additional step of converting the output jsonschema into a format that JSON Faker can accept (adding the JSONSchema version etc)
2. Using [JSONSchema to generate a fake …

feat: update openapi spec with identity and is_anonymous fields

---

go.mod
go.sum
internal/mailer/mailer.go

* Fixes an issue where some SMTP providers reject requests when the SMTP client uses a Local Name that is identical to the SMTP Host name.

fix: use api_external_url domain as localname

---

internal/api/anonymous_test.go
internal/api/verify.go

* verifying the phone number of a user should update the `is_anonymous` field to false
* add test to prevent any future regression

fix: sms verify should update is_anonymous field

---

cmd/serve_cmd.go
go.mod
go.sum
internal/api/admin.go
internal/api/api.go
internal/api/api_test.go
internal/api/identity.go
internal/api/router.go
internal/api/ssoadmin.go
internal/observability/request-logger.go
internal/observability/request-tracing.go

* Upgrades [chi](https://github.com/go-chi/chi) from v4 to v5

feat: update chi version

---

internal/api/api.go
internal/api/middleware.go
internal/api/middleware_test.go
internal/api/verify.go
internal/api/verify_test.go

#1529 introduced timeout middleware, but it appears from working in the wild it has some race conditions that are not particularly helpful.
This PR rewrites the implementation to get rid of race conditions, at the expense of slightly higher RAM usage. It follows the implementation of `http.TimeoutHandler` closely.

feat: new timeout writer implementation

---

internal/api/saml.go
internal/conf/saml.go

Adds a SAML-specific external URL config, which allows the advertised SAML metadata to be different than the one defined with the API external URL.
This is useful in projects that use proxies or custom domains which can be very disruptive with SAML as a new connection with the IDP needs to be established. By configuring `GOTRUE_SAML_EXTERNAL_URL` to the URL before the custom domain was set up, Auth will advertise the correct metadata.

feat: add SAML specific external URL config

---

internal/api/token_oidc.go
internal/api/token_oidc_test.go

* Currently, when the "Unacceptable audience in id_token" error is returned, it doesn't log the audience claim from the id token, which makes it hard to debug. The audience claim from the id token is now logged as well when this error is returned.
* Adds a basic test for the generic id token oidc `getProvider()` method, since we currently have 0 coverage for this file
* The test also uncovered a possible nil pointer panic in the case of the generic OIDC provider being returned since in the generic case, the `oauthConfig` will be nil. Rather than returning the `oauthConfig`, we only need to return the `skipNonceCheck` property since we only check for that.

fix: improve token OIDC logging

---

internal/mailer/mailer.go

This makes the emails to be explicitly set to be HTML formatted instead of plain text which helper older clients that cannot figure this out themselves. 
Email messages are sent as plain/text. 

feat: make the email client explicity set the format to be HTML

---

.github/workflows/test.yml
Dockerfile
go.mod
go.sum

* Bump alpine version to v3.20.0 to resolve an openssl vuln
* Bump go to v1.22

chore: bump alpine and go versions

---

Dockerfile.dev

Local Dockerfile needs to use go 1.22.3 too.

ci: upgrade local dockerfile go version

---

internal/api/mail.go

feature: add max length check for email.
Currently, email length is only checked on db side. Email has max length 255 characters, when user sends (>255 characters) large email to `/admin/users` endpoint, db is doing unnecessary queries.
Code returns early if user enters large email. There will be no db queries.

feat: add max length check for email

---

migrations/20240612114525_set_search_path.up.sql

* Set search_path to empty string in all auth functions

fix: define search path in auth functions

---

.github/workflows/release.yml

See: https://github.com/supabase/ssr/pull/13/files
as per title

ci: fix doubling of rc version identifier

---

migrations/20240612123726_enable_rls_update_grants.up.sql

* Previously, users need to grant [these permissions](https://supabase.com/docs/guides/database/database-advisors?lint=0002_auth_users_exposed#security-invoker-view-with-rls-on-authusers) to create views with RLS for tables in the auth schema. 
* This also unblocks our efforts to revoke `supabase_auth_admin` membership from `postgres` to prevent cases where the `auth.schema_migrations` table is accidentally truncated by the user - causing migrations to be rerun unnecessarily.
* Bug fix, feature, docs update, ...

fix: enable rls & update grants for auth tables

---

internal/api/admin.go
internal/api/anonymous_test.go

fix: admin user update should update is_anonymous field

---

internal/api/api.go
internal/api/middleware_test.go
internal/conf/configuration.go

* Adds ip-based rate limiting on all endpoints that send OTPs either through email or phone with the config `GOTRUE_RATE_LIMIT_OTP` 
* IP-based rate limiting should always come before the shared limiter, so as to prevent the quota of the shared limiter from being consumed too quickly by the same ip-address

fix: add ip based limiter

---

internal/api/invite_test.go
internal/api/user.go
internal/api/verify.go
internal/models/user.go

Makes sure that `NULL` values in the `auth.users.encrypted_password` column are not met with SQL serialization errors.

fix: use pointer for `user.EncryptedPassword`

---

internal/api/verify_test.go
internal/models/one_time_token.go

Currently, when  `SECURE_EMAIL_CHANGE` is enabled and a dev invokes `verifyOtp({type:'email_change', token:'<some-token>', email:'<some-wrong-email>'})` an internalServerError and panic is returned. After this change a 403 is returned as expected.
This is because when an invalid `email_change` OTP is submitted [an access on  ott.UserID (which is nil) is made ](https://github.com/supabase/auth/compare/j0/prevent_panic_on_email_change?expand=1#diff-55a81f8dc53ee75ff592eec9c5e1fcb665f653d7593de7e9c8b8dadf7159fe83L258)

fix:  return proper error message when invalid email_change token is passed in

---

internal/api/verify.go

* Fixes a bug in the boolean condition where an invited user fails to have their password updated to a temporary password on invite confirmation

fix: invited users should have a temporary password generated

---

internal/api/admin.go
internal/api/admin_test.go
internal/api/token.go
internal/api/user.go
internal/api/user_test.go
internal/crypto/password.go
internal/models/user.go
internal/models/user_test.go

* Add a `password_hash` field to admin create user, which allows an admin to create a user with a given password hash (argon2 or bcrypt)
* Add an `id` field to admin create user, which allows an admin to create a user with a custom id
* To prevent someone from creating a bunch of users with a high bcrypt hashing cost, we opt to rehash the password with the default cost (10) on subsequent sign-in.
* Only plaintext passwords are allowed, which will subsequently be hashed internally
Example request using the bcrypt hash of "test":
```bash
$ curl -X POST 'http://localhost:9999/admin/users' \
-H 'Authorization: Bearer <admin_jwt>' \
-H 'Content-Type: application/json' \
-d '{"email": "foo@example.com", "password_hash": "$2y$10$SXEz2HeT8PUIGQXo9yeUIem8KzNxgG0d7o/.eGj2rj8KbRgAuRVlq"}'
``` …

feat: add `password_hash` and `id` fields to admin create user

---

internal/api/user.go

* Fixes #1629 
* Previously, rate limit errors were being returned as an internal server error, which is incorrect. This PR checks for the underlying error type returned and ensures that rate limit errors are surfaced appropriately.

fix: return proper error if sms rate limit is exceeded

---

internal/api/helpers.go
internal/api/helpers_test.go

* Fixes an issue where an empty string set as the `aud` claim will cause some methods to fail

fix: check for empty aud string

---

internal/api/user.go
internal/api/user_test.go
internal/api/verify.go

* `GOTRUE_MAILER_AUTOCONFIRM` setting should be respected in the update email flow via `PUT /user`
* When `GOTRUE_MAILER_AUTOCONFIRM=true`, updating a user's email still sends an email and requires user confirmation 
* Difficult for anonymous users to upgrade to a permanent user seamlessly without requiring email confirmation
* Fixes #1619 
* When `GOTRUE_MAILER_AUTOCONFIRM=true`, updating a user's email will not require email confirmation. 

fix: apply mailer autoconfirm config to update user email

---

internal/api/samlassertion_test.go

* Add test cases to ensure that the default attribute is respected
* If the attribute is missing, the default value in the mapping will be used
* If the attribute is present, but the mapping doesn't specify the name, then the default value will be used
* The name will always be respected over the default

chore: add default tests for saml assertions

---

internal/api/samlassertion.go
internal/api/samlassertion_test.go

* Fixes an issue where the SAML mapping is incorrect when a `Default` is specified in the mapping and the `FriendlyName` in the SAML Assertion is an empty string
* Use case-insensitive equality for mapping SAML attributes
* Tested with a trial okta account
* During the SAML assertion process, the `SAMLAttributeMapping` struct defaults the `Name` to an empty string. When combined with a SAML assertion that has an empty string set in the `FriendlyName`, this causes an incorrect mapping when a default mapping is provided. (see [test case](https://github.com/supabase/auth/pull/1654/files#diff-e708a1335880a92063e8b45f3a06eb96931ab0ee46b94cdf6bf5f566640f7a3cR247-R272)
* Use case-sensitive equality for mapping SAML attributes
Feel free to include screenshots …

fix: omit empty string from name & use case-insensitive equality for comparing SAML attributes

---

internal/api/auth.go
internal/api/auth_test.go

* Improve logging for missing session
* Helps provide better visibility for missing session errors encountered in https://github.com/orgs/supabase/discussions/23715

fix: improve session error logging

---

internal/api/token.go
internal/hooks/auth_hooks.go

* serializes the jwt as a string rather than a slice of strings

fix: serialize jwt as string

---

internal/api/token.go
internal/models/user.go

`Authenticate` should treat empty string as nil, as both mean the same thing.

fix: treat empty string as nil in `encrypted_password`

---

internal/api/ssoadmin.go

* when the `attribute_mapping` key is not provided in the payload, the update should not delete the existing attribute mapping

fix: don't update attribute mapping if nil

---

internal/models/sso.go

* `Default` field in SAMLAttribute uses an `interface{}` type which requires using deep equality for comparisons 

fix: use deep equal

---

internal/api/user.go
internal/api/user_test.go

* Restricts auto-confirmation of emails on email change to anonymous users only
* Permanent users will still need to verify the email change request regardless of whether auto-confirmation is enabled or not
* This bug was introduced in #1646

fix: restrict autoconfirm email change to anonymous users

---

internal/api/hooks.go
internal/api/hooks_test.go
internal/api/mail.go
internal/api/mfa.go
internal/api/phone.go
internal/api/token.go

Adds a log entry when hooks run. Also refactors the `invokeHook` API to not require redundant parameters like the URI.

feat: add hook log entry with `run_hook` action

---

internal/api/token.go
internal/conf/configuration.go

* Use the original value of `GOTRUE_JWT_SECRET` - no need to check for base64 decoding.
* Don't include the kid claim if the kid is an empty string

fix: maintain backward compatibility for asymmetric JWTs

---

internal/api/admin_test.go
internal/api/mfa.go
internal/api/mfa_test.go
internal/models/factor.go
internal/models/factor_test.go

- Split `NewFactor` into `NewPhoneFactor()` and `NewTOTPFactor()`. 
- All `New<Type>Factor` methods will now create unverified factors.
- Additionally, also guards the `Challenge` endpoint when verification is disabled for a factor.
The hope is to reduce cognitive load and the chance of creating a factor in an undesired state
Should one wish to obtain a Verified Factor (say for tests) they can call `UpdateStatus`. It is unlikely for this to be a common use case though.
Someone might have brought this up prior but only getting to it now

fix: MFA NewFactor to default to creating unverfied factors

---

migrations/20240729123726_add_mfa_phone_config.up.sql

- Add `if not exists` so the migration is idempotent
- Also drops the partial unique constraint on phone factors to avoid potential database bloat

fix: update mfa phone migration to be idempotent

---

internal/api/mfa.go
internal/conf/configuration.go

`GOTRUE_MFA_ENABLED` used to control whether TOTP enroll and verify were on, but with #1668 this config option was disregarded, meaning that TOTP will stop working for already configured projects.

fix: treat `GOTRUE_MFA_ENABLED` as meaning TOTP enabled on enroll and verify

---

openapi.yaml

Complement to #1668 
Add OpenAPI specification for MFA (Phone). In particular, updates the parameters and `/enroll` `/challenge` and `/verify`

fix: update openapi spec for MFA (Phone) 

---

internal/api/api.go

fix: expose `X-Supabase-Api-Version` header in CORS

---

internal/api/mfa.go

Refactors TOTP, Challenge, Enroll, and Verify into separate branches for consistency with other methods and also readability.
Adds an additional check to ensure a user must own a factor in order to challenge it.

fix: refactor TOTP MFA into separate methods

---

internal/api/errorcodes.go
internal/api/hooks.go

* Not all responses are gonna contain the `Content-Length` header. According to the HTTP/2 spec, it is not required to return the content-length header in the response. If the "Transfer Encoding" is chunked, the content-length header will also not be present as the response is sent in chunks and the content-length is unknown initially.

fix: remove check for content-length

---

internal/api/hooks.go
internal/api/hooks_test.go
internal/api/mfa.go
internal/api/mfa_test.go
internal/api/otp.go
internal/api/phone.go
internal/api/phone_test.go
internal/api/reauthenticate.go
internal/api/resend.go
internal/api/signup.go
internal/api/sms_provider/sms_provider.go
internal/api/user.go

* Resolves issue where the custom SMS hook cannot be used unless a SMS provider is configured by moving `GetSmsProvider` into `sendPhoneConfirmation` and only calls it if the hook is not enabled.
* Allows `channel` to be set for MFA (phone) if hook is enabled 
* It's not possible to set up a hook without adding config for a SMS provider

fix: allow enabling sms hook without setting up sms provider

---

internal/api/mfa.go
internal/api/settings.go
internal/conf/configuration.go

The `MFA_ENABLED` config is deprecated and not in active use.

fix: drop the MFA_ENABLED config

---

internal/api/mfa_test.go

Refactors the tests and removes FindFactorsByUser. There shouldn't be a need to call it as it's possible to directly load the Factors.
We note that there is significant opportunity for refactoring [in this test](https://github.com/supabase/auth/pull/1707/files#diff-776a4afc31ddc19c68d15827910389a0f2598c3351ec1df5495344d3e286c36cL309) this will be done later in the week  in the interest of time

fix: remove FindFactorsByUser

---

internal/api/errorcodes.go
internal/api/mfa.go
internal/api/mfa_test.go
internal/models/factor.go

With this change:
- Multiple verified phone mfa factors can exist so long as they have distinct phone numbers (see discussion below)
- Enrolling a factor with a number that is the same as the existing verified factor will result in a 422 status code
- Enrolling a factor with a number that is the same as another existing unverified factor will result in the deletion of the older factor.
Also includes:
- A refactor to check for duplicate constraints at application level then at the Postgres layer.
- A narrowing of deletion so that only unverified factors of the same type are deleted upon first successful verification
Follow up to #1687 to support the unique constraint on phone factors.

fix: enforce uniqueness on verified phone numbers 

---

internal/api/mfa.go
internal/api/mfa_test.go

Expose factor type on challenge so that developers can know whether it is a phone or TOTP factor they have challenged and redirect to appropriate page or perform relevant action
Also helps us distinguish between the two so we can prevent unintended behaviour (e.g. the use of `challengeAndVerify` with a phone factor)
As typescript follow structural typing I think addition of a new field should be fine. We will test this before proceeding. However, putting it out there first for early review or consideration
Update - tested and should be fine

fix: expose factor type on challenge

---

internal/api/hooks_test.go
internal/hooks/auth_hooks.go

* Remove unused "Success" field in the hook outputs for "Send SMS" and "Send Email" 

chore: remove unused hook outputs

---

internal/api/mfa.go

Make TOTPObject a pointer so that it is not returned in the case of an `EnrollResponse` for phone

fix: remove TOTP field for phone enroll response

---

internal/api/errorcodes.go
internal/api/mfa.go
internal/api/token.go
internal/conf/configuration.go

* Add error codes to the password login flow, which fixes #1631 
* Most errors in the password login flow are returned as `oauthError`, which doesn't have support for an error code as the struct conforms to the [oauth error response](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2) specified in the RFC
* Errors which were previously returned as an `oauthError` struct now return `badRequestError` instead with the following error code `invalid_login_credentials`
* In certain cases, we can return existing error codes like `ErrorCodeUserBanned`, `ErrorCodeEmailNotConfirmed`, `ErrorCodePhoneNotConfirmed` or `ErrorCodeValidationFailed`
* Some error messages are updated to provide more clarity on the underlying error
Add …

fix: add error codes to password login flow

---

internal/api/api.go
internal/api/external.go
internal/api/external_oauth.go
internal/api/external_test.go
internal/api/samlacs.go

* Currently, invalid state errors on the oauth callback endpoint are returned as json responses - this makes error handling impossible for the client since the callback is invoked by the oauth provider and leaves users with an unfriendly error message.
* This PR aims to address this by redirecting errors to the Site URL. We can't redirect errors to the redirect url specified in the `state` because the `state` might not be verified yet, which may lead to malicious redirects.
* This changes the response for these type of errors to redirect to the site URL instead of failing at the `/callback` endpoint.

fix: redirect invalid state errors to site url

---

openapi.yaml

Bug fix
A valid provider name gets invalidated.
A possible valid provider name gets verified by regex correctly.
`[^a]+` -> This regex will match any char except character `a`
`^a$` -> This regex will match string have single char `a`
`^[a-zA-Z0-9]+$` -> This regex will match any alphanumeric string. `^` denotes start of string and `$` denotes end of string.
This pull request will address https://github.com/supabase/auth/issues/1719

updated regex for provider name

---

internal/api/external.go
internal/api/provider/oidc.go
internal/api/provider/vercel_marketplace.go
internal/api/token_oidc.go
internal/conf/configuration.go

- adds Vercel marketplace provider

feat: Vercel marketplace OIDC

---

internal/api/external.go
internal/api/jwks.go
internal/api/token.go

* OAuth state is now signed with the same JWK that is used to sign the access tokens 
* currently, it's weird for the `GOTRUE_JWT_SECRET` to be set (other than it being a fallback option) just for the sake of signing the oauth state

fix: use signing jwk to sign oauth state

---

internal/api/external.go

* When the oauth user is first created, the identity needs to be returned in the user object as well. 

fix: return oauth identity when user is created

---

internal/api/anonymous_test.go
internal/api/user.go

* fixes https://github.com/supabase/auth/issues/1671
* allows an anonymous user to update their password when linking an email or phone identity (through update user)
* an anonymous cannot update their password unless they confirm their email first - this is not ideal since it requires the anonymous user to verify the email first before adding a password to their account
* An anonymous user remains anonymous until they have confirmed the email / phone added

fix: allow anonymous user to update password

---

example.env
internal/api/anonymous.go
internal/api/auth.go
internal/api/external.go
internal/api/logout.go
internal/api/logout_test.go
internal/api/mfa.go
internal/api/middleware.go
internal/api/samlacs.go
internal/api/signup.go
internal/api/token.go
internal/api/token_refresh.go
internal/api/verify.go
internal/conf/configuration.go

Remove set cookie tokens and clear cookie token methods as it looks like they aren't done server side. 
Task: https://www.notion.so/supabase/team-auth-113cb19144c1419ea5fb1d600281d959?p=ff083dad758e44ef9b4e230804e0fee7&pm=s

fix: remove server side cookie token methods

---

internal/conf/configuration.go

The HookName is generated from the Postgres URI and used internally to invoke the hook.
Context: https://github.com/supabase/auth/issues/1734#issuecomment-2308342232
Since it's for internal use, we don't expose it similar to what we do with [encryption key](https://github.com/supabase/auth/compare/j0/hide_hook_name?expand=1#diff-4c28cb40881781a1067b3b3681c43f805dab629f31f3c7614b0f781ffa096505L457) and other similar fields.
This is fine since we don't marshal the extensibility point.
We don't marshal the struct so it should be fine but for additional sanity check ran this locally:
```
GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_ENABLED="true"
GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_URI="pg-functions://postgres/public/custom_access_token_hook"
```
```
create or replace function …
```

fix: hide hook name

---

internal/api/context.go
internal/api/external.go
internal/api/identity.go
internal/api/invite.go
internal/api/magic_link.go
internal/api/mail.go
internal/api/middleware.go
internal/api/middleware_test.go
internal/api/phone.go
internal/api/reauthenticate.go
internal/api/recover.go
internal/api/resend.go
internal/api/signup.go
internal/api/user.go
internal/mailer/mailer.go

* Fixes https://github.com/supabase/auth/issues/1236
* Reduces the number of false positives arising from validation errors when counting rate limits for emails / sms sent
* This change applies the shared rate limiter for email and phone functions before the actual email / sms is being sent out rather than at the start of the request
* The `limitEmailOrPhoneSentHandler()` now initialises the rate limiters and sets it in the request context so we can subsequently retrieve it right before the email / sms is sent

fix: apply shared limiters before email / sms is sent

---

internal/api/saml.go
internal/conf/saml.go

By setting the `GOTRUE_SAML_ALLOW_ENCRYPTED_ASSERTIONS` to `true` the SAML private key will be advertised as usable with encryption too.
Encrypted assertions are fairly rare these days because:
- They make it very hard to debug what's going on.
- HTTPS is the default protocol on the web for over 10 years, including in intranets.
**Why not use a separate key?**
The underlying library [does not support it](https://pkg.go.dev/github.com/crewjam/saml@v0.4.14/samlsp#Options) and there are no significant cryptological issues using the same RSA key for signatures and encryption, especially in a limited setting like this.

feat: add support for saml encrypted assertions

---

internal/api/magic_link.go
internal/conf/configuration.go

Adds an option to disable magic links, as they are more prone to email sending abuse than other email authentication methods.

feat: add option to disable magic links

---

internal/api/admin.go
internal/api/errorcodes.go
internal/api/invite.go
internal/api/magic_link.go
internal/api/mail.go
internal/api/mail_test.go
internal/api/otp.go
internal/api/recover.go
internal/api/resend.go
internal/api/signup.go
internal/api/user.go
internal/api/verify.go
internal/api/verify_test.go
internal/conf/configuration.go

Adds support for authorized email addresses, useful when needing to restrict email sending to a handful of email addresses. In the Supabase platform use case, this can be used to allow sending of emails on new projects only to the project's owners or developers, reducing email abuse.
To enable it, specify `GOTRUE_EXTERNAL_EMAIL_AUTHORIZED_ADDRESSES` as a comma-delimited string of email addresses. The addresses should be lowercased and without labels.
Labels are supported so emails will be sent to `someone+test1@gmail.com` and `someone+test2@gmail.com` if and only if the `someone@gmail.com` address is added in the authorized list.
Not a substitute for blocklists!

feat: add authorized email address support

---

internal/api/cleanup.go
internal/observability/cleanup.go
internal/utilities/context.go

Deduplicate the `WaitForCleanup` function into one under `utilities`.

fix: simplify WaitForCleanup

---

internal/api/signup.go

The `sanitizeUser` function did not cleanup the **EmailChange** and **EmailChangeSentAt** properties on a User. If a User had a pending email address change, the new address could be leaked via a crafted `signUp` request.

fix: user sanitization should clean up email change info too

---

internal/api/verify.go
internal/crypto/crypto.go
internal/crypto/password.go
internal/models/audit_log_entry.go
internal/models/cleanup.go
internal/models/user.go

Fix to gosec warnings so builds can complete.
The gosec checks are halting builds.
The gosec checks are passing.
I didn't see any warnings that led to real vulnerabilities / security issues.
That said long term it may be worth adding some defensive bounds checks for a couple of the integer overflow warnings, just to future proof us age the code ages. Given that we allow supabase users to write to the database, not sure we can guarantee a user doesn't provide a bring-your-own-hash singup flow or something like that. Unbound allocations are a prime target for DoS attacks.
For the nonce issues, neither is was real issue. Open is not "fixable, see gosec issue [#1211](https://github.com/securego/gosec/issues/1211). For Seal I tried:
```
nonce := make([]byte, cipher.NonceSize())
if _, err := …
```

chore: fix gosec warnings via ignore annotations in comments

---

internal/api/mail.go

Fix #1744  by introducing the token to the Auth Hook payload for Send Email. The tokenHash seems to be already present.
Currently, it's passed into the function as `otpNew`. Though it is indeed the OTP needed to validate the new email address we place it in  the `token` field to maintain the convention that `token_hash_new` is only populated when secure email change is enabled
New output structure:

fix: add token to hook payload for non-secure email change

---

internal/api/mfa_test.go
internal/api/user.go
internal/models/user.go

If a user has verified factors (mfa enabled) we should require an AAL2 session in order to proceed with any operation
We restrict phone, email, and password from updates as we consider those as sensitive fields
Context: https://supabase.slack.com/archives/C02AK9166FR/p1725466764804889

fix: update aal requirements to update user

---

internal/api/errors.go
internal/observability/request-logger.go

Adds the `x-sb-error-code` header to non-2XX responses if the error has an error code determined. This is picked up by the request logger which includes it in the request completed log.
Furthermore, the same header can be picked up by the API gateway (Supabase world) without having to parse the response to include the error code in request logs too.

feat: add `x-sb-error-code` header, show error code in logs

---

internal/crypto/password.go
internal/crypto/password_test.go
internal/models/user.go
internal/models/user_test.go

Fix #1750. Firebase uses a [modified version of scrypt](https://github.com/firebase/scrypt) We add support for Firebase Scrypt hashes so that developers can move over from Firebase (or similar) without the obligation to force a password reset for all users.
As there is no pre-defined convention for Firebase scrypt hashes, we establish the following:
```
$fbscrypt$v=1,n=<N>,r=<r>,p=<p>[,ss=<salt_separator>][,sk=<signer_key>]$<salt>$<hash>
```
```
$fbscrypt: Firebase scrypt Identifier
$v: version identifier. Intended to allow for flexibility in parameters used.
$n: N is the CPU/memory cost parameter.
$r: block size
$p: parallelization
$ss: salt seperator, optional, only if using firebase,  base64-encoded string used to separate the salt from other parameters.
$sk: signer key, a …
```

feat: add support for migration of firebase scrypt passwords

---

internal/api/api.go
internal/api/helpers.go
internal/api/mail.go
internal/api/mail_test.go
internal/api/middleware.go
internal/api/middleware_test.go

* Move the email restriction validation to the middleware rather than doing it in the `validateEmail` function
* Excludes requests made to the `/admin` endpoints and any `GET` and `DELETE` requests

fix: apply authorized email restriction to non-admin routes

---

internal/api/middleware.go
internal/api/middleware_test.go

* Allow requests to skip check for authorized email addresses for /token and /verify endpoints

fix: bypass check for token & verify endpoints

---

.github/workflows/release.yml

[Support for Go 1.21 has ended](https://endoflife.date/go). Also for certainty that we don't have cases where the CI build passes (v1.21) but doesn't work with 1.22. 
Setup Go v4 and v3 [seem to use node16](https://github.com/actions/setup-go) and supported has ended for that so decided to upgrade

fix: upgrade ci Go version

---

openapi.yaml

As per title, internal context: https://supabase.slack.com/archives/C03S3SW9485/p1727274238768729

ci: update openapi spec for saml and generate_link

---

internal/api/mfa.go
internal/api/mfa_test.go
internal/models/factor.go

We make the following changes:
- Move all checks for factor validation into a single function. This ensures that we can re-use it across methods so we don't miss checks
- Removes un-used functions
- For MFA (TOTP) changes the duplicate friendly name from one that is done at the database level to one that is done at the application level. This aligns with MFA (Phone)

fix: refactor mfa validation into functions

---

internal/api/mail.go
internal/api/mail_test.go
internal/api/verify_test.go

* `validateEmail` should normalise emails

fix: validateEmail should normalise emails

---

internal/storage/dial.go

`getExcludedColumns` allocates a slice of a particular length instead of capacity, which does not achieve the intended effect -- memory optimization.

fix: fix `getExcludedColumns` slice allocation

---

internal/api/middleware_test.go

Fix reqPath for verify check bypass test
We are experiencing lot of 403 responses from /v1/verify EP. Supabase is returning "invalid or expired OTP". Correcting this test maybe will raise the cause of our problems. I did not setup the project on my machine, someone can run the test and check if it passes also on verify EP?
Test is correct.

fix: Fix reqPath for bypass check for verify EP

---

internal/mailer/mailer.go
internal/mailer/mailme.go

The previously forked [`github.com/supabase/mailme`](https://github.com/supabase/mailme) package is inlined for easy development and changes.

fix: inline mailme package for easy development

---

internal/conf/configuration.go
internal/mailer/mailer.go

The code here is misleading. The `mail` variable is only used to format a From address, not used at all after that.

fix: email header setting no longer misleading

---

internal/conf/configuration.go
internal/mailer/mailme.go
internal/mailer/noop.go
internal/mailer/template.go
internal/mailer/template_test.go

Adds support for additional and configurable email message headers. Set the `GOTRUE_SMTP_HEADERS` value to a JSON object of the shape (TypeScript notation) 
```
{ [header: string]: string[] }
```
Use the special string `$messageType` in the value portion to identify the message type being sent (for now: `invite`, `confirm`, `reauthenticate`, `email_change`, `recovery`, `magiclink`, `other`).
To use this with [AWS SES Feedback-ID](https://aws.amazon.com/about-aws/whats-new/2024/06/amazon-ses-custom-values-feedback-header/) one way to do it would be to [set SES SMTP message tags](https://docs.aws.amazon.com/ses/latest/dg/event-publishing-send-email.html#event-publishing-using-ses-headers):
```
GOTRUE_SMTP_HEADERS={"x-ses-message-tags": …
```

feat: add mail header support via `GOTRUE_SMTP_HEADERS` with `$messageType`

---

internal/api/mail_test.go
internal/api/middleware.go
internal/api/middleware_test.go
internal/conf/configuration.go

Adds a new config option `GOTRUE_MAILER_EXTERNAL_HOSTS` that serves as an allowlist to all the acceptable hosts provided to the APIs.
Fixes #1228

fix: external host validation

---

internal/api/mail.go
internal/api/phone.go

* https://github.com/supabase/auth/pull/1800 introduced a bug which applied the rate limiting setting even if `AUTOCONFIRM` was enabled. Although this is unintended, it is a breaking change so we need to give users time to update their rate limit settings before applying it

fix: ignore rate limits for autoconfirm

---

internal/api/middleware.go

Returns HTTP 400 with the validation failed error code if the request body sent to the server when CAPTCHA verification is enabled was not JSON or couldn't be parsed into JSON.

feat: return validation failed error if captcha request was not json

---

migrations/20240806073726_drop_uniqueness_constraint_on_phone.up.sql

* Fixes an issue where `20240806073726_drop_uniqueness_constraint_on_phone.up.sql` is not idempotent when the `schema_migrations` table is truncated because `20240729123726_add_mfa_phone_config.up.sql` would have recreated the `unique_verified_phone_factor` index. This causes both indexes (`unique_verified_phone_factor` and `unique_phone_factor_per_user`) to be present resulting in the later migration (which renames the index) to fail.

fix: make drop_uniqueness_constraint_on_phone idempotent

---

internal/api/admin.go
internal/api/helpers.go
internal/api/middleware.go
internal/security/captcha.go

* Move the reading the requestBody into the captcha middleware, which is in the api package so it can use `retrieveRequestParams` 
* Use `retrieveRequestParams` in the admin delete route

chore: use retrieveRequestParams where possible

---

internal/api/hooks.go

* HTTP hooks that return status codes outside of the accepted status codes will cause Auth to return an obscure error message that is hard to debug: `Error executing Hook` - this change is an attempt to improve the error messaging to reflect the status code being rejected

fix: improve error messaging for http hooks

---

internal/api/token_refresh.go
internal/models/user.go

* Prior to the `auth.sessions` table being created, some refresh tokens can contain a null `session_id`. In those cases, attempting to use those refresh tokens to obtain a new session will result in a panic. 
* This PR creates a new session for those refresh tokens that do not have a `session_id` to prevent panics from happening.

fix: possible panic if refresh token has a null session_id

---

internal/models/factor.go

Use appropriate column name for Web Authn verification - it's fine to change this as it's currently behind the feature flags `MFA_WEB_AUTHN_*_ENABLED` and should have never been used.

fix: correct web authn aaguid column naming

---

internal/api/ratelimits_test.go
internal/conf/rate_test.go

Verify that rate limits such as "0/1h", "0/24h" work as intended. This is a tests only change to ensure this behavior is preserved in the future.

fix: add test coverage for rate limits with 0 permitted events

---

internal/api/external_figma_test.go
internal/api/provider/figma.go

Closes #1827 by defaulting to `files:read` oAuth scope for Figma as per the issue.

fix: default to files:read scope for Figma provider

---

internal/api/mail.go
internal/conf/configuration_test.go

This does not fix lower restrictions from being bypassed, but does help in the case the rate limit is explicitly set to 0.

fix: rate limits of 0 take precedence over MAILER_AUTO_CONFIRM

---

internal/api/mfa.go

Response to an internal ticket, IP mismatch can show up when authenticating  as well which might be confusing for users

fix: update ip mismatch error message

---

internal/api/external.go
internal/api/verify.go
internal/api/verify_test.go

* Return the error code for in the redirect URL instead of the status code

fix: return the error code instead of status code

---

migrations/20240427152123_add_one_time_tokens_table.up.sql

Edits an existing migration to fallback onto btree indexes when hash indexes are unavailable.
This change allows auth to be compatible with the orioledb storage engine. At time of writing orioledb only support btree indexes. That issue is expected to be addressed by the end of Q1 - 2025. Once that support is added, both heap and orioledb projects will both use the code path for hash indexes. hash indexes are preferred because they are [safer from timing attacks](https://dba.stackexchange.com/questions/285739/prevent-timing-attacks-in-postgres)
A reminder has been set for May 1st for us to
- remove the fork in this migration
- identify and update the index type (from btree to hash) on any orioledb-alpha projects that are still in existence

fix: fallback on btree indexes when hash is unavailable

---

internal/api/errorcodes.go
internal/api/mail.go
internal/conf/configuration.go
internal/conf/configuration_test.go
internal/mailer/mailer.go
internal/mailer/mailme.go
internal/mailer/noop.go
internal/mailer/template.go
internal/mailer/validate.go
internal/mailer/validate_test.go

The goal is to only return an error when we have a very high confidence the email won't be deliverable.
This is currently going to be added as a draft for the team to review. I haven't actually implemented any paths that call this or configuration around when it is activated.

feat: add email validation function to lower bounce rates

---

internal/conf/configuration.go
internal/mailer/validate.go

* Request made to email validation service should be a `POST`
* Update error message when config validation fails

fix: allow setting the mailer service headers as strings

---

internal/api/verify.go
internal/api/verify_test.go
internal/models/user.go

* Addresses https://github.com/supabase/auth/issues/1620

fix: email_verified field not being updated on signup confirmation

---

internal/api/token_oidc.go

Placeholder solution.
Need to:

fix: handle user banned error code

---

CHANGELOG.md
internal/conf/configuration.go
internal/mailer/validate.go

This merges a small release hotfix committed into the releases branch back into master.

chore: merge release/2.165.0 into master

---

.github/workflows/release.yml

Because 2.165.1 was incorrectly made over the release/2.165.0 branch (should have just been a PR to master as 2.165.0 was the latest version) that version number is taken. Now master needs an explicit `Release-As` directive.
Release-As: 2.165.2

chore: release as 2.165.2, switch to googleapis/release-please-action

---

.github/workflows/release.yml

Make a new version as 2.165.1 can't be released.

feat: switch to googleapis/release-please-action, bump to 2.166.0

---

internal/crypto/password.go
internal/crypto/password_test.go

Argon2 parsing and comparison is broken in multiple ways:
1. Incorrect comparison being done using `ConstantTimeCompare`. This Go API is awful as it returns 1 on _equality_ (unlike all other comparison APIs that return 0) so it was missed.
2. All Argon2 comparisons were producing incorrect derived keys due to the multiplication by 1024. The `argon2.Key` and `IDKey` accept *KiB* as arguments (not bytes!) which caused all hashes to always be incorrect.
Tests didn't catch this as they only tested for the positive case (which passed with flying colors).

feat: fix argon2 parsing and comparison

---

README.md

Coverage is higher, but it's showing the coverage of the old repo.

docs: change coveralls image in README

---

.github/workflows/test.yml

The `-coverpkg` option changed in Go 1.20 and now includes files not under test, which skew the actual coverage.
Files not under test:
- `/cmd` The commands, these run as part of the executable.
- `/client` A non-official admin client that should be removed from the repo in the next major version.
- `/docs` Will be removed in a follow up PR.
- `/main.go` Main file.

ci: fix coverage metering by removing files not under test

---

Dockerfile

Using `alpine:3` means we don't have to worry about updating the base image often, it'll just use whatever latest.

ci: use `alpine:3` as base image

---

CONTRIBUTING.md

Docs update: Add macOS installation instructions to the CONTRIBUTING.md file. Fixes #1685.
The current CONTRIBUTING.md does not include specific installation instructions, which may lead to confusion during setup.
This PR updates outdated instructions in the CONTRIBUTING.md file. ensuring a smoother setup experience for contributors.

docs: update CONTRIBUTING.md for macOS installation instructions

---

internal/api/verify.go

A fix for #1899 undoing changes in #1868.

feat: set `email_verified` to true on all identities with the verified email

---

.github/workflows/publish.yml

Docker images are built with the `vunspecified` version, which comes because the release step does not use the current [Git context of the buildx action](https://github.com/docker/build-push-action?tab=readme-ov-file#git-context):
> Be careful because any file mutation in the steps that precede the build step will be ignored, including processing of the .dockerignore file since the context is based on the Git reference. However, you can use the [Path context](https://github.com/docker/build-push-action?tab=readme-ov-file#path-context) using the [context input](https://github.com/docker/build-push-action?tab=readme-ov-file#inputs) alongside the [actions/checkout](https://github.com/actions/checkout/) action to remove this restriction.

ci: fix unspecified version at runtime in docker images

---

openapi.yaml

fix: update OpenAPI schema to use 'minimum' instead of 'min' for integer validation
ref:https://swagger.io/docs/specification/v3_0/data-models/data-types/#numbers:~:text=2-,minimum,-%3A%201

docs: update OpenAPI schema to use 'minimum' instead of 'min' for integer validation

---

Makefile
hack/coverage.sh
internal/api/hooks.go
internal/api/magic_link.go
internal/api/mail.go
internal/api/mfa.go
internal/api/mfa_test.go
internal/api/phone.go
internal/crypto/crypto.go
internal/crypto/crypto_test.go
internal/crypto/password.go
internal/crypto/password_test.go
internal/crypto/utils.go
internal/crypto/utils_test.go

Covers a 100% of the `crypto` package with tests.

feat: cover 100% of crypto with tests

---

.github/workflows/dogfooding.yml

Adds a dogfooding check on release, i.e. making sure that the RC version being released has already been out on Supabase production & staging.
It works by adding a mandatory dogfooding check on every PR. If the PR is one for Release Please, upon giving approval to merge, the check will re-run ensuring that the latest RC is in fact deployed. If it is not, the check will fail, blocking the merge.

ci: introduce dogfooding check on release

---

README.md

docs
Commit 1a52eb6e3aaa5a2331bab2cf233856fa6f6015d8 moved `api.go` to `internal`, without updating all references.
This PR adjusts sources to changes.

docs: update `api.go` reference

---

README.md

docs: update README to correct code snippets and add resend OTP endpoint. fix #1711

docs: update README to correct code snippets and add resend OTP endpoint

---

CHANGELOG.md
internal/api/errors.go

* Improve error message around invalid channel error for phone auth. Only twilio and twilio verify support whatsapp as a valid channel.

fix: improve invalid channel error message returned

---

internal/api/samlacs.go

* Logs the `Response` returned from the library as well

fix: improve saml assertion logging

---

Makefile

chore: support both `docker compose` or `docker-compose` command
no issue link
before this commit, dev can have error if install docker-compose as plugin. After this commit, dev can run `make docker-x` without errros
no

chore: alias to docker compose command

---

internal/models/one_time_token.go

* `POST /verify` fails for email change when PKCE is used and `GOTRUE_MAILER_SECURE_EMAIL_CHANGE_ENABLED` is enabled because the query to retrieve the token returns an error if the token is not found instead of trying again with the `pkce_` prefix

fix: ignore not found error to check for pkce prefix later

---

README.md

This PR is to update `README` to use better syntax for `json` code block.
Some of `json` code blocks aren't valid json format, e.g it shows comments in red:
Use `js` syntax for `json` code block for better looking.
N/A

docs: update README to use better syntax for `json` code block

---

cmd/serve_cmd.go

* Enables `SO_REUSEPORT` which allows multiple sockets to bind to the same address and port - this is useful when the auth service needs to be restarted and the port is still being held by a reverse proxy (i.e. envoy) until all the connections are drained

fix: enable SO_REUSEPORT in listener config

---

.github/workflows/test.yml
Dockerfile
Dockerfile.dev
cmd/serve_cmd.go
go.mod

* Use `syscall.SO_REUSEPORT` instead of hardcoding the syscall to deal with cases where it's not supported
* Upgrade go to version 1.23.7

fix: use sys/unix instead of syscall

---

.github/workflows/release.yml

* Force the release ci to use 1.23.7 - for some reason, the gh runner cache only contains 1.23.6

chore: use go 1.23.7

---

cmd/serve_cmd.go
internal/reloader/reloader.go
internal/reloader/reloader_test.go

This change will prevent an invalid config directory from shutting down the auth server. To prevent spamming the logs we wait for the reloadInterval between each attempt to check the config dir.

feat: allow invalid config directories

---

internal/models/user.go

Propagate errors that occur when calling tx.UpdateOnly in internal/models/user.go:ConfirmPhone.
Previously this line returned nil:
https://github.com/supabase/auth/blob/097f01f39fa79d5e8e4e9c399a14e14405e3a142/internal/models/user.go#L471
Meaning that the next call to ClearAllOneTimeTokensForUser was ran even when the confirmation token could not be updated.
https://github.com/supabase/auth/blob/master/internal/models/one_time_token.go#L119

fix: propagate error when when confirming phone

---

internal/utilities/request.go
internal/utilities/request_test.go

Redirect URL was not being sanitized (query and fragment not being stripped) before being pattern matched on the allowed URL globs. This made it possible in some cases to produce an insecure redirect.

fix: sanitize redirect URL (remove fragment, query) before pattern matching

---

internal/conf/configuration.go
internal/mailer/validate.go
internal/mailer/validate_test.go

Feature that gives configuration option to block an email address event if the mx server of the domain is on a blocklist
Existing behavior only checks for syntax issues and single email addresses against a message stream.
This is called on every sent email event, the mx server of the email addresses domain is queried and checked against a hard-coded blocklist
Functionality to allow for the long term blocking of bot and spam behavior.
Resolves SEC-245

feat: Block specific outgoing mail servers

---

.github/workflows/conventional-commits.yml
.github/workflows/dogfooding.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/test.yml

Found nothing vulnerable found in actions, just tightening up the permissions across all our publicly facing repos.
Not clear why pull_request_target is being used. Ready to revert if needed

fix: explicit permisions on actions

---

internal/api/api.go
internal/api/middleware.go
internal/api/options.go
internal/api/token.go
internal/api/token_test.go
internal/conf/configuration.go
internal/observability/request-logger.go

Sign in with Web3 can be very prone to abuse. This is because all it takes for the `/token?grant_type=web3` endpoint to be abused is the generation of signed messages by a private key.
For this reason a new rate limit config is provided `GOTRUE_RATE_LIMIT_WEB3` which limits the number of such calls per IP address.
To achieve this, the rate limit enforcement on the `/token` API is moved inside in the `Token` handler. This provides a future basis for separating out the rate limiters for Sign in with Password and ID token, as well as rate limiters for PKCE.

feat: separate web3 rate limits from other `/token?grant_type=...`

---

internal/utilities/request.go
internal/utilities/request_test.go

Properly fixes the attempt in #1974

fix: redirects must not be to ip addresses

---

internal/api/token_refresh.go
internal/conf/configuration.go
internal/conf/configuration_test.go
internal/models/sessions.go
internal/models/sessions_test.go
internal/models/user.go

Adds a new optional config `GOTRUE_SESSIONS_ALLOW_LOW_AAL` (duration) which when set will prevent the continued refreshing of a user session if the session has not been upgraded to the highest possible AAL level of the user.
For example if you set it to `1h` it means that a user who has MFA factors enrolled must step-up the session to the highest AAL level for their account within 1 hour, otherwise future session refreshes will fail with a `Invalid Refresh Token: Session Expired (Low AAL: User Needs MFA Verification)`) message.

feat: allow limiting lifespan of low-aal sessions

---

internal/api/provider/azure.go
internal/api/provider/azure_test.go
internal/api/provider/oidc.go

Handles [large `group` claims in Azure ID tokens](https://learn.microsoft.com/en-us/entra/identity-platform/id-token-claims-reference#groups-overage-claim) by fetching them from the ([usually](https://learn.microsoft.com/en-us/graph/api/directoryobject-getmemberobjects?view=graph-rest-1.0&tabs=http)) designated Azure endpoint.

feat: fix large group claim handling in azure id tokens

---

internal/api/provider/azure.go

fix: azure overage claims start with single `_` not two

---

internal/utilities/request.go

`net/url` truncates `Scheme.Something://` to `scheme.something:` breaking backward compatibility.

fix: use redirect URL as-is for mobile apps

---

.github/workflows/release.yml

`supabase-admin-api` (internal repository) likes tarballs that *only use `gotrue`* as only those will be upgraded via the admin-api mechanism.
This adds an additional tarball version usable with this upgrade mechanism.

fix: add `supafast` tarball for upgrading auth via supabase-admin-api

---

.github/workflows/release.yml

Artifact generation failed due to `cp` not working with symlinks.

fix: fix `supafast` tarball generation

---

.github/workflows/dogfooding.yml
internal/hooks/hooks.go
internal/hooks/hookshttp/hookshttp.go
internal/hooks/hookshttp/hookshttp_test.go
internal/hooks/hookspgfunc/hookspgfunc.go
internal/hooks/hookspgfunc/hookspgfunc_test.go
internal/hooks/v0hooks/manager.go
internal/hooks/v0hooks/manager_test.go

This prepares packages to match with the agreed upon end state in https://github.com/supabase/auth/pull/2012

chore: rename packages to remove versioning information

---

internal/conf/configuration.go
internal/conf/configuration_test.go
internal/e2e/e2e.go
internal/e2e/e2e_test.go
internal/e2e/e2eapi/e2eapi.go
internal/e2e/e2eapi/e2eapi_test.go
internal/e2e/e2ehooks/e2ehooks.go
internal/e2e/e2ehooks/e2ehooks_test.go
internal/hooks/v0hooks/manager.go
internal/hooks/v0hooks/manager_test.go
internal/hooks/v0hooks/v0hooks.go

This PR will contain a series of commits preparing for the implementation of before & after user created hooks. It takes the feedback from https://github.com/supabase/auth/pull/2012 into consideration.
Begin adding the Before and After user created hooks:
* update pkg `internal/conf` [d5f5436](https://github.com/supabase/auth/pull/2028/commits/d5f5436ce173d3973fd32c9f970e57e739ae90f6)
* add `BeforeUserCreated` and `AfterUserCreated` to `HookConfiguration` struct
* add test cases for `EmailValidationBlockedMX` to restore 100% test coverage
* update pkg `internal/hooks/v0hooks` [bd37fe2](https://github.com/supabase/auth/pull/2028/commits/bd37fe23cb784939a81f782b533e4fe0247283f5)
* add `BeforeUserCreated` method to `v0hooks.Manager` struct
* add `AfterUserCreated` method to `v0hooks.Manager` …

feat: hooks round 3 - begin adding the Before and After user created hooks

---

internal/e2e/e2e_test.go
internal/e2e/e2ehooks/e2ehooks_test.go
internal/hooks/hookserrors/hookserrors_test.go
internal/hooks/hookshttp/hookshttp_test.go
internal/hooks/hookspgfunc/hookspgfunc_test.go
internal/hooks/v0hooks/manager_test.go

This PR will contain a series of commits preparing for the implementation of before & after user created hooks. It takes the feedback from https://github.com/supabase/auth/pull/2012 into consideration.
[feat: hooks round 4](https://github.com/supabase/auth/pull/2030) - update tests to use require package
* use pkg `require` for tests in: [f2b3600](https://github.com/supabase/auth/pull/2030/commits/f2b36005c924faf7e7f50b24ab2eca1a27600d0c)
* pkg `internal/e2e/...`
* pkg `internal/hooks/...`
[feat: hooks round 1](https://github.com/supabase/auth/pull/2023) - prepare package structure
* Renamed pkg `internal/hooks/v0hooks/v0http` -> `internal/hooks/hookshttp` [8a398ab](https://github.com/supabase/auth/pull/2023/commits/8a398aba564267e4caa4c32bf661699d47d29174)
* Renamed pkg …

feat: hooks round 4 - update tests to use require package

---

internal/api/e2e_test.go
internal/api/mail.go

This change sets EmailData.Token to the new OTP when the secure email change setting is set to true.
This should fix:
https://github.com/supabase/auth/issues/1744
https://github.com/supabase/auth/issues/2042
Note:
I am fixing this bug in a way that is consistent with what I view to be the current bug. I believe for email changes token_new and token_hash_new should always contain the values for the users new_email field. This should be fixed in the future in a way that doesn't break BC.

fix: email-sendhook - bug in email change verification

---

internal/api/provider/keycloak.go

This change will populate the `CustomClaims` field from the `Claims` struct with 'other' claims from the Keycloak user token.
Currently only `Name`, `Sub`, `Email`, and `EmailVerified` are taken from the Keycloak user token.
The "custom_claims" field in the retrieved JWT is populated. 
* https://github.com/orgs/supabase/discussions/18909

feat: Add custom claims from Keycloak user token

---

internal/api/provider/apple.go
internal/api/provider/oidc.go
internal/api/token_oidc.go

Apple seems to have swapped the issuer without notice from `https://appleid.apple.com` to `https://account.apple.com`

fix: accept ID tokens from all `account.apple.com` and `appleid.apple.com`

---

internal/api/token_oidc.go

Apple's ID tokens sometimes say `https://appleid.apple.com` but the well-known URL returns that the issuer should be `https://account.apple.com`.

fix: new `odic.Provider` for apple with insecure issuer url context

---

cmd/serve_cmd.go

do not log fatal when http server successfully closes

fix: do not log fatal when http server successfully closes

---

internal/api/admin.go
internal/api/external.go
internal/api/identity.go
internal/api/invite.go
internal/api/logout.go
internal/api/magic_link.go
internal/api/mail.go
internal/api/mfa.go
internal/api/otp.go
internal/api/reauthenticate.go
internal/api/recover.go
internal/api/resend.go
internal/api/signup.go
internal/api/token.go
internal/api/token_refresh.go
internal/api/user.go
internal/api/verify.go
internal/api/web3.go
internal/conf/configuration.go
internal/models/audit_log_entry.go
internal/models/refresh_token.go
internal/models/refresh_token_test.go

Adds a new config option `GOTRUE_AUDIT_LOG_DISABLE_POSTGRES` which when set to true will cause the server to no longer write to the `audit_log_entries` table.

feat: add option to disable writing to `audit_log_entries`

---

internal/models/audit_log_entry.go

move `DisablePostgres` check after payload mutation to ensure auth_event logs have the same data prior to introduce of the `DisablePostgres` config

fix(auditlog): keep writing to logs even postgres is disabled

---

internal/api/provider/apple.go

Bug fix
Sign-in with Apple does not open the native sign-in flow (face-id + "continue" button), but rather redirects to the account.apple.com website, where users have to do a full manual sign-in. I'm pretty sure this is due to a change introduced (the change to using "account.apple.com" instead of "appleid.apple.com") while there was an outage/issue on Apple's side.
The native sign-in flow should be used when available (e.g. on an iOS device).
This should resolve the problem described by [lizbzlx (comment)](https://github.com/supabase/auth/issues/2051#issuecomment-2967028786), [obeliskgroup (comment)](https://github.com/supabase/auth/issues/2051#issuecomment-2969431447) and [bsheikh (comment)](https://github.com/supabase/auth/issues/2051#issuecomment-2991427271) in [this …

fix: use `appleid.apple.com` as default issuer

---

.github/workflows/release.yml
.github/workflows/test.yml

Additionally, remove unused strategy-matrix from test job
Github workflow actions cleanup
Job `actions/setup-go@v5` takes go version to install from the provided string literal
Job `actions/setup-go@v5` take go version from `go.mod`
Now there are less things to maintain and less changes need to be done on go version bump.
Additionally, unused strategy-matrix from test job is removed.

ci: improve go version management by using `go.mod`

---

internal/api/provider/oidc_test.go
internal/api/provider/provider.go

Support multiple values in `aud` claim in the provider token. It can be either string or array of string (complying with JWT [RFC 7519](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3))

feat: support multiple `aud` for the external providers

---

cmd/admin_cmd.go
internal/api/admin.go
internal/api/external.go
internal/api/mail.go
internal/api/signup.go
internal/api/user.go
internal/conf/configuration.go
internal/models/linking.go
internal/models/user.go
internal/models/user_test.go

Experimental feature internal to Supabase. Don't use outside of Supabase.
Adds the ability to specify providers e.g. `google`, `apple`, whose identities will not participate in the `default` email-similarity identity linking algorithm but be on its own. You can do this by setting
```
GOTRUE_EXPERIMENTAL_PROVIDERS_WITH_OWN_LINKING_DOMAIN="google,apple,..."
```
This has the effect of setting the `is_sso_user` column on `auth.users` to true, which is the only mechanism that allows the same email address to appear in different linking domains. The column cannot be renamed as that requires re-creating a partial index, which is not on the table for this change. It will be revised in the future.

feat: experimental own linking domains per provider

---

internal/api/api.go
internal/api/oauthserver/handlers.go

Adding `.well-known/oauth-authorization-server` endpoint per [RFC 8414](https://datatracker.ietf.org/doc/html/rfc8414)

feat: add `.well-known/oauth-authorization-server` endpoint

---

.github/workflows/release.yml
Makefile

- Add `build-strip` target to Makefile to produce stripped binaries
- Update release workflow to:
- build both regular and stripped binaries
- generate `.tar.xz` artifacts alongside existing `.tar.gz`
- include `.xz` files in checksum generation
- upload `.xz` artifacts to GitHub Releases and S3
This reduces binary size for distribution while keeping compatibility with gzip.
Savings breakdown:
- 38,788,564 auth-arm64
- 26,738,840 auth-arm64 (stripped)
- 18,970,510 auth-arm64.tar.gz
-  9,657,140 auth-arm64.tar.gz (stripped)
-  6,794,836 auth-arm64.tar.xz (stripped, xz -9e)
Decompress xz with:
`tar -xvJf auth-arm64.tar.xz -C /path/to/dir`

feat: add xz-compressed release artifacts and stripped binary build

---

.gitignore
Makefile

Stripping removed the symbol encoding the version. Now the stripped binary rewrites the version file before build.

fix: stripped binary now includes version

---

go.mod
internal/api/api.go
internal/api/api_test.go
internal/api/apierrors/errorcode.go
internal/api/context.go
internal/api/oauthserver/authorize.go
internal/api/oauthserver/handlers.go
internal/api/oauthserver/handlers_test.go
internal/api/oauthserver/service.go
internal/api/oauthserver/service_test.go
internal/api/shared/context.go
internal/conf/configuration.go
internal/models/flow_state.go
internal/models/oauth_authorization.go
internal/models/oauth_authorization_test.go
internal/models/oauth_client.go
internal/models/oauth_client_test.go
internal/models/oauth_consent.go
internal/models/oauth_consent_test.go
internal/models/oauth_scope.go
internal/models/oauth_scope_test.go
internal/models/pkce.go
internal/models/pkce_test.go
internal/security/pkce.go
internal/security/pkce_test.go
internal/utilities/strings.go
migrations/20250804100000_add_oauth_authorizations_consents.up.sql

This PR implements the OAuth 2.1 authorization endpoint in Supabase Auth, completing the server-side OAuth flow by adding user authorization and consent management. Building on the OAuth client registration foundation (#2098), this enables Supabase Auth to function as an OAuth 2.1 authorization server.
- **Authorization Initiation** (`GET /oauth/authorize`) - Initiates OAuth 2.1 authorization code flow with PKCE support and redirects user to (for now) pre-configured url
- **Authorization Details** (`GET /oauth/authorizations/{authorization_id}`) - Retrieves authorization request details for consent UI
- **Consent Processing** (`POST /oauth/authorizations/{authorization_id}/consent`) - Handles user consent decisions (approve/deny)
- **PKCE Enforcement** - Mandatory PKCE (RFC 7636) with …

feat: implement OAuth2 authorization endpoint

---

Makefile

When developing locally I always comment out dev-deps due to the failed soda command. Today I did a grepped through the repo and it seems soda is no longer used.
- Remove unused `soda` command
- Could not find any reference to this
- Remove `dev-deps` target that installed all cmds
- Add dedicated check targets:
- `check-gosec` installs gosec if missing
- `check-staticcheck` installs staticcheck if missing
- `check-exhaustive` installs exhaustive if missing
- `check-oapi-codegen` installs oapi-codegen if missing
- Update existing targets to depend on new check targets:
- `sec` depends on `check-gosec`
- `unused` depends on `check-staticcheck`
- `static` depends on `check-staticcheck` and `check-exhaustive`
- `generate` depends on `check-oapi-codegen`
- Adjust `.PHONY` declarations to …

chore: replace dev-deps with per-tool check targets

---

internal/api/middleware.go
internal/api/oauthserver/authorize.go
internal/api/oauthserver/client_auth_test.go
internal/api/oauthserver/handlers.go
internal/api/oauthserver/handlers_test.go
internal/api/oauthserver/service.go
internal/api/oauthserver/service_test.go
internal/models/oauth_client.go
internal/models/oauth_client_test.go
migrations/20250903112500_remove_oauth_client_id_column.up.sql

Simplified OAuth client model by removing redundant `client_id` column and using the primary `id` UUID field as the public client identifier.

feat(oauth2): use `id` field as the public client_id

---

internal/api/provider/oidc.go

Gain access to the [`transfer_sub` claim present in Apple ID tokens](https://developer.apple.com/documentation/signinwithapple/bringing-new-apps-and-users-into-your-team) when an app is being transferred from one owner to another (e.g. when an app is purchased by another company).

feat: support `transfer_sub` in apple id tokens

---

internal/api/api.go
internal/api/api_test.go
internal/api/oauthserver/handlers.go
internal/api/oauthserver/service.go

- Add `POST /admin/oauth/clients/{client_id}/regenerate_secret` endpoint
- Only allow secret regeneration for confidential clients
- Return updated client with new plaintext secret in response

feat(oauth2): add admin endpoint to regenerate OAuth client secrets

---

internal/api/admin.go
internal/api/external.go
internal/api/external_oauth.go
internal/api/hooks.go
internal/api/identity.go
internal/api/magic_link.go
internal/api/mfa.go
internal/api/token.go
internal/api/token_refresh.go

Some API paths were using `a.db` directly, which bypasses request scoped timeouts/cancellation. This change ensures db work is performed with a connection derived from the current request context. No behavioral are changes are intended here.

fix: ensure request context exists in API db operations

---

internal/api/oauthserver/authorize.go
internal/api/oauthserver/authorize_test.go

Replace `Referer` header validation with `Origin` header in `validateRequestOrigin` function. Referer was unintended at the beginning. Using `Origin` header as it's automatically set by browsers for cross-origin requests. This is a very basic attempt to prevent cross domain malicious calls.
Key changes:
- Check `Origin` header instead of `Referer` header
- Allow empty `Origin` header (for backend/mobile app initiated requests)
- Add comprehensive test coverage for new validation behavior

fix(oauth2): switch to Origin header for request validation

---

internal/conf/configuration.go
internal/storage/advisor.go
internal/storage/advisor_test.go
internal/storage/dial.go

Adds a simple advisor that emits a log message every hour, if the number of [DBStats](https://pkg.go.dev/database/sql#DBStats) samples exceeds:
- 1/3 or more samples indicate more than 1ms wait for every millisecond in the sampling interval
- 1/3 or more samples indicate 2 or more goroutines have been waiting to acquire a connection from the pool
For instance, if you set `GOTRUE_DB_ADVISOR_SAMPLING_INTERVAL="100ms"` and `GOTRUE_DB_ADVISOR_OBSERVATION_INTERVAL="1s"` then:
- There are 1000 / 100 = 10 samples
- Every 100ms a sample is taken and the conditions are checked
- Log message is emitted if either one of the conditions are met at most once per hour

feat: add advisor to notify you when to double the max connection pool
