- README.md
> feat: Adds a docker deployment

- api/external.go
re: https://github.com/supabase/gotrue-js/issues/2#issuecomment-696445569
> fix: changes # to ? in external redirect callbacks

- api/magic_link.go
fix for intermittent json corruption of signup body
> fix: stops special symbols corrupting json body intermittently

- models/refresh_token.go
- models/user.go
Bug fix according to issue #11 .
Add some missing logic to update last_sign_in field while generating token
> chore: Add missing logic to update last_sign_in field

- api/verify.go
Feature according to task #30 
Add new field to redirected URL in verify function. Type field represent which verification is successfully finished (recovery or signup)
> Added field type to redirected query in verify function

- api/verify.go
Added logic for redirecting errors to user's app when recovery/magiclink expire according to issue #39
> Feat: added logic for redirecting expired token errors to user's app

- .github/workflows/release.yml
- .gitignore
- Makefile
Adds an ARM build, similar to https://github.com/supabase/supabase-admin-api/pull/32
Fixes #32
> Add an ARM cross-compilation build step.

- api/token.go
Fixed error messages from brute forcing according to issue #59
> Fixed error response message from password guessing

- api/provider/discord.go
Bug fix to return the correct avatar URL for users using the default Discord avatars.
Currently the avatar URL is just returned as `https://cdn.discordapp.com/avatars/<snowflake>/<avatar-hash>.<extension>`, which ignores the `avatar` field from the Discord API which can be `null` if the user is using a default avatar.
The new behavior checks if the `avatar` field is "`null`" and returns the correct avatar URL for default and custom avatars based on Discord's [image CDN endpoints](https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints).
If `avatar` field
* is "`null`", return avatar URL `https://cdn.discordapp.com/embed/avatars/<discriminator % 5>.<extension>`.
* else, return normal avatar URL.
None.
> fix: return correct avatar URL for default Discord avatars

- api/signup.go
Fixes #112 
Error message for requesting a confirmation email within the MAX_FREQUENCY time set
> fix: missing import & invalid type

- README.md
- api/admin_test.go
- api/api_test.go
- api/instance_test.go
- api/magic_link.go
- api/middleware.go
- api/otp.go
- api/settings.go
- api/settings_test.go
- api/signup.go
- conf/configuration.go
Refactor EXTERNAL_EMAIL_DISABLED & EXTERNAL_PHONE_DISABLED config vars to EXTERNAL_EMAIL_ENABLED and EXTERNAL_PHONE_ENABLED.
> Refactor: rename env vars

- migrations/20210722035447_adds_confirmed_at.up.sql
- models/user.go
fixes https://github.com/supabase/gotrue/issues/152
> fix: adds a generated confirmed_at column

- models/user.go
See https://gobuffalo.io/en/docs/db/models#read-only-fields
> Fix: Change confirmed_at field to read-only

- cmd/migrate_cmd.go
Remove sql query info from logs
> Chore: fix logging

- cmd/migrate_cmd.go
* Removes pop migration logging information
> Fix: migrate cmd logging

- api/admin_test.go
- api/audit_test.go
- api/auth.go
- api/context.go
- api/external.go
- api/external_azure_test.go
- api/external_bitbucket_test.go
- api/external_discord_test.go
- api/external_facebook_test.go
- api/external_github_test.go
- api/external_gitlab_test.go
- api/external_google_test.go
- api/external_twitch_test.go
- api/hooks.go
- api/invite_test.go
- api/middleware.go
- api/provider/apple.go
- api/signup_test.go
- api/token.go
- go.mod
- go.sum
> chore: dependabot issues

- api/phone.go
> fix: update default message for phone otp

- .github/workflows/test.yml
- Makefile
- hack/database.yml
- hack/migrate.sh
* Add github action for running tests
* Clean up makefile
> Chore: Add github action for running test suite

- api/signup.go
- api/signup_test.go
* Replace existing user id with fake uuid generated
* Add a test to ensure that the user id is different from the existing one signed up
> Fix: sanitizeUser should sanitize user id

- api/signup.go
* Remove `last_sign_in_at`, `email_confirmed_at`, `phone_confirmed_at` and `confirmed_at` fields
> fix: remove potentially leaking fields

- api/token.go
> Fix: sign in error message

- api/invite_test.go
- api/signup.go
* Duplicate identities created in [this PR](https://github.com/supabase/gotrue/pull/287/files#diff-c8a2b3cbde5284846b2a4231b94df6b607fd908fdbaa98b051b6bd47a2846ce9R293-R298)
> Fix: duplicate identities on oauth signup

- migrations/20211124214934_update_auth_functions.up.sql
- migrations/20211202183645_update_auth_uid.up.sql
* Updates `auth.uid()` to address https://github.com/supabase/supabase/issues/4244
> fix: update auth.uid function

- api/verify.go
* Fixes issue where an open redirect is allowed
> fix: verify redirect url on POST /verify

- CONTRIBUTING.md
Just fixes a bunch of minor typos I ran into while reading contributing.md not really important but figured I'd just fix.
> Fix minor typos in contributing guide

- api/external.go
- api/signup.go
- api/token.go
- api/verify.go
- conf/configuration.go
* set cookies on oauth callback
* change default cookie name to "sb"
> fix: set cookies on oauth callback

- README.md
to match https://github.com/supabase/gotrue/pull/326 and https://github.com/supabase/supabase/pull/5018
> chore: adds notion to readme

- api/provider/discord.go
> fix: add discord discriminator to username

- .github/workflows/release.yml
* _Hopefully_ fixes issue where test workflow completes but release workflow isn't run
> fix: release action should be triggered after test

- api/verify.go
- api/verify_test.go
* Fixes an issue where the error isn't being returned as a json response on `POST /verify`
> fix: return error as json on POST verify

- api/recover.go
Fix #338 
Returns user not found error
Does not return user not found error
TODOs:
- Check for constant time return
> Change recover password to not return user not found error

- migrations/20220224000811_update_auth_functions.up.sql
* Fixes https://github.com/supabase/supabase/issues/4794 
* Related to https://github.com/supabase/supabase/pull/4871
> fix: add nullif to auth functions

- api/provider/notion.go
- api/provider/provider.go
- api/provider/twitch.go
- api/provider/twitter.go
* return error message if oauth request made returns a non-2xx response
> fix: handle non-2xx status code

- models/json_map.go
> fix: default nil interface to empty byte slice

- api/otp.go
* Fixes https://github.com/supabase/supabase/issues/1176#issuecomment-1098187468
> fix: validate email & phone number in shouldCreateUser

- go.mod
- go.sum
> chore: dependabot

- models/audit_log_entry.go
* Log auth event whenever an audit log entry is created
> fix: log auth actions

- api/admin.go
- api/audit.go
- api/external.go
- api/invite.go
- api/logout.go
- api/magic_link.go
- api/mail.go
- api/otp.go
- api/reauthenticate.go
- api/recover.go
- api/signup.go
- api/token.go
- api/user.go
- api/verify.go
- migrations/20220614074223_add_ip_address_to_audit_log.postgres.up.sql
- models/audit_log_entry.go
- models/refresh_token.go
In order to support IP address tracking for MFA and SAML we would probably to track IP addresses in our audit log.
Not sure if there are other immediate fields that we should consider adding. Let me know if any others come to mind
No IP Addresses
IP address field in audit log
> Add IP Address field to audit log

- api/sms_provider/twilio.go
> fix: handle all non-2xx errors from twilio

- Makefile
> fix: go fmt -> gofmt in Makefile 

- api/recover.go
- api/recover_test.go
Masks the response on the `/recover` endpoint if the user does not have an account.
Leaks information that the user has an account.
> feat: Mask user existence on /recover

- api/mail.go
* GenerateLink should also return the query params in the verification url as well as the raw email otp
> fix: update generateLink response

- api/magic_link.go
- api/otp.go
- api/otp_test.go
As in title
Fix #416 
Metadata with Passwordless phone signups as well as magic link. See video for magic link demo on localhost
> Add Metadata to Phone Signup(Without Password)

- api/mail.go
* Fixes issue where there's a nil pointer dereference because the user struct is nil for new users
> fix: generate signup / invite link

- .github/workflows/test.yml
- .gitignore
- Makefile
- README.md
- api/hook_test.go
* add coveralls to ci
* based on https://github.com/marketplace/actions/coveralls-github-action
> chore: add coveralls to ci

- api/mfa.go
- api/mfa_test.go
- api/signup_test.go
- migrations/20220607041349_add_mfa_schema.up.sql
- models/user.go
- models/user_test.go
Completely remove notion of MFAEnabled from the code, model and SQL
> Completely Remove notion of MFAEnabled

- api/admin.go
- api/admin_test.go
- api/api.go
- api/mfa.go
- api/mfa_test.go
- models/audit_log_entry.go
- models/mfa_constants.go
- models/recovery_code_test.go
Introduces the following:
Refer to #527 for Update related endpoints
None
> Admin Delete and Get endpoints

- api/api.go
- api/mfa.go
- api/mfa_test.go
> refactor: remove /recovery_codes endpoint

- api/verify_test.go
- conf/configuration.go
* Do not normalise mobile deeplinks for redirect urls
> fix: dont normalise mobile deeplinks

- api/mfa.go
- api/mfa_test.go
Makes the issuer field mandatory for `/verify` route 
> Minor MFA fixes

- api/admin.go
- api/admin_test.go
- api/api.go
- models/audit_log_entry.go
- models/factor.go
> feat: add update factor admin endpoint

- api/external.go
- api/helpers.go
- api/provider/provider.go
- api/saml.go
- api/signup.go
- api/token.go
- api/verify.go
- conf/saml.go
- migrations/20220801152030_add_saml.up.sql
- migrations/20220804104030_add_saml.up.sql
- models/errors.go
- models/refresh_token.go
- models/sso.go
Adds SAML SP initiated flow via the `/verify` endpoint.
> feat(saml): Add SAML SP initiated flow

- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- reduce some boilerplate with semantic releaser action
- disallow workflow dispatch
> Use semantic releaser action

- api/context.go
- api/external.go
- api/middleware.go
> Chore: remove netlify ID

- .github/workflows/release.yml
- .releaserc
Bug fix for release job
reference: https://github.com/supabase/functions-relay
> Add releaserc config for release action

- .github/workflows/release.yml
Bug fix
breaking because release tag has `v` prefix
> fix: add tag prefix to semver

- .github/workflows/test.yml
- Makefile
- api/api.go
- api/api_test.go
- api/external.go
- api/provider/apple.go
- api/provider/facebook.go
- api/provider/twitter.go
- conf/logging.go
- models/user.go
Adds [gosec](https://github.com/securego/gosec) scanning. Fixes all errors except _G104 - Unhandled error_ since they're dealing mostly with `Close()` errors on readers. I shall fix them in a follow-up PR.
> chore: Add gosec scanning (exlcudes G104)

- api/context.go
- api/errors.go
- api/hooks.go
- api/mail.go
- api/provider/azure.go
- api/token.go
- mailer/noop.go
- mailer/template.go
Staticcheck gives the removed lines as unused. Will be adding it in the CI flow in a follow up PR.
> style: remove unused code (via staticcheck)

- .github/workflows/release.yml
- .github/workflows/test.yml
- .releaserc
Adds semantic release behavior for the `mfa` experimental branch.
> style: add semantic release behavior for `mfa`

- .releaserc
> style: fix `.releaserc` bad json

- models/connection.go
Although used only in tests, with the addition of SAML and MFA, this function becomes unreadable. This is a much simpler way of tracking all tables that can be truncated.
> refactor: `TruncateAll` for better readability

- crypto/crypto.go
Removes unused GenerateEmailOtp function
> Remove unused GenerateEmailOtp function

- conf/configuration.go
- conf/tracing.go
Comes out of #554 -- fixes up the configuration to allow for validation.
> refactor: configuration with validation

- Makefile
`make all` didn't work without first running `make dev-deps`. Now it should work.
> style: add dev-deps make dependency to `vet`, `sec`

- .github/workflows/release.yml
- .github/workflows/test.yml
- .releaserc
Adds the `zerosessionidfix` to release workflows.
> ci: add `zerosessionidfix` branch to workflows

- api/mail_test.go
* Add test cases for `/admin/generate_link` endpoint for all verification types
> test: add test for generate_link

- .releaserc
* Remove unused branch `zerosessionidfix`
> fix: releaserc

- api/logout_test.go
* Add test for logout endpoint
> test: add test for logout

- api/middleware.go
- security/hcaptcha.go
* Checks the url path as well for bypassing captcha
> fix: bypass captcha for certain routes

- api/mfa.go
- api/token.go
* check totp validity only if challenge isn't expired
* always send underlying error when returning internalServerError
> refactor: nit changes

- api/mfa.go
- api/token.go
- api/verify.go
- models/amr.go
- models/factor.go
- models/mfa_constants.go
Replace mfa/constants.go for enum
> refactor: replace mfa/constants.go for enum

- migrations/20221003041349_add_mfa_schema.up.sql
- models/factor_test.go
- models/sessions.go
- models/sessions_test.go
Breaks up the refactors to session  in #691 into a separate PR
> refactor: add sessions refactors

- .github/workflows/release.yml
- .github/workflows/test.yml
changes .yml file from `mfa_v1` to `mfa`
> fix: update .yml to mfa

- api/admin.go
- api/admin_test.go
- api/mfa.go
- api/mfa_test.go
- models/factor.go
- models/factor_test.go
- remove FindFactorByFriendlyName
- add negative test cases
- Make error messages more descriptive
- Block admin from modifying factor status
- Split UnenrollFactor tests into Verified and Unverified
> refactor: refactor models/factor and block admin from modifying factor status

- api/admin.go
- api/admin_test.go
- api/mfa.go
Add negative test cases  for admin related functions
> fix: update admin tests to add negatives

- api/admin_test.go
- api/otp_test.go
- api/phone_test.go
- api/token_test.go
- api/user_test.go
- api/verify_test.go
Similar to #471 but extracts the changes which can be merged into master
> refactor: add implicit struct tags

- api/admin_test.go
- api/mfa_test.go
- api/phone_test.go
- api/user_test.go
Add Explicit struct tags to tests
> refactor: add explicit struct tags(mfa)

- api/mfa.go
- api/mfa_test.go
Removes the requirement for a code in order to unenroll as the AAL2 check introduced  in #751 should ensure user has MFA enabled
> refactor: remove requirement for code in order to unenroll

- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
- Dockerfile.dev
- docs/doc.go
- go.mod
Update CI, code to use Go 1.19.
> feat: update to Go 1.19

- mailer/template.go
If the user passes a proper URL with query params or a fragment in the `redirectTo` parameter on sign-in with magic links, then the query parameters and the fragment will "break" the URL because they are not query escaped. Since some users have already noticed this and started query escaping the `redirectTo` parameter, to keep backward compatibility with them, the URL will only be escaped if it contains any of the unescaped characters that should not appear within a query parameter (i.e. `&=#`).
> fix: properly escape `redirectTo` URL for magic links

- api/external.go
Extracts the account creation from external identities into a separate function which can be refactored further on.
The extracted function intentionally uses a minimal number of transformations to keep it bugs free. This is why the `terr` error variable is still used, even though it should be renamed to `err`. Also why the `errReturnNil` mechanism is being used. This will be refactored in follow up PRs.
> refactor: extract account creation from external identity logic

- api/sso.go
- api/sso_test.go
`POST /sso` typically redirects using HTTP 303 See Other on successful SSO attempt.
Now, you can pass the optional `skip_http_redirect` parameter to get a HTTP OK response with the below JSON:
```json
{
"url": "..."
}
```
The change is being made since browser's fetch does not modify the `window.location` nor is able to let developers handle the HTTP 303 See Other response. Thus to use this method from the browser you would need to pass `skip_http_redirect: true` and set the `window.location.href = <URL-in-json>`.
> feat(saml): return JSON response on `POST /sso` with optional JSON response

- README.md
> adds README docs for #421

- api/ssoadmin.go
Update logic for SSO domains and SAML attribute mappings was not working correctly since Pop does not handle creation / destruction in updates on nested resources.
> fix(saml): correct SSO domain, SAML attribute mapping update logic

- models/user.go
- models/user_test.go
Whenever an email or phone change occured, the corresponding `email` or `phone` provider identity was not getting updated. This is now the case.
> fix: update email, phone identities on change

- api/mfa.go
Currently, users can verify a factor they don't  on the unlikely chance that they have a factor, create a verified session, and  have the same IP address.
We introduce an additional check which requires that users have an ID which matches the factorID in order to unenroll.
This potentially exposes information about the factorID that a user owns. However, this risk is mostly mitigated since 1. the user cannot verify unless already signed in(AAL1)
2. the user needs to comb the space of all UUIDs in order to find the one verified factor  - this will take a long time because of the rate limiters in place
> fix: add checks for ownership for unenroll and verify

- migrations/20211124214934_update_auth_functions.up.sql
- migrations/20220224000811_update_auth_functions.up.sql
related https://github.com/supabase/cli/pull/648
> chore: replace tabs in migration with spaces

- .github/workflows/mirror.yml
- .github/workflows/publish.yml
ci
publish docker image to ghcr
> chore: mirror gotrue image to ghcr

- api/sso_test.go
- api/ssoadmin.go
- migrations/20221202110421_remove_sso_sessions.up.sql
- models/connection.go
- models/sso.go
- models/sso_test.go
Removes:
- `resource_id` concept as it's not used and not necessary at this time
- `auth.sso_sessions` table -- a leftover from the Proof of Concept
Refactors:
- renames `keepProviders` into `keepDomains` variable
> feat(saml): remove unused features, small refactors

- api/ssoadmin.go
A caller that did not specify `domains` when updating an SSO provider, then all of the domains were being removed. This should not be the case, since if that was the intention the caller should have sent an empty array instead.
> fix(saml): not specifying `domains` should not delete all domains

- api/admin.go
> fix: admin delete factor should be allowed to delete unverified factors

- Dockerfile.postgres.dev
> chore: bump dev docker Postgres to 15

- hack/postgresd.sh
* Updates postgresd.sh to use postgres 15
> chore: upgrade to postgres 15

- api/magic_link.go
- api/otp.go
- api/otp_test.go
* On subsequent requests for magiclink or sms OTP, if the user hasn't completed the signup process yet (i.e they haven't confirmed their email or phone), then the endpoint should resend the signup confirmation email or sms.
* The previous behaviour would have sent the magiclink email template even though user hasn't accepted the signup confirmation yet. This led to an undesirable onboarding experience when resending magiclinks because subsequent requests would deliver the wrong email template for a user who hasn't completed the signup process. 
* Partially address #312. Specifically, this comment:
> Send a magic link. This will work, though you'll be using a different email template. Instead of sending a confirmation email, you'll be sending a log-in email. Functionally this is the same, …
> fix: return signup confirmation if signup is incomplete for magiclink / otp

- .github/workflows/mirror.yml
- .github/workflows/publish.yml
instead of long lived access keys
> fix: switch to aws roles

- api/helpers.go
> chore: remove unused SafeHTTPClient function

- internal/api/hooks.go
- internal/api/provider/notion.go
- internal/api/provider/provider.go
- internal/api/provider/twitch.go
- internal/api/provider/twitter.go
- internal/api/sms_provider/messagebird.go
- internal/api/sms_provider/textlocal.go
- internal/api/sms_provider/twilio.go
- internal/api/sms_provider/vonage.go
- internal/api/ssoadmin.go
- internal/security/hcaptcha.go
- internal/utilities/io.go
- internal/utilities/request.go
Fixes issues with latest `gosec`.
> feat: add safe deferred closing

- internal/api/helpers.go
> fix tiny typo

- internal/models/linking.go
* In older versions, there can be instances where a user exists without an identity. When we refactored the account linking logic in https://github.com/supabase/gotrue/releases/tag/v2.35.0, we refactored the account linking logic to check if there is an existing identity with the same email. If a user doesn't have any identities, an oauth sign-in (which should automatically link) will fail since the decision made would be to `CreateAccount`. 
1. sign up a user with magiclink and confirm the email
2. ssh into the db and delete the user's identity
3. attempt to use the same email to sign in with google (fails as expected)
4. build gotrue with these changes
5. repeat step (3) and observe that the oauth sign-in works now
Steps 1-2 attempts to recreate the scenario where a user exists without …
> fix: account linking logic

- migrations/20221215195500_modify_users_email_unique_index.up.sql
Dropping the `users_email_key` can sometimes be an issue as the `auth.users.email` column has been used as a foreign key reference in certain projects. This PR will continue with the migration, but will raise a notice that the developers of such projects should take care of this change manually. If it is not handled, SSO will not work and future compatibility with new versions may be an issue.
> feat: make dropping `users_email_key` backward compatible

- internal/api/magic_link.go
- internal/api/otp.go
FLUP to #1004, moves OTP and validation to separate function
> refactor: convert magic link and otp validation to function

- internal/api/otp.go
- internal/api/signup.go
- internal/api/sms_provider/sms_provider.go
- internal/api/user.go
> refactor: move validation for signup into function

- internal/api/signup.go
- internal/api/verify.go
Also moves a validation check out of transaction.
Need to confirm that there are no ordering depenedencies between Validation and setting of defaults before setting to ready
> refactor: move default setting into a function

- openapi.yaml
Found a small typo. 
"successfull"
"successful"
Figured I'd flag and share since I ran across it this morning. Thanks!
> Typo Change

- internal/api/external.go
- internal/api/helpers.go
- internal/api/pkce.go
- internal/api/token.go
- internal/models/flow_state.go
> refactor: move file to dedicated pkce namespace

- internal/api/helpers.go
- internal/api/signup.go
- internal/models/amr.go
- internal/models/audit_log_entry.go
- internal/models/challenge.go
- internal/models/factor.go
- internal/models/flow_state.go
- internal/models/sessions.go
- internal/models/user.go
Given that we're doing a deploy soon this can wait since it's a non essential change. Just thought I'd open the PR first
> refactor: switch to uuid.Must

- internal/api/token.go
* Add comments to explain how the reuse detection works
> refactor: explain automatic reuse detection

- internal/api/mfa.go
Converts some MFA strings into error messages
> refactor: convert mfa strings to error messages

- internal/api/pkce.go
Light refactor as discussed in [this comment](https://github.com/supabase/gotrue/pull/1027#discussion_r1162298555)
> refactor: condense code challenge check

- internal/api/magic_link.go
- internal/api/recover.go
- internal/api/signup.go
- internal/models/flow_state.go
* Fix PKCE bugs found in the magic link flow
* Refactor some bits of the code
> fix: pkce bug with magiclink

- internal/api/token.go
- internal/models/flow_state.go
Currently, the flow states don't expire as expected as the check is faulty
> fix: fix flow state expiry check

- internal/api/external.go
- internal/api/verify.go
Refactor around the redirect url generation for pkce. Done for consistency with how the other redirect urls are generated, and also to cut back on a few lines of code.
> refactor: lump code redirect url generation into function

- internal/models/errors.go
> refactor: remove unused errors

- internal/api/token.go
Adds appropriate audit log statements for access tracking and also for metrics tracking.  For metrics tracking we can also monitor requests to the endpoint as a whole
> feat: add log entries for pkce

- CONTRIBUTING.md
Remove invite link for discord from contributing.md
> chore: remove invite link

- go.mod
- go.sum
> feat: update github.com/coreos/go-oidc/v3@v3.6.0

- openapi.yaml
* Update openapi to include token_hash in `POST /verify`
> chore: update openapi

- internal/api/helpers_test.go
- internal/api/pkce.go
* Simplify PKCE param validation logic
> refactor: simplify validation logic

- README.md
Docs update.
There is no table of contents so it is not easy to search the docs.
There is now a table of contexts for easier searching of the docs.
N/A
> docs: adding table of contents.

- go.mod
- go.sum
Was not using the latest version.
> feat: update github.com/rs/cors to v1.9.0

- migrations/20230914180801_add_mfa_factors_user_id_idx.up.sql
see title, supports [this internal PR](https://github.com/supabase/infrastructure/pull/14835/files) among other things
> feat: add index on user_id of mfa_factors

- CONTRIBUTING.md
- README.md
* Update readme and contributing guides
> docs: update readme & contributiing guides

- internal/api/verify.go
see title, aims to address #1252 and https://github.com/supabase/gotrue-js/issues/787
TODOs:
> fix: take into account test otp for twilio verify

- internal/api/provider/fly.go
* Organization info is not needed
> fix: remove organizations from fly provider

- internal/api/provider/fly.go
This reverts commit ef0614b164b1e79df4a6ce8ba8fe2ee63c7afbbf.
* Reverts this PR: https://github.com/supabase/gotrue/pull/1267
> fix: Revert "fix: remove organizations from fly provider"

- internal/api/verify.go
* The internal error messages for the `/verify` endpoint can be made clearer to the developer. 
* This is not a breaking change since internal error messages are not returned to the end user / application
> fix: log clearer internal error messages for verify

- internal/api/external.go
- internal/api/external_github_test.go
- internal/api/external_kakao_test.go
- internal/api/provider/provider.go
- internal/api/provider/spotify.go
- internal/models/linking_test.go
- internal/models/user.go
- internal/models/user_test.go
> feat: spotify oauth

- internal/api/token_test.go
* Set inactivity timeout to nil when the test completes
> chore: session inactivity timeout test

- go.mod
- go.sum
Part 1 of 2 of a PR aimed to address this issue: https://github.com/supabase/gotrue/security/dependabot/11 by updating dependencies 
- github.com/microcosm-cc/bluemonday v1.0.26 
- go version
Split into two PRs so as not to mix the changes to the OTEL packages with update of unrelated dependencies
> fix: update dependencies (1/2)

- internal/api/mfa.go
- internal/api/mfa_test.go
See title
PR to update GoTrue: https://github.com/supabase/gotrue/pull/1277/files
Docs Update: https://github.com/supabase/gotrue/pull/1277
> feat: add friendly name to enroll factor response

- .github/workflows/release.yml
- Dockerfile
Some things in the workflows remained unrenamed.
> ci: fix workflows post rename

- internal/api/otp.go
> fix: return correct sms otp error

- internal/api/token.go
- internal/api/token_refresh.go
We need to bubble up the error so it doesn't get masked.
> feat: properly return hook error

- internal/hooks/auth_hooks.go
> feat: add session id to required claim for output of custom access token hook

- .github/workflows/conventional-commits-lint.js
- .github/workflows/publish.yml
Lints merge and revert commits correctly.
Publishes images with the correct version tags.
> ci: lint merge and revert commits, publish docker images with correct tags

- internal/api/token.go
Temporarily reverts a refactor of `updateMFASessionsAndClaims`. This will be addressed in a separate PR
> fix: revert refactor on updateMFASessionsAndClaims

- internal/models/sessions.go
#1437 broke the `amr` calculation in the access token as it skipped including the `provider` for the SAML AMR, which is vital for building RLS policies.
> fix: expose `provider` under `amr` in access token

- internal/api/token.go
Was passing through the code and found that a re-ordering  was slightly easier to read for me. Let me know your thoughts
> feat: refactor resource owner password grant

- README.md
> chore: fix link to netlify gotrue

- go.mod
- go.sum
* upgrades supabase/mailme package to v0.1.0 which contains https://github.com/supabase/mailme/pull/2
> chore: update mailme

- internal/api/hooks.go
- internal/api/mfa.go
- internal/api/phone.go
- internal/api/token.go
:wave:
Remove redundant method parameter `hookURI`
> chore: remove redundant hookURI parameter

- internal/api/api.go
:wave: Consolidate the middleware setup logic for request tracing. Instead of separate conditions, use a single one.
> chore: simplify request tracing middleware setup logic

- internal/api/hooks.go
- internal/api/hooks_test.go
- internal/api/identity_test.go
- internal/api/otp.go
- internal/api/phone.go
- internal/api/phone_test.go
- internal/api/reauthenticate.go
- internal/api/resend.go
- internal/api/signup.go
- internal/api/user.go
* clean up unused args in various functions
> chore: remove unused args in functions

- internal/api/middleware.go
If `Write` is called and `WriteHeader` was not previously called, the `WriteHeader` needs to be set to StatusOK.
> fix: call write header in write if not written

- internal/api/provider/spotify.go
Re-formats the files from PR #1209.
> ci: re-format files

- .github/workflows/publish.yml
> fix: publish to ghcr.io/supabase/auth

- go.mod
- go.sum
- internal/api/mfa.go
* Upgrade the totp library to the latest version
* Improve logging when mfa verification fails by returning the validation error internally as well as logging the code used
> fix: improve mfa verify logs

- internal/api/admin.go
- internal/api/password.go
- internal/api/password_test.go
- internal/crypto/password.go
- internal/models/user_test.go
* Check if password exceeds max length in `checkPasswordStrength`
> fix: check password max length in checkPasswordStrength

- internal/api/admin.go
- internal/api/mfa.go
- internal/api/mfa_test.go
- internal/models/challenge.go
- internal/models/factor.go
Makes two changes:
- Ensures we track DB calls to loadFactor
- Changes the interface for creating a challenge in attempt to make clear that Challenge should always have a Factor
> fix: refactor mfa models and add observability to loadFactor

- internal/hooks/auth_hooks.go
Add is_anonymous claim to hook spec to ensure that generated tokens always contain the is_anonymous claim.
> feat: add is_anonymous claim to Auth hook jsonschema

- openapi.yaml
> fix: minor spelling errors

- internal/api/admin.go
- internal/api/mfa.go
- internal/api/mfa_test.go
- internal/models/challenge.go
- internal/models/user.go
In `loadFactor` ensure that all factors which are loaded are owned by the user
> fix: move is owned by check to load factor

- migrations/20240806073726_drop_uniqueness_constraint_on_phone.up.sql
Currently, the phone constraint only allows for one phone number across all users. Changes to make phone numbers unique per user.
Also renames the constraint on phone factors to reflect that it applies to all factors rather than verified factors.
> fix: change phone constraint to per user

- internal/storage/dial.go
* There exist a race condition between the context deadline and a transaction being committed - in certain cases, the context cancellation may happen after a transaction has been committed, which leads to attempting a rollback operation on a closed transaction. Users may end up seeing the following error: `database error on committing or rolling back transaction: sql: transaction has already been committed or rolled back` - this PR chooses to ignore the error
> fix: ignore errors if transaction has closed already

- internal/api/verify.go
Custom SMS verification did not work if Twilio Verify was enabled. Furthermore, test OTP flow was misplaced.
> fix: custom SMS does not work with Twilio Verify

- .github/workflows/release.yml
> Revert "ci: upload release artifact to supabase s3 bucket"

- .github/workflows/conventional-commits-lint.js
- .github/workflows/conventional-commits.yml
Update workflow to match other repositories and better handling of github.event format.
> chore: update check conventional-commits

- migrations/20240427152123_add_one_time_tokens_table.up.sql
Reverts supabase/auth#1858
Reverse reverse, cha cha real smooth now
> fix: Revert "fix: revert fallback on btree indexes when hash is unavailable"

- internal/api/logout.go
* Log a message if the session is nil
> fix: check if session is nil

- README.md
docs: update README for command syntax and binary execution
> docs: update README for command syntax and binary execution

- .github/workflows/dogfooding.yml
Fixes a minor issue with the dogfooding check. GitHub Actions never work from the first time.
> ci: fix dogfooding check

- CONTRIBUTING.md
> chore:fix typo in contributing

- internal/conf/configuration.go
- internal/conf/configuration_test.go
- internal/conf/jwk.go
- internal/conf/jwk_test.go
- internal/conf/rate_test.go
- internal/conf/saml.go
- internal/conf/saml_test.go
Increase test coverage in internal/conf to 100%.
> feat: increase test coverage in conf package to 100%

- .github/workflows/test.yml
> ci: use `ubuntu-latest`

- internal/models/sessions.go
- internal/models/sessions_test.go
* When a SSO user has MFA enabled and signs in, the `sso/saml` amr claim does not contain the provider field
* Usage of sort.Reverse was previously incorrect and the comments made did not match what was expected - sort.Reverse needs to be chained with sort.Sort and doesn't sort the array if used on it's own (see [docs](https://pkg.go.dev/sort#Reverse))
* Opted to remove the sorting structs because we can just do it with sort.Slice which is simpler
> fix: amr claim should contain provider_id for sso method

- internal/api/provider/apple.go
- internal/api/token_oidc.go
> fix: skip apple oidc issuer check

- .github/workflows/release.yml
fix formatting for the checksum in the release notes
> ci: fix formatting for checksum in release notes

- .github/workflows/release.yml
fixing the yaml [syntax error](https://github.com/supabase/auth/actions/runs/15924164060)
> ci: fix yaml syntax error

- .github/workflows/release.yml
> fix: add `id-token` permission to ci

- .github/workflows/release.yml
> fix: run release-please again

- internal/api/apitask/apitask.go
- internal/api/apitask/apitask_test.go
- internal/api/options_test.go
Quick PR to button up the apitask package.
> chore: add 100% test coverage to apitask package
